### ISSUE TITLE
Check for parentheses around require(_once)/include_(once)

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#1007]
There doesn't appear to be any checks if files are included as:

```php
include '/path/to/file.php';
```
or
```php
include ( '/path/to/file.php' );
```

(Repeat for `include_once`, `require`, `require_once`.)

WordPress Core apparently does a mixture of both.

Generally, there is no different between them, except when a comparison is done against it - see Example 4 on http://us1.php.net/manual/en/function.include.php. Otherwise, the `(` `)` are redundant and can be safely removed.

There is a [PEAR sniff](https://github.com/squizlabs/PHP_CodeSniffer/blob/b95ff2c3b122a3ee4b57d149a57d2afce65522c3/src/Standards/PEAR/Sniffs/Files/IncludingFileSniff.php#L54) that could be used / adapted from.

This was [mentioned](https://wordpress.slack.com/archives/C5VCTJGH3/p1498611873198551) in the #core-coding-standards channel, so while any addition would go into `WordPress-Extras` right now, it may be that the Handbook has been updated, so this could go into `WordPress-Core` standard instead.

**Comment by johnbillion** [comment]
Not including parentheses is actually faster because PHP treats it as the language construct instead of a function. Definitely falls under micro-optimisation though.
