### ISSUE TITLE
Closing PHP tag errors for themes

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#1013]
I was just running the latest version WPCS on `_s`. After fixing a [few of items which were simple](https://github.com/grappler/_s/commit/ab8ca82e526484884547aef52461c7337d2b6ff8) there there were still item left which I am not fully sure how best to fix them or if they are false positives.

```
FILE: /_s/comments.php
----------------------------------------------------------------------
FOUND 8 ERRORS AFFECTING 8 LINES
----------------------------------------------------------------------
 27 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
 31 | ERROR | [x] Line indented incorrectly; expected 3 tabs, found 4
    |       |     (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 37 | ERROR | [x] Line indented incorrectly; expected 3 tabs, found 4
    |       |     (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 44 | ERROR | [x] Line indented incorrectly; expected 3 tabs, found 4
    |       |     (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 49 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
 59 | ERROR | [x] Expected 1 space before closing PHP tag; 0 found
    |       |     (Squiz.PHP.EmbeddedPhp.SpacingBeforeClose)
 70 | ERROR | [x] Expected 1 space before closing PHP tag; 0 found
    |       |     (Squiz.PHP.EmbeddedPhp.SpacingBeforeClose)
 87 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 8 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: /_s/header.php
----------------------------------------------------------------------
FOUND 3 ERRORS AFFECTING 2 LINES
----------------------------------------------------------------------
 30 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
 38 | ERROR | [x] Line indented incorrectly; expected 0 tabs, found 3
    |       |     (Generic.WhiteSpace.ScopeIndent.IncorrectExact)
 38 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 3 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: /_s/template-parts/content-none.php
----------------------------------------------------------------------
FOUND 4 ERRORS AFFECTING 4 LINES
----------------------------------------------------------------------
 19 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
 21 | ERROR | [x] Opening PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeOpen)
 34 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentAfterEnd)
 42 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 4 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------

FILE: /_s/template-parts/content.php
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 21 | ERROR | [x] Closing PHP tag must be on a line by itself
    |       |     (Squiz.PHP.EmbeddedPhp.ContentBeforeEnd)
----------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
----------------------------------------------------------------------
```

**Comment by JDGrimes** [comment]
See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/465#issuecomment-309233372 and #991. I don't think that these are false positives. The best fix depends, but generally just move the opening and closing PHP tags to their own lines, or so that both the opening and closing tag are on the same line. Your fixes thus far looked good to me.

**Comment by GaryJones** [comment]
Also see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1000#issuecomment-312435341 (and the question in the comment before that response).

**Comment by grappler** [comment]
Ok, I have made a [few more changes.](https://github.com/grappler/_s/commit/d23ac8c69e3487ab45ff421ae55d3774c51edcd7) Do you think they make sense?

The one I am still stuck on is `<?php endif; // Check for comment navigation. ?>`

**Comment by JDGrimes** [comment]
> The one I am still stuck on is <?php endif; // Check for comment navigation. ?>

Yeah, I found that it didn't handle comments just before a closing PHP tag. Apparently PHPCS considers the space before the closing tag to be a part of the comment token, so it doesn't detect that there is a space between the comment and the closing tag. There is no way to get around this that I could find, other than removing the comments.

**Comment by GaryJones** [comment]
```php
<?php
endif; // Check for comment navigation.
?>
```

?

**Comment by jrfnl** [comment]
This would work as well: `<?php endif; /* Check for comment navigation. */ ?>` (different comment style)

**Comment by JDGrimes** [comment]
> This would work as well: <?php endif; /* Check for comment navigation. */ ?> (different comment style)

Yep, I forgot that I had also done that to work around it.

**Comment by grappler** [comment]
Thanks! Created a PR for it. https://github.com/Automattic/_s/pull/1157

**Comment by jrfnl** [comment]
FYI: The _not correctly handling of a `//` comment before a closing tag_ was also reported in #1017 (as a fixer conflict bug). It was determined this was an upstream bug - https://github.com/squizlabs/PHP_CodeSniffer/issues/1549, and has since been fixed in both the 2.x as well as the 3.x branches. The fix is not (yet) in a released version.

**Comment by mirzazeyrek** [comment]
same here:

```
			<script type="text/javascript">
				window.MK = window.MK || {};
				MK.HB = MK.HB || {};
				MK.HB.WP = MK.HB.WP || {};
				MK.HB.store = <?php echo get_option( 'header_builder', array() ); // WPCS: XSS ok. ?>;
				MK.HB.WP.menus = <?php echo wp_json_encode( wp_get_nav_menus() ); // WPCS: XSS ok. ?>;
			</script>
```

any suggestions ?

**Comment by jrfnl** [comment]
@mirzazeyrek The fixes have been merged upstream, but no new releases have been made yet. If you use PHPCS `master` branch, you should be fine (depending of course on how you install PHPCS).

**Comment by mirzazeyrek** [comment]
@jrfnl 

composer global require squizlabs/php_codesniffer

and my version is 3.0.2

also I'm using latest version of master from wpcs repo.

What would you suggest for install ?

**Comment by jrfnl** [comment]
@mirzazeyrek You need PHPCS / `master` for this for now, though I have heard rumors that PHPCS 3.1.0 will be released either this or next week. 3.1.0 will contain the fix.
