### ISSUE TITLE
How can I solve (or suppress) VIP error? (Type: Question

### ISSUE THREAD

**Issue by yousan** [WordPress-Coding-Standards/WordPress-Coding-Standards#1014]
Hi.

I got an error for `get_previous_post_link()`.

```
 24 | ERROR | get_previous_post_link() is highly discouraged due to
    |       | not being cached; please use
    |       | wpcom_vip_get_adjacent_post() instead.
```

How can I solve this error?

1. Get wpcom_vip_get_adjacent_post() and other vip functions. But where is those functions?
2. Use // PHPCS: xxx ok inline ignoring comment. But which comment should be used?
3. Use @codingStandardsIgnoreStart and End comment. But...

Thanks.

**Comment by jrfnl** [comment]
@yousan There are a couple of options open to you:

You are clearly using the `WordPress` or `WordPress-VIP` ruleset. The `WordPress` ruleset includes the `VIP` sniffs of which most are only really applicable for themes and plugins which are seeking permission to be used on the `wordpress.com` managed platform (which is where the functions mentioned exist).

Now you can either say _"I'm not interested in anything VIP related, not even the bits which are not VIP platform specific"_. In that case, I suggest you use the `WordPress-Extra` ruleset instead.

Alternatively, you can exclude just that particular error code `WordPress.VIP.RestrictedFunctions.get_adjacent_post_get_previous_post_link`, that particular sniff `WordPress.VIP.RestrictedFunctions` or the whole VIP specific sniff category `WordPress.VIP`.

If you have a custom ruleset, you can do so from the ruleset using `<exclude name="<name>"/>`.
If you don't use a custom ruleset, add `--exclude=<name>` to your command line command to do the same.
_(replace `<name>` in both cases with any of the three names I mention in the paragraph above)_

Does that answer your question ?

**Comment by yousan** [comment]
Really Thanks!
```
        <exclude name="WordPress.VIP" />
```
