### ISSUE TITLE
Adding custom whitelist comments to custom sniffs?

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#1022]
Is it possible to add a custom whitelist comment in my custom sniff?

To be more exact, I would like to include `WordPress.Files.FileName.NotHyphenatedLowercase` except in some files, where I'd like to be able to add a comment at the beginning of the file (kinda like in ESLint) to exclude that file.

I could add those files in the exclude list, but that kinda defeats the purpose of the automation check :D

**Comment by grappler** [comment]
Try adding this to the file header.

`// @codingStandardsChangeSetting WordPress.Files.FileName exclude NotHyphenatedLowercase`

**Comment by grappler** [comment]
Here is another way. https://stackoverflow.com/questions/20743054/exclude-a-specific-phpcs-rule-for-a-specific-file

`phpcs.xml.dist`
```
 <rule ref="WordPress.Files.FileName.NotHyphenatedLowercase">
    <exclude-pattern>*/single.php/*</exclude-pattern>
 </rule>
```

**Comment by dingo-d** [comment]
Thanks for the suggestions, I'll try to implement this.
