### ISSUE TITLE
Uncaught exception 'ReflectionException' in custom ruleset

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#1023]
I created a custom ruleset https://github.com/infinum/wp-coding-standards and when I install it, and try to test it, using

`vendor/bin/phpcs --standard=vendor/infinum/wp-coding-standards wp-content/themes/twentyseventeen/functions.php`

I get the error

```sh
Fatal error: Uncaught exception 'ReflectionException' with message 'Class wp-coding-standards_Sniffs_Classes_OnlyClassInFileSniff does not exist' in /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1420
Stack trace:
#0 /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer.php(1420): ReflectionClass->__construct('wp-coding-stand...')
#1 /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer.php(594): PHP_CodeSniffer->registerSniffs(Array, Array, Array)
#2 /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(956): PHP_CodeSniffer->initStandard(Array, Array, Array)
#3 /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php(113): PHP_CodeSniffer_CLI->process()
#4 /www/wordpress-default/public_html/vendor/squizl in /www/wordpress-default/public_html/vendor/squizlabs/php_codesniffer/CodeSniffer.php on line 1420
```

It's like that it doesn't recognize the custom sniffs I added. Any ideas what am I doing wrong? My guess is something is wrong with the path, but I don't know what exactly.

When I add the sniffs (copy paste to my global installation of wpcs) in a custom ruleset that I named `Infinum`, the sniffs work just fine in my Sublime, and in the terminal.

**Comment by grappler** [comment]
The folder structure should be `vendor/infinum/wp-coding-standards/Infinum/Sniffs`.

PHPCompatibility had the same issue. https://github.com/wimg/PHPCompatibility/issues/102

Side Note: I would not call them `wp-coding-standards` but just `wp-coding-standards`  as they are really your coding standards and not those of WordPress.

Second Side Note: I don't think GitHub is the best place for support questions especially when they are not specific to WPCS. This policy is placed in other Open Source Projects too. I am not sure what @jrfnl @GaryJones @westonruter @JDGrimes think. My personal recommendation would be to add this question on some place like Stackoverflow. I would be happy to answer the question there.

**Comment by ntwb** [comment]
This repo does not offer support for other PHPCS projects, you should consult the PHPCS documentation to debug any issues.

---- 

Can I also suggest you rename your repo to something like `infinum-coding-standards`, as your repo name as it stands `wp-coding-standards` is easily misconstrued.

----

_edit: @grappler, your comment landed seconds before I hit submit here, I'll keep my comment as it was how I was originally going to submit it._

**Comment by jrfnl** [comment]
Closing as this question is unrelated to WPCS.

**Comment by dingo-d** [comment]
Thanks for the help and advice, will keep them in mind the next time :)

**Comment by ntwb** [comment]
Thanks @dingo-d, will you rename your repo?

**Comment by dingo-d** [comment]
I renamed it to `coding-standards-wp`, we have some coding standards in the firm already so I need to differentiate them, hope this is ok.
