### ISSUE TITLE
Fatal Error Using WPCS Standards

### ISSUE THREAD

**Issue by cedon** [WordPress-Coding-Standards/WordPress-Coding-Standards#1027]
Getting a Fatal Error when attempting to use WPCS under Windows 10.0.14393. Using the command `phpcs metaboxes.php --standard=WordPress` give the following error:
 `Fatal error: Interface 'PHP_CodeSniffer_Sniff' not found in C:\php\pear\PHP\CodeSniffer\src\Standards\WordPress\Sniff.php on line 18`

Using specific standards like WordPress-Extra or WordPress-Core all result in the same error.

PHP Version: 7.1.7
PHPCS Version: 3.0.1

I've attached the complete error in [wpcs_error.txt](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/files/1146042/wpcs_error.txt).

**Comment by cedon** [comment]
Forced a downgrade to PHPCS v2.9.1 and that made WPCS work.

**Comment by jrfnl** [comment]
That's it. WPCS is not (yet) compatible with PHPCS 3.x. See #718
