### ISSUE TITLE
Temporary feature freeze

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1040]
Once 0.12.0 has been released, I'd like to call for a temporary freeze on **all** merges until the PHPCS 3.x compatibility PR(s) has been pulled, merged and released as 0.13.0.

The PHPCS 3.x compatibility PR will touch nearly all files and solving conflicts & rebasing it is a lot of work which I'd rather avoid.

**Comment by GaryJones** [comment]
Understood.

**Comment by jrfnl** [comment]
Just to make sure we're on the same page: PRs tagged by me with `0.13.0` as milestone and the label `review-merge`, **_can_** be merged as those are part of the PHPCS 3.x compatibility efforts (and it will say so in the PR description and in the branch name).

All other PRs are on hold.

**Comment by jrfnl** [comment]
I've just opened two more PRs related to the PHPCS 3.x compatibility project and four which are sort of a side-results.

For those last four goes: they are ok to go into 0.13.0, but not necessarily a "must".

Shall we give people a chance to test for a week or so before releasing 0.13.0 ?

**Comment by GaryJones** [comment]
> Shall we give people a chance to test for a week or so before releasing 0.13.0 ?

Yes.
