### ISSUE TITLE
StrictInArraySniff should use strtolower in check

### ISSUE THREAD

**Issue by websupporter** [WordPress-Coding-Standards/WordPress-Coding-Standards#1061]
If you define your own ruleset in which you want to enforce constants in uppercase
( `$boolean = TRUE;`) but you want to use the `StrictInArray`-rule, you run into a problem, because this check relies on lowercase:
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/PHP/StrictInArraySniff.php#L83

This is not a problem, if you enforce lowercase anyway, but I think the `StrictInArraySniff` should not implicitly rely on this rule

**Comment by jrfnl** [comment]
Related to #763
