### ISSUE TITLE
Issue template

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#1066]
Maybe it would be a good idea to have issue template. I noticed that some repositories have this - you need to describe your issue in details, and provide information like version of the software, OS this happens on, steps to reproduce etc.

Thoughts?

**Comment by GaryJones** [comment]
Go for it. 

Using the raw versions of the files in https://github.com/GaryJones/plugin-boilerplate/tree/a2cca0aefc4df5585a7959851177fad9a12bd160/.github (has extra HTML comments only shown in raw) would be a good starting point.

**Comment by GaryJones** [comment]
Should probably provide a `.github/SUPPORT.md` as well.
https://github.com/blog/2400-support-file-support

**Comment by mikaelz** [comment]
Could be something like:
https://github.com/facebook/react/blob/master/docs/community/support.md
https://github.com/piwik/developer-documentation/blob/master/docs/support.md
https://github.com/jquery/learn.jquery.com/blob/master/page/about-jquery/additional-support.md

**Comment by jrfnl** [comment]
I personally am not necessarily a fan of issue templates.

For most people there is a barrier to report something anyway (am I doing it wrong or is the software wrong?), especially if it is someone who doesn't "live" on GitHub but might even need to register for GH to report something in the first place.

An issue template which asks for more than the bare minimum, will throw up an insurmountable barrier for people and often cause them to not report something at all.

**Comment by mikaelz** [comment]
But when they report it should be helpful for fixing. Saves some commenting. Sure it shouldn't be long, but some bare minimum as you mentioned.

SUPPORT.md is great to separate dev from support, of course if there is already an existing support channel.

**Comment by GaryJones** [comment]
I like them, and if there were insurmountable evidence that contributors didn't use them, GitHub wouldn't have bothered to introduce them.

So long as the questions are guiding, then providing a starting point for teasing out the information that needed for it to be helpful, is going to be more successful than a blank box to fill, and then that first round of "Please provide information ..." back and forth, which this issue template seeks to avoid.

**Comment by jrfnl** [comment]
> if there were insurmountable evidence that contributors didn't use them, GitHub wouldn't have bothered to introduce them.

Chicken/egg. There was no evidence at all as they didn't before GH introduced them...
