### ISSUE TITLE
Warning: Cannot declare interface \PHP_CodeSniffer_Sniff, because the name is already in use

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#1073]
I was not able to run WPCS because of the following error.
`Warning: Cannot declare interface \PHP_CodeSniffer_Sniff, because the name is already in use in ~/.composer/vendor/wimg/php-compatibility/PHPCSAliases.php on line 28`

`installed_paths: ~/.composer/vendor/wimg/php-compatibility,~/Documents/webdev/wpcs-theme/`

I am running
- PHPCS - `3.0.2` - Installed via composer
- PHPCompatibility latest `master` - Installed via composer
- WPCS - latest `develop` - installed via git

**Comment by jrfnl** [comment]
@grappler That was my bad, I'd originally used `class_exists()`, not `interface_exists()` there. There is an open PR in the PHPCompatibility repo to fix this which will be merged once @wimg is back from his vacation.
If you (temporarily) use the PR branch, things should work correctly (and confirm that my fix is solid).
https://github.com/wimg/PHPCompatibility/pull/488 -branch name `feature/prevent-conflicts-with-other-standards`

**Comment by jrfnl** [comment]
If you don't mind, I'll close this issue now as it's not a WPCS issue, but one in PHPCompatibility which will be fixed there.
