### ISSUE TITLE
Suggestion: Improve instructions for Atom 

### ISSUE THREAD

**Issue by jaredatch** [WordPress-Coding-Standards/WordPress-Coding-Standards#1082]
When using PHPCS+WPCS with the Atom linter, there is a rather strange and mostly undocumented configuration step that seems to be necessary.

The PHPCS package has a default tab width of `1`. This makes PHPCS+WPCS fail it seems. Changing this setting to `4` resolves it.

Here's the issue https://github.com/AtomLinter/linter-phpcs/issues/280

Setting https://cl.ly/3n063J1i1W1K (under linter-phpcs).

Would be helpful to note this in the readme for new users - I lost a lot of time trying to debug why things were failing! :)

**Comment by JDGrimes** [comment]
Seems like maybe this is something that should also be addressed by linter-phpcs. I took a quick look at the code, and it seems that it already has special handling for WPCS, but only to avoid errors when attempting to override the tab width on PHPCS versions that don't support overriding the standard.  https://github.com/AtomLinter/linter-phpcs/commit/0155dff8863577867a5c8fd815372c2cb29a6f72#commitcomment-22121762 indicates that setting the tab width manually is the recommended solution. I'd think that ideally, if no tab width was explicitly set, the standard would be allowed to override the default (and why a default tab width of 1 anyway?!). But I guess that at least for now, this is the way it is, and we ought to add a note about this.

**Comment by jrfnl** [comment]
I don't mind an extra line with instructions being added to the Atom install instructions, but this feels like a shortcoming in the `linter-phpcs` application. WPCS explicitely sets `tab-width` to 4 in the ruleset. PHPCS respects that, `linter-phpcs` apparently doesn't.

**Comment by GaryJones** [comment]
I'm in agreement with the others. No bug with our code, but happy for the work around for linter-phpcs to be documented within the Readme here.

**Comment by jaredatch** [comment]
Yep, sounds about right. No idea why the Atom package ignores it (no issue when I was using Sublime Text), but it took me entirely too much time and frustration to figure out the fix, which thankfully was easy.

There is some other interesting (and probably related) things that the Atom linter does as well, like if you have `<arg name="report">` specified in your PHPCS config, it causes the linter to fail (https://github.com/AtomLinter/linter-phpcs/issues/95#issuecomment-316133107).
