### ISSUE TITLE
Custom Post Type Templates Throw Warnings When Containing Underscores

### ISSUE THREAD

**Issue by desrosj** [WordPress-Coding-Standards/WordPress-Coding-Standards#1088]
Custom post type names adhere to the rules within `sanitize_key()` (lowercase alphanumeric characters, dashes, and underscores).

This means, if you register post type `some_post_type` it is perfectly fine. The archive and single templates will be `archive-some_post_type.php` and `single-some_post_type.php`. This however, triggers the `WordPress.Files.FileName.NotHyphenatedLowercase` sniff.

**Comment by jrfnl** [comment]
See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#themes-allow-filename-exceptions

**Comment by GaryJones** [comment]
I'm going to assume that answers your issue @desrosj, but please follow-up if not.
