### ISSUE TITLE
No longer require wpcom_vip_get_term_link, wpcom_vip_get_category_by_slug, wpcom_vip_get_term_link as of WP 4.8

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#1096]
From the WordPress VIP blog:

> Several previously uncached core functions are now cached as of WordPress 4.8:
> 
> get_term_by()
> get_category_by_slug()
> get_term_link()
> get_tag_link()
> get_category_link()
>
> As a result, we are deprecating the following VIP functions in favor of using the equivalent core functions instead:
> 
> wpcom_vip_get_term_by()
> wpcom_vip_get_category_by_slug()
> wpcom_vip_get_term_link()
>
> Please make sure you use the core functions instead of the deprecated VIP functions in your future commits.

Therefore, update RestrictedFunctionSniffs to no longer require these functions. Instead, flag them as deprecated.
- wpcom_vip_get_term_link()
- wpcom_vip_get_category_by_slug()
- wpcom_vip_get_term_link()

**Comment by JDGrimes** [comment]
This should already be fixed by #969, which has been merged into `develop` and will be part of the 0.14.0 release.
