### ISSUE TITLE
Forced new lines with associative arrays of one item

### ISSUE THREAD

**Issue by Rarst** [WordPress-Coding-Standards/WordPress-Coding-Standards#1104]
`WordPress.Arrays.ArrayDeclarationSpacing.AssociativeKeyFound` insists on multi–line array notation in _all_ cases, including array only having single item.

So to satisfy it `[ 'foo' => 'bar' ]` needs to be rewritten as
```php
[
    'foo' => 'bar',
]
```
which can be hugely space–wasting within function calls and such:
```php
function_call( 'foo', [
    'bar' => 'baz',
], 'stuff' );
```
While [letter of the rules](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation) makes no distinction for number of items, I feel applying this literally to single–item arrays is counter–productive.

Though maybe should be clarified in the rules upstream first? Not sure whom to poke about it.

**Comment by JDGrimes** [comment]
I agree, and I said something similar when that sniff was first added, see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/773#discussion_r95234082. I think that this could be updated in the handbook, but either way the option ought to be added to this sniff to ignore single-item arrays.

**Comment by westonruter** [comment]
I went ahead and updated the coding standards to not require line breaks when there is only one item in the array: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation

There are a lot of examples of this in core, for example:

```php
$settings = array( 2 => $settings );
$instance = wp_parse_args( (array) $instance, array( 'title' => '' ) );
return new WP_Error( 'rest_trash_not_supported', __( 'Users do not support trashing. Set force=true to delete.' ), array( 'status' => 501 ) );
```

**Comment by jrfnl** [comment]
> There are a lot of examples of this in core

Core doesn't comply with most of their own standards. That doesn't mean the rule is wrong.

I'm quite happy to allow an exception - possibly based on a property - for one item associative arrays, but whether it should be allowed or not, should be based on a discussion of the rule, not on code found in core.

**Comment by jrfnl** [comment]
On a different note: what should such a property be called ? `allow_single_item_single_line_associative_arrays` seems excessively long winded :wink:

**Comment by GaryJones** [comment]
> I went ahead and updated the coding standards

@westonruter:

Can you please change:

"For associative arrays, values should start on a new line, particularly when the array contains more than one item:" 

to

"Keys in associative arrays should start on a new line when the array contains more than one item:"

It'll correct _values_ to _keys_, and make the phrase less ambiguous.

(Also, there's no textual mention in the handbook about the alignment of `=>` in associative arrays, yet the code examples does that.)

**Comment by jrfnl** [comment]
> "Keys in associative arrays should start on a new line when the array contains more than one item:"

> It'll correct values to keys, and make the phrase less ambiguous.

Actually, I think that's still ambiguous.

What about: _""For associative arrays, **each item** should start on a new line when the array contains more than one item:""_

**Comment by jrfnl** [comment]
@westonruter The examples in the handbook now do not match the rule as it is.
