### ISSUE TITLE
Applying new line after brace to alternative controls structures

### ISSUE THREAD

**Issue by Rarst** [WordPress-Coding-Standards/WordPress-Coding-Standards#1106]
`Squiz.ControlStructures.ControlSIgnature.NewlineAfterOpenBrace` produces `Newline required after opening brace` on alternative `if`:

```php
<?php if ( $disabled ) : ?> disabled="disabled"<?php endif; ?>
```

1. Technically there isn't even a brace. :)
2. This seems like an overreach, especially since whitespace _is_ meaningful within HTML context, unlike PHP.

The [example in standards](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style) seems perfectly fine with lack of new line in such context, I would say this form in the loop is pretty much staple everywhere:

```php
<?php while ( have_posts() ) : the_post(); ?>
```

**Comment by jrfnl** [comment]
This has been discussed in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1000

**Comment by Rarst** [comment]
I am not sure I follow how one relates to another?

This one is about alternate `if` syntax, not PHP tags.

**Comment by ntwb** [comment]
Related: #1106 ( In regard to `<?php while ( have_posts() ) : the_post(); ?>` snippet

**Comment by Rarst** [comment]
@ntwb ehm, you linked to this issue itself? :)

**Comment by ntwb** [comment]
Ha, my bad @Rarst, sorry, I meant #1085

**Comment by Rarst** [comment]
Right, I'll close this one as a duplicate, cheers.
