### ISSUE TITLE
NoNonceVerification triggered when nonce verification is inside a switch statement

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1114]
Given the following piece of code, the `WordPress.CSRF.NonceVerification.NoNonceVerification` warning will be triggered, even though a nonce check is present. The culprit appears to be the `switch` statement.

```php
function my_function() {
	if ( ! isset( $_REQUEST['action'] ) ) {
		return;
	}

	switch ( $_REQUEST['action'] ) {
		case 'foo':
			check_admin_referer( 'foo' );
			foo();
			break;
		case 'bar':
			check_admin_referer( 'bar' );
			bar();
			break;
	}

}
```

**Comment by JDGrimes** [comment]
Note that the warning would also be given for a similar if condition:

```php
	if ( 'foo' === $_REQUEST['action'] ) {
		check_admin_referer( 'foo' );
		foo();
	}
```

Perhaps we should treat comparisons the same way that we do `isset()` checks, and only give a warning for them if they aren't followed by an nonce check.
