### ISSUE TITLE
Faulty core fixes: Tabs replaced with spaces in multiline string

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#1119]
Given the following example:

```php
<?php

$foo = array(
	"
	",
);
```

The `\t` inside the string (ie, before the second `"`), is being incorrectly replaced with 4 spaces.

**Comment by jrfnl** [comment]
Confirmed and found to be a bug in the upstream `Squiz.Strings.DoubleQuoteUsage` sniff. Will see if i can find a fix for it.

**Comment by jrfnl** [comment]
I've pulled a fix upstream - see PR https://github.com/squizlabs/PHP_CodeSniffer/pull/1640

**Comment by jrfnl** [comment]
The upstream PR has been merged in the mean time to PHPCS `master` and will be included in the 3.1.0 release.
