### ISSUE TITLE
Do my theme PHP files need to use the standards?

### ISSUE THREAD

**Issue by paulcanning** [WordPress-Coding-Standards/WordPress-Coding-Standards#1131]
So I have gone through my plugin and cleaned it up using PHPCS.

Now I am trying to clean up my theme.

The theme obviously has PHP files, but how do I deal with the main doc comment?

Custom templates need to use `/* Template Name: Foo */` but this is not valid PHPDoc?

**Comment by jrfnl** [comment]
If you change it to a docblock, it should be fine AFAIK (for both WP as well as WPCS):
```php
/**
 * Template Name: Foo
*/
```

**Comment by paulcanning** [comment]
And... you're correct :)

**Comment by GaryJones** [comment]
You can also make it a full file-header:

```php
<?php
/**
 * Landing page template
 *
 * Template Name: Landing
 *
 * @package  Gamajo\MyTheme
 * @author   Gamajo
 * @link     http://gamajo.com/
 * @license  GPL2-0+
 */
```
