### ISSUE TITLE
Template PHPDoc conflict

### ISSUE THREAD

**Issue by paulcanning** [WordPress-Coding-Standards/WordPress-Coding-Standards#1132]
I have encountered a conflict in one of my theme files.

I am using `wp_nav_menu` and it is saying I need a DOCBlock, so I started adding one.

However, I am in a situation where trying to correct it is impossible, as it conflicts with itself.

See the following screenshots:

Screenshot 1 shows an error stating there must be a line between the doc block and the method.
<img width="501" alt="screen shot 2017-09-08 at 16 39 49" src="https://user-images.githubusercontent.com/1275739/30219716-de2f5f6a-94b4-11e7-804d-32006fa203f4.png">

Screenshot 2 shows an error stating there is whitespace found at the end of the line
<img width="519" alt="screen shot 2017-09-08 at 16 40 01" src="https://user-images.githubusercontent.com/1275739/30219732-e47637d6-94b4-11e7-8125-f120c9998a9a.png">

I'm a tad confused with the whole PHPCS when it comes to themes, as most files are not pure PHP code.

**Comment by JDGrimes** [comment]
You just need to remove the whitespace at the end of the line, the line should be completely blank, no tabs.

----

Usually what people do in theme template files is add a PHP block at the top just for the file docblock to go in.

**Comment by paulcanning** [comment]
Eurgh, I hate PHPStorm sometimes!

Really counter-intuitive to hit return for a newline and then have to delete the tabs.

**Comment by JDGrimes** [comment]
PHPStorm's settings can be adjusted to remove whitespace from the end of lines when the file is saved (this might even be the default, I don't remember). However, the line that the cursor is on will always have the whitespace behind the cursor left, so that the cursor won't be forcibly moved.

**Comment by westonruter** [comment]
![image](https://user-images.githubusercontent.com/134745/30229204-d23ee8de-9495-11e7-8277-d9f5a2ccaf3d.png)

**Comment by GaryJones** [comment]
Why does a function call need a DocBlock?

**Comment by jrfnl** [comment]
> Why does a function call need a DocBlock?

@GaryJones It doesn't, but if it's the first PHP content in a (template) file, a _file_ docblock is expected.
I can imagine that the messages received about this through PHPStorm may not be as intuitive as the full result report the command line provided.
Anyways, this is commonly solved by having a separate PHP block with the file docblock at the top of the file, not by having the docblock above the first PHP content in the file.

**Comment by GaryJones** [comment]
> Anyways, this is commonly solved by having a separate PHP block with the file docblock at the top of the file, not by having the docblock above the first PHP content in the file.

Agreed - I always do this, so hadn't spotted the apparent flaw in the logic before.

**Comment by jrfnl** [comment]
@paulcanning Just checking: Has your question been sufficiently answered ?

**Comment by paulcanning** [comment]
Looks like it has, thanks :)
