### ISSUE TITLE
Access to undeclared static property: PHP_CodeSniffer_Tokens::$textStringTokens 

### ISSUE THREAD

**Issue by burhandodhy** [WordPress-Coding-Standards/WordPress-Coding-Standards#1133]
Hi,

I'm getting this error. My PHP is 7.1.1

`PHP Fatal error:  Uncaught Error: Access to undeclared static property: PHP_CodeSniffer_Tokens::$textStringTokens in C:\xampp\php\pear\PHP\CodeSniffer\Standards\WordPress\Sniffs\VIP\AdminBarRemovalSniff.php:144`

**Comment by jrfnl** [comment]
What version of WPCS and of PHPCS are you using ?
This error sounds like you are using a PHPCS version which does not match the requirements of WPCS. For the current WPCS version, you need PHPCS 2.9.0+ or 3.0.2+.

**Comment by burhandodhy** [comment]
It's old version of PHPCS that causing the problem. I update it and it fixed the problem. Thank you 👍
