### ISSUE TITLE
Documentation: Using cache and db call flags together

### ISSUE THREAD

**Issue by barryceelen** [WordPress-Coding-Standards/WordPress-Coding-Standards#1140]
The [wiki page](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors) says:

> For historical reasons, the cache and db call flags cannot currently be used together, although each of them can be used along with any other flags.

It seems they work fine when using them together.
I’d be happy to update the wiki page to reflect that.

**Comment by JDGrimes** [comment]
You're right. I had added that note because this doesn't work:

```
$wpdb->get_results(); // cache, db call OK.
```

However, this *does* work:

```
$wpdb->get_results(); // cache OK, db call OK.
```

I'll update the page to reflect that.

Thanks for pointing this out!
