### ISSUE TITLE
Enhancement: add new sniff to verify optimized use of `wp_enqueue_...` functions

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1146]
I'd like to propose a new sniff to be added to the `Extra` ruleset to verify the following two things:
* That all calls to these methods which pass a `$src`, also pass something for `$ver`.
    
   Reason: Not passing the `$ver` argument can cause issues with browser caching/the wrong version of a script/stylesheet being used.
* That all calls to the script enqueue methods pass the `$in_footer` argument and warn if the `$in_footer` argument is set to `false`.
    
    Reason: The default value for `$in_footer` is `false`. Not passing the argument means the script will load in the HTML header, i.e. in a layout rendering blocking manner. This is rarely needed.
    By demanding the argument to be present at least the dev will have to think about this and (hopefully) will set the value to `true` in most cases.

Loosely related to #867

Refs;
* https://developer.wordpress.org/reference/functions/wp_register_script/
* https://developer.wordpress.org/reference/functions/wp_enqueue_script/
* https://developer.wordpress.org/reference/functions/wp_register_style/
* https://developer.wordpress.org/reference/functions/wp_enqueue_style/
* https://codex.wordpress.org/Function_Reference/wp_register_style

**Comment by westonruter** [comment]
Note that technically these sniffs should be about `wp_register_script()` and `wp_register_style()`. The fact that the corresponding enqueue functions allow you to enqueue and register at the same time is just a shortcut, and one that I don't think is a good practice. I think it's better to register all your scripts during `wp_default_scripts` and `wp_default_styles`, at least for core feature plugins, and then later to just `wp_enqueue_script( $handle )`. This ensures you can just reference a handle regardless of the context where you're enqueueing the asset, and there isn't a need to copy the `$src` in multiple places.

If possible, it would also be nice to include `wp_scripts()->add()` and `wp_styles()->add()` in these checks, also assuming that variables `$wp_scripts`and `$scripts` or `$wp_styles` and `$styles` may be used instead. Examples: https://github.com/WordPress/better-code-editing/blob/0.7.0/wp-includes/script-loader-addendum.php

**Comment by westonruter** [comment]
> That all calls to the script enqueue methods pass the $in_footer argument and warn if the $in_footer argument is set to false.

Once/if core supports adding `defer` or `async` to registered scripts, this should be detected and the warning should not be issued. See https://core.trac.wordpress.org/ticket/22249

**Comment by jrfnl** [comment]
@westonruter Thanks for your input. Both sound like good points.

**Comment by jrfnl** [comment]
> In other words, it's not mandating that you register scripts/styles prior to enqueueing.

That is a different issue and not something which the sniff in #1378 needed to solve.

This would probably best be discussed in a new issue as the original issue reported here has been solved and the issue closed.

Personally I'm not sure whether WPCS should warn about a shortcut which was build into WP to specifically act as a shortcut. I'm not familiar with caching by service workers, so I'm not sure whether this is an edge case or common practice. Altogether, I'd like to hear some more opinions from people before we decide whether or not to add this to WPCS.
