### ISSUE TITLE
Forbid usage of `goto` ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1149]
Should we add a sniff to forbid the use of the `goto` language construct ?

Use of `goto` can be considered a code smell.

Proposed for ruleset: `Extra`.

Sniff would be a candidate to be upstreamed. No upstream sniff for this currently exists.

**Comment by westonruter** [comment]
💯 I forgot that `goto` even is part of PHP. I definitely should not be used. It isn't in core, so I think it should be safely implied to be part of the coding standards to not use it. I think it should go into `WordPress-Core` itself.

**Comment by jrfnl** [comment]
@pento :arrow_up: If you agree, could this be added to the handbook ? Maybe in the [clever code section](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#clever-code) ?

For that matter should `eval()` be forbidden for Core as well ? (not currently in the handbook - sniff for this is in the `Extra` ruleset).
10 points for inconsistency as usage of the PCRE `/e` modifier _is_ explicitly forbidden in the Core handbook: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#regular-expressions :sunglasses:

**Comment by westonruter** [comment]
There are no instances of `eval()` or `create_function()` in core, other than one instance of the latter in a 3rd-party library: https://github.com/WordPress/wordpress-develop/blob/6c8b9adeee80040d02fd0236af4c1481924bacf2/src/wp-includes/pomo/translations.php#L197-L209

**Comment by GaryJones** [comment]
Re-opening for `eval()` discussion.

**Comment by pento** [comment]
`goto` is now [verboten](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#clever-code).

**Comment by pento** [comment]
The last instance of `create_function()` is [gone](https://core.trac.wordpress.org/changeset/41722), so are [eval() and create_function()](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#clever-code) a banned, too.

**Comment by jrfnl** [comment]
@pento PRs to bring WPCS is line upcoming.

Regarding the handbook change:
* As far as I know `eval` has not been deprecated in PHP 7.2
* `eval` is also not a function, but a language construct

Maybe tweak the wording a little ?

**Comment by pento** [comment]
Good catch, fixed!

**Comment by jrfnl** [comment]
For the WPCS changes to bring it inline with the adjusted handbook, see #1177 and #1178
