### ISSUE TITLE
Fixer for PEAR.Files.IncludingFile.BracketsNotRequired assumes no spacing in parens

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#1153]
The fixer for `PEAR.Files.IncludingFile.BracketsNotRequired` (added in #1145) turns this:

```php
require_once( '/path/to/file.php' );
```

Into this:

```php
require_once  '/path/to/file.php' ;
```

- The space before the closing parenthesis is left.
- A new space is added after `require_once`, in addition to the space that already followed the opening parenthesis.

In other words, the fixer assumes that no extra whitespace will be here. Ideally, it should be whitespace agnostic. But because the sniff comes from upstream, it is possible that we'd need to create a custom sniff for our purposes instead.

**Comment by jrfnl** [comment]
Nice catch. I would propose we bug-fix the upstream sniff and submit the fix as a PR upstream.

**Comment by JDGrimes** [comment]
> I would propose we bug-fix the upstream sniff and submit the fix as a PR upstream.

Yes, it seems like that will work. I'm getting a PR ready now.

**Comment by JDGrimes** [comment]
I've opened https://github.com/squizlabs/PHP_CodeSniffer/pull/1670.

**Comment by jrfnl** [comment]
@JDGrimes Nice work! :+1:  I left some feedback in the PR.

**Comment by JDGrimes** [comment]
We ultimately decided that this shouldn't be fixed in the upstream sniff (https://github.com/squizlabs/PHP_CodeSniffer/pull/1670#discussion_r140101224):

>I'm wondering if modifying this sniff is really the way to go. It seems to be adding a lot of whitespace-related complexity to the fixer, when the sniff really has nothing to do with whitespace. There was already a precedent within the sniff, but checking on both sides of both parentheses is 6 different checks. It seems like the fixing should really be handled by sniffs specifically for whitespace, like `Squiz.WhiteSpace.LanguageConstructSpacing` and `Squiz.WhiteSpace.SemicolonSpacing`. The one whitespace check that was already part of this sniff makes sense, but I think maybe we should just add those two sniffs to the WordPress ruleset rather than adding more whitespace handling to this sniff.

Since the `PEAR.Files.IncludingFile` sniff was added to `Extra`, I guess for now these should just be added to `Extra` as well?

**Comment by jrfnl** [comment]
> Since the PEAR.Files.IncludingFile sniff was added to Extra, I guess for now these should just be added to Extra as well?

@JDGrimes The first one: yes.
As for the second one - `Squiz.WhiteSpace.SemicolonSpacing` -, that feels like such a generic undisputable implied rule, I'd happily see it go into the `Core` ruleset in the end section: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress-Core/ruleset.xml#L356

**Comment by jrfnl** [comment]
@JDGrimes It would be great if we could include these sniffs in the `0.14.0` release as the `PEAR.Files.IncludingFile` was also added in `0.14.0`. Have you got a chance to send in a PR for this ?

**Comment by JDGrimes** [comment]
@jrfnl I'll try to get a PR in later today.
