### ISSUE TITLE
Releasing 0.14.0 ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1158]
Further on #1157, I would like to propose releasing WPCS 0.14.0 some time over the next two weeks.

The release as it is, is already quite feature rich: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/milestone/14

I think it would be great if we could still get #1135 and #1136 over the finish line before then.
* #1135 is waiting on feedback from @pento 
* #1136 is waiting on feedback from @pento (in general) and from the @WordPress-Coding-Standards/wpcs-admins with regards to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1135#issuecomment-330322341

With #1157 in mind, I would like to propose leaving #1084 for a future release. /cc @GaryJones 

As for #1041, this needs a new review and if nothing blocking comes up, it could ship with 0.14.0, otherwise this can be moved to a future release. /cc @emgk

Any objections ? If not, please leave feedback where feedback is requested. Thanks :heart:

**Comment by GaryJones** [comment]
> I would like to propose leaving #1084 for a future release

Fine with me.

**Comment by jrfnl** [comment]
FYI: I've created a preliminary changelog and will keep updating it until we are ready to release.

Where this hadn't been done yet, I've updated the wiki pages with information about new (merged) sniff properties and whitelist flags.

I've also created PRs #1161 and #1162 to be in sync with the release.

**Comment by jrfnl** [comment]
I'm hoping to get clarification about a potential issue with the new `PreparedSQLPlaceholders` sniff before the release as it may need a fix to be more lenient about literal `%`'sses. See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1160#issuecomment-332324550
Fingers crossed this will be clarified soon.

**Comment by emgk** [comment]
> As for #1041, this needs a new review and if nothing blocking comes up, it could ship with 0.14.0, otherwise this can be moved to a future release.

Please let me know if I need to make any changes. :)

**Comment by jrfnl** [comment]
@emgk Sorry about the delayed second review. I will try and have a look later today.

@pento Any change of some feedback on #1135 and #1136 over the next week ?

**Comment by jrfnl** [comment]
Looks like we're nearly there.

I'm still working on an update to the `PreparedSQLPlaceholders` sniff which should go into this release. I should have that PR ready sometime this week.

Other than that #1163 is ready for merge and I *will* get to #1041 ;-)
