### ISSUE TITLE
Faulty Core Fix: Incorrect array item indentation after trailing comment

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#1179]
Given this sample:

```php
<?php
b( array(
    1 => false, // wat
    2 => false,
) );
```

Running `phpcbf`, the second array element is not indented correctly. Removing the comment causes it to be indented correctly.

Using PHPCS `master`, and WPCS `develop`.

**Comment by jrfnl** [comment]
@pento Thanks for reporting that. Nice catch. Patched in PR #1180.
