### ISSUE TITLE
Add sniff to detect unused variables and undefined variables

### ISSUE THREAD

**Issue by sirbrillig** [WordPress-Coding-Standards/WordPress-Coding-Standards#1221]
While it is not exactly a code _style_ concern, the use of undefined variables and creating variables without using them is nearly always a bug. 

The following typo is a trivial example, but it is the kind of thing that can easily make it into production code because a particular code path has not been adequately tested. 

```php
function update_my_post( $post_data ) {
  wp_insert_post( $post_info );
}
```

While it's possible to argue that this is the responsibility of testing, I'd make the case that WordPress and its plugins are of sufficient complexity that it's difficult to test all code paths adequately. Perhaps more importantly, WordPress is a vehicle for new developers to learn coding and therefore this project is in a unique position to help those developers avoid introducing new bugs into their own code.

PHPCS can easily detect these instances and prevent a whole class of bugs from appearing. Here is a set of PHPCS sniffs which does just that: https://github.com/sirbrillig/VariableAnalysis

If there's interest, I can work on integrating these sniffs into this ruleset.

**Comment by GaryJones** [comment]
Is there anything that would be WordPress-specific with the checks, or could folks just make use of your standard directly?

Aside: I'd love to see [support](https://github.com/DealerDirect/phpcodesniffer-composer-installer#developing-coding-standards) added for `"type": "phpcodesniffer-standard"` to make it easier to install.

**Comment by sirbrillig** [comment]
Wow, I didn't know about `phpcodesniffer-composer-installer`. That's awesome! I just added support for that to the package. 

However, I still think those rules should be added to this ruleset. If I were a new WP/PHP developer (or new to using linters anyway) I'd rather not have to figure out how to install multiple standards just to get what I'd call a "core" linting rule like looking for undefined variables. On top of that, PHPCS seems to me to be mainly designed to have "complete" rulesets which include everything you could need.

**Comment by grappler** [comment]
I don't think sniffs need to be added to WPCS. I think it is important the developers uderstand the tools that they are using. We can improve the documentation if it is not clear enough.

There is also [wimg/PHPCompatibility](https://github.com/wimg/PHPCompatibility) which developers could/should use.

By having the code separate to WPCS allows PHP developers use it even if they don't use WordPress.

I find that projects can be more agile when the strongly coupled together.

**Comment by GaryJones** [comment]
> On top of that, PHPCS seems to me to be mainly designed to have "complete" rulesets which include everything you could need.

There's a difference between WPCS using some of its own code + sniffs from Generic / Squiz / PSR2 (which are all built-in to PHPCS), and WPCS also trying to use your sniffs (which introduces an external dependency).

I'd much rather see your sniffs improve for the benefit of everyone - because even then, they can be added to [existing custom rulesets](https://github.com/GaryJones/plugin-boilerplate/blob/master/phpcs.xml.dist#L12-L18) along with other external standards.

> Wow, I didn't know about phpcodesniffer-composer-installer. That's awesome! I just added support for that to the package.

It's late now, but I'll give your package a whirl tomorrow - thanks!

Obviously, it's not quite the same, but unused parameters and undefined variables are typically highlighted in some way in IDEs anyway, so it's not easy to miss if you happen to be looking at the code. Here's PhpStorm:

![PhpStorm with code highlighting](https://user-images.githubusercontent.com/88371/32300598-3269cef4-bf52-11e7-8ba2-9de2cf52bef3.png)

**Comment by sirbrillig** [comment]
> I'd much rather see your sniffs improve for the benefit of everyone - because even then, they can be added to existing custom rulesets along with other external standards.

Well, I can't argue with that. I suppose that recommended custom rulesets (along with custom `require-dev`) can go a long way toward handling the "easy for the developer" setup I'd like to see. 

> Obviously, it's not quite the same, but unused parameters and undefined variables are typically highlighted in some way in IDEs anyway, so it's not easy to miss if you happen to be looking at the code.

I guess what I like about having such features in a separate tool like phpcs is that it can both show developers the issue in their editor and also add additional safeguards like being able to notice errors in a CI server if the developer did miss it (for example, by not using an IDE). Tangentially, if PhpStorm can find that error, it must be generating an AST and running its own linter... it'd be nice if that was available as a stand-alone CLI tool or as a plugin for something like phpcs. 🤔

**Comment by GaryJones** [comment]
@sirbrillig 

> That's awesome! I just added support for that to the package.

I think there may be a small issue with the support (it's not working quite how I expect) - if you could enable Issues on your repo, I'm happy to open an issue to go into more detail.

**Comment by sirbrillig** [comment]
@GaryJones whoops! I didn't realize issues were disabled. Maybe that happens automatically with forks. Done!

**Comment by kurdtpage** [comment]
For those coming across this via search engine, someone has created some standards for detecting unused/undefined variables here: https://github.com/sirbrillig/phpcs-variable-analysis
