### ISSUE TITLE
Missing @package tag in file comment (plugin header comment)

### ISSUE THREAD

**Issue by sandrodz** [WordPress-Coding-Standards/WordPress-Coding-Standards#1223]
WP docs don't mention requirement to have @package in the plugin header comment.

<img width="1270" alt="screen shot 2017-11-05 at 12 32 21 pm" src="https://user-images.githubusercontent.com/8479569/32413188-7537df70-c225-11e7-8626-0ff8a325bbfb.png">

**Comment by jrfnl** [comment]
The WP Core [PHP Documentation handbook page](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/php/#6-file-headers) explicitly requires every PHP file to have a file doc block with a `@package` tag.

For plugin "main" files, [the plugin headers](https://codex.wordpress.org/index.php?title=File_Header#Plugin) can be combined with the file doc block as shown in the second example.

Also see: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1070#issuecomment-318084020 for another example.

**Comment by athlan** [comment]
The presented example does not work https://codex.wordpress.org/index.php?title=File_Header#Plugin_File_Header_Example.


Example:

```
<?php
/**
 * Custom Fields Permalink 2.
 *
 * @package     WordPress_Custom_Fields_Permalink
 * @author      Your Name
 * @copyright   2016 Your Name or Company Name
 * @license     GPL-2.0+
 *
 * @wordpress-plugin
 * Plugin Name: Custom Fields Permalink 2
 * Plugin URI: http://athlan.pl/wordpress-custom-fields-permalink-plugin
 * Description: Plugin allows to use post's custom fields values in permalink structure by adding %field_fieldname%, for posts, pages and custom post types.
 * Author: Piotr Pelczar
 * Version: 1.0.3
 * Author URI: http://athlan.pl/
 */

require '...';
```

Result:
```
FILE: /vagrant/www/testwp/htdocs/wp-content/plugins/wordpress-custom-fields-permalink-plugin/wordpress-custom-fields-permalink-plugin.php
-----------------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
-----------------------------------------------------------------------------------------------------------------------------------------
 1 | ERROR | Missing file doc comment (Squiz.Commenting.FileComment.Missing)
-----------------------------------------------------------------------------------------------------------------------------------------

Time: 575ms; Memory: 6Mb
```

**Comment by jrfnl** [comment]
@athlan The example *does* work.

The `require` which is the first line of code in your file is a structural element for which the sniff would expect documentation as well. So, it now thinks the docblock you provided is for the `require`, not for the file, which is a completely different issue.

**Comment by athlan** [comment]
@jrfnl thank you for the quick response.

You are totally right. I didn't noticed that. After adding some additional comment before require statement, the general file comment works as expected.
