### ISSUE TITLE
WordPress-Docs should identify missing docblocks

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1225]
The WordPress-Docs ruleset doesn't currently trigger a warning/error for functions and methods which are completely missing a docblock.

**Comment by johnbillion** [comment]
Actually, I guess `Squiz.Commenting` takes care of this.

**Comment by westonruter** [comment]
But `Squiz.Commenting` is being included and I don't see that error being excluded.

**Comment by johnbillion** [comment]
User error! My ruleset was excluding`psr2`.
