### ISSUE TITLE
Allow class methods in the customAutoEscapedFunctions property

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1226]
It's not possible to pass a class method name into the `customAutoEscapedFunctions` property. This means a method which is safe for output still needs to be marked as ok:

```php
echo $this->build_toggler(); // WPCS: XSS ok;
```

This is similar to #1176 but not quite the same.

PHPCS 3.1.1, WPCS 0.13.1, PHP 7.1.0

**Comment by markkap** [comment]
just the problem I faced this morning

**Comment by jrfnl** [comment]
Duplicate of #413 ?
