### ISSUE TITLE
All output doesn't need to be run through esc!

### ISSUE THREAD

**Issue by sandrodz** [WordPress-Coding-Standards/WordPress-Coding-Standards#1228]
Any ideas how to format this properly to satisfy linter? I'm escaping url, I think that should be enough as rest of the string is hardcoded and bares no risk.

<img width="1403" alt="screen shot 2017-11-10 at 4 50 35 pm" src="https://user-images.githubusercontent.com/8479569/32659273-6ad97a50-c637-11e7-88a3-e2fae97cd2e0.png">

`echo '<div class="error"><p>' . sprintf( __( 'WooCommerce TBC Credit Card Payment Gateway: all merchant account fields are required! please fix it <a href="%s">here</a>.', 'pp-woo-tbc-cc' ), esc_url ( admin_url( 'admin.php?page=wc-settings&tab=checkout&section=' . $this->id ) ) ) . '</p></div>';`

**Comment by jrfnl** [comment]
Changing `__()` to `esc_html__()` should do the trick. This is not a hard-coded string, but a function call retrieving a translation and translations can not be seen as trusted data. (Translation might have issues, the file containing the translation may have been infected, the site the translation is updated from may be infected etc).

**Comment by sandrodz** [comment]
Here is the problem with `esc_html__`

![screen_shot_2017-11-10_at_5_17_34_pm](https://user-images.githubusercontent.com/8479569/32660148-1e71a152-c63b-11e7-9bd5-406b72a0c53d.png)

**Comment by JDGrimes** [comment]
You can wrap the entire `sprintf()` call in `wp_kses_data()`.

**Comment by sandrodz** [comment]
Thanks! I was looking exactly for that, somehow missed in docs, or func name didn't jump out

**Comment by dingo-d** [comment]
Shouldn't this be:

```php
sprintf( '<div class="error"><p>%s <a href="%s">%s</a></p></div>', esc_html__( 'WooCommerce TBC Credit Card Payment Gateway: all merchant account fields are required! Please fix it', 'pp-woo-tbc-cc' ), esc_url( admin_url( 'admin.php?page=wc-settings&tab=checkout&section' . $this->id ) ), esc_html__( 'here', 'pp-woo-tbc-cc' ) );
```

**Comment by sandrodz** [comment]
Absolutely, tired mind does weird things.

**Comment by JDGrimes** [comment]
@dingo-d Splitting up a string like that can make it more difficult for translators to translate it properly. It is considered best to keep a translation string in once piece in this case.

**Comment by dingo-d** [comment]
Well, he could add a translators comment, no? I think the comments appear in poEdit.

**Comment by sandrodz** [comment]
@dingo-d his point was about separating string `here`

In some languages `here` might not be at the end of the string.

**Comment by dingo-d** [comment]
I mean it's ok to wrap the whole thing in `wp_kses_post()`, just seemed a bit cleaner to me ;)

**Comment by GaryJones** [comment]
Split the code up into the formation of the text (with internationalisation including placeholder translator comment), and the display of it (which could be extracted to a view file):

```php
$text = sprintf(
	/* translators: %s: admin URL */
	__( 'WooCommerce TBC Credit Card Payment Gateway: all merchant account fields are required! Please fix it <a href="%s">here</a>.', 'pp-woo-tbc-cc' ),
	esc_url ( admin_url( 'admin.php?page=wc-settings&tab=checkout&section=' . $this->id ) )
);

?>
<div class="error">
	<p><?php echo wp_kses_post( $text ); ?></p>
</div>
<?php
```
