### ISSUE TITLE
WPCS when you use XAMPP and ECLIPSE

### ISSUE THREAD

**Issue by ramonamorea** [WordPress-Coding-Standards/WordPress-Coding-Standards#1231]
Hi, first let me thank you for your work to maintain this great repo!

My issue ....is not an issue, in fact.

I just wanted to help with a hint, those people who might try to install and use WordPress Coding Standards with Eclipse, based on a XAMPP installation. I already spent two days trying to accomplish this (works now like a charm!), so I thought this might help:

If you are a theme/plugin developer using XAMPP and Eclipse for development, these are the steps that will work for you to use the WordPress standards:

step 1) first install CodeSniffer using these exact steps:
http://subharanjan.com/setup-php-codesniffer-along-wordpress-coding-standards-windows-xampp/
(do not install codesniffer via composer, because via composer it will fail, because the XAMPP package already contains a code sniffer sub-package, so you will end up with two versions of code sniffer): 

step 2) then, since the most used code sniffer plugin for Eclipse ( http://phpsrc.org/ ) includes an OLD CodeSniffer version, which will not work with these WordPress Coding Standards, you'll have to install this Eclipse plugin instead: https://github.com/Webaib/net.overscale.eclipse.pti.tool.codesniffer

Notes:

- This was the only way to make WPCS, XAMPP, ECLIPSE work together (with their latest versions)

- Please note that XAMPP includes an old version of CodeSniffer too (even the XAMPP latest stable version 7.1.11 ), so you have to make sure that in c:\xampp\php\pear\PHP\CodeSniffer\src\ you have the latest version of CodeSniffer. If you don't have there the latest version, copy it manually from:
https://github.com/squizlabs/PHP_CodeSniffer

Useful command window commands:

phpcs --version 
shows your CodeSniffer versions

phpcs -i
shows all installed standards, you should see here WPCS too

Thanks, issue can be closed, I just wanted to add this, maybe it can help someone to spare two days of research :)

Have a good day/night everyone!

**Comment by jrfnl** [comment]
@ramonamorea Thanks for writing this up. Would you be willing to create a pull request adding something along the lines of the above to the readme ?
The `README.md` contains a section with additional install and usage information for various tools and adding a section for Eclipse would fit right in, I'd say.

See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#how-to-use

**Comment by ramonamorea** [comment]
I'm quite new to github, but I'll try to add this as soon as possible. Thank you for your reply!

**Comment by GaryJones** [comment]
At the very least @ramonamorea, feel free to copy and paste your notes into a new page on the [wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki) which may make it easier for folks to find.

Thanks for taking the time to do the write-up and help folks out! 🌟

**Comment by jrfnl** [comment]
@ramonamorea Just noticed the [new wiki page](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/How-to-use-WPCS-with-Eclipse-and-XAMPP). Thank you so much for creating that!
You may also want to add a link from the Readme to the wiki page to help people find it ?

**Comment by ramonamorea** [comment]
I would love to :) But stupid me, I bet it's a simple thing, but it seems I can't find from where to edit the Readme. I tried "New pull request" but it seems it does some sort of compare between branches. If anyone knows how to and has some time to add the link to the Readme, I'd appreciate it very much!

**Comment by GaryJones** [comment]
@ramonamorea Click through to the Readme file (https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/README.md) and then hit the pencil icon, top right.
