### ISSUE TITLE
Multiline indented string concatenation 

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#1243]
When building large regex, it's not unusual to build it over multiple lines, with indentation, to make it more readable.

For example, `dbDelta()`, as well as various KSES and shortcode handling functions.

A small example might look something like this:

```php
$regex = '/'
	. '('
	.     'foo'
	. '|'
	.     'bar'
	. ')'
	. '/';
```

The current behaviour of `phpcbf` is to remove the extra spaces after each `.`, which makes the regex unreadable.

Indenting with tabs before the `.` maintains the indenting, eg:

```php
$regex = '/'
	. '('
	    . 'foo'
	. '|'
	    . 'bar'
	. ')'
	. '/';
```

But it's also a common pattern to have trailing comments on the regex, explaining what each line is doing:

```php
$regex = '/'
	. '('       // Open the group
	.     'foo' // Foo
	. '|'       // Or
	.     'bar' // Bar
	. ')'       // Close the group
	. '/';
```

So the leading tab indenting will make it impossible to line these comments up.

Any suggestions for a way forward?

**Comment by jrfnl** [comment]
I'd actually suggest a completely non-PHPCS based solution, which IMHO is the better way to document large regexes like that, which is to use the PCRE native `x` modifier in combination with regex comments starting with `#` instead of using PHP concatenation and comments.

You can see an example of how this is used here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/52ff31fe4f686919fe367fc3153766cbb214c4d1/WordPress/Sniffs/WP/I18nSniff.php#L37-L56

Note: this does influence how you need to write the regex to match whitespace!
Let me know if you need help reworking the existing regexes in core.

Refs:
* http://php.net/manual/en/regexp.reference.comments.php
* http://php.net/manual/en/reference.pcre.pattern.modifiers.php

**Comment by pento** [comment]
Agreed, that's a better way of doing things. I think we use it in a few places in core, already.

**Comment by pento** [comment]
Actually, this option doesn't work for a couple of cases:

- `get_shortcode_regex()` and `_get_wptexturize_shortcode_regex()` return regular expressions without the `/` delimiters, those are added by the calling functions, so it's not possible to change the regex format.
- The `x` modifier doesn't allow whitespace within conditional subpatterns, which all of the regex use. 

I suspect the best option is going to be to mark them as `@codingStandardsIgnoreStart` / `@codingStandardsIgnoreEnd` blocks.

**Comment by jrfnl** [comment]
@pento Want me to have a look ? Could you give me links to the exact files/lines for each of these ?

> The x modifier doesn't allow whitespace within conditional subpatterns, which all of the regex use.

Do you mean "whitespace whitespace" (indentation and such) or whitespace as part of the pattern to match ? if the latter, I'm pretty sure you can use that, you just have to adjust the regex a little.

**Comment by jrfnl** [comment]
> I suspect the best option is going to be to mark them as @codingStandardsIgnoreStart / @codingStandardsIgnoreEnd blocks.

As WP Core will be using PHPCS `master` for now and I presume, PHPCS 3.2.0 and up once it is out, you can use the newer more specific ignore annotations which will be introduced in PHPCS 3.2.0.

See: https://github.com/squizlabs/PHP_CodeSniffer/issues/604

```php
// phpcs:disable Generic.Commenting.Todo, PSR1.Files.SideEffects -- Because reasons
... code ...
// phpcs:enable
```

**Comment by pento** [comment]
For indentation - from [the docs](https://secure.php.net/manual/en/reference.pcre.pattern.modifiers.php):

> Whitespace characters may never appear within special character sequences in a pattern, for example within the sequence (?( which introduces a conditional subpattern.

For example, I converted `get_html_split_regex()`, like so:

```php
function get_html_split_regex() {
	static $regex;

	if ( ! isset( $regex ) ) {
		$comments =
			'!          # Start of comment, after the <.
			(?:         # Unroll the loop: Consume everything until --> is found.
			    -(?!->) # Dash not followed by end of comment.
			    [^\-]*+ # Consume non-dashes.
			)*+         # Loop possessively.
			(?:-->)?    # End of comment. If not found, match all input.';

		$cdata =
			'!\[CDATA\[ # Start of comment, after the <.
			[^\]]*+     # Consume non-].
			(?:         # Unroll the loop: Consume everything until ]]> is found.
			    ](?!]>) # One ] not followed by end of comment.
			    [^\]]*+ # Consume non-].
			)*+         # Loop possessively.
			(?:]]>)?    # End of comment. If not found, match all input.';

		$escaped =
			"(?=          # Is the element escaped?
			   !--
			|
			   !\[CDATA\[
			)
			(?(?=!-)      # If yes, which type?
			    $comments
			|
			    $cdata
			)";

		$regex =
			"/(               # Capture the entire match.
			    <             # Find start of element.
			    (?            # Conditional expression follows.
			        $escaped  # Find end of escaped element.
			    |             # ... else ...
			        [^>]*>?   # Find end of normal element.
			    )
			)/x";
	}

	return $regex;
}
```

This caused a compilation failure:

`preg_split(): Compilation failed: unrecognized character after (? or (?- at offset 99`

**Comment by pento** [comment]
> As WP Core will be using PHPCS master for now and I presume, PHPCS 3.2.0 and up once it is out, you can use the newer more specific ignore annotations which will be introduced in PHPCS 3.2.0.

Oh, that's super useful! I didn't really want to remove all checks on the blocks of code. 🙂
