### ISSUE TITLE
Semver / version 1.0.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1247]
_Previously discussed in #287 and #519 and touched upon in #718 and #1157._

As the [big CS patch has gone into WP Core](https://make.wordpress.org/core/2017/11/30/wordpress-php-now-mostly-conforms-to-wordpress-coding-standards/) now and I'm proposing breaking changes for version `0.15.0` in #1157, I think it's time to revisit the Semver discussion.

Version `0.13.0` also contained breaking changes up to a point: for any standard which based itself on WPCS.
Now `0.15.0` will contain breaking changes - but with proposal 2 will stabilize the location of a number of sniffs to more logical places in the hierarchy.
Version `0.17.0` or `0.18.0` - depending on how we go - will **again** contain breaking changes as we'll be dropping PHPCS 2.x support and removing previously deprecated sniffs as well as removing sniffs where we can defer to upstream sniffs once the minimum PHPCS requirement has gone up to PHPCS 3.x as per #1048.

Keeping all that in mind, I think it's time.

Using Semver will allow us to better communicate what people can expect from a release, making it less painful to upgrade.

So, if people agree, this would mean that `0.15.0` would become the `1.0.0` release. If we call it `1.0.0` which would clearly signal a breaking change, it would also not necessarily just and only need to contain the breaking changes. We could then allow other finished PRs to also enter into the release.

And, unless there are breaking changes before that time, the "drop PHPCS 2.x support" release would become version `2.0.0`.

Opinions ?

/cc @WordPress-Coding-Standards/wpcs-admins 

Refs:
* https://semver.org/
* [The Fear of 1.0.0](http://jeremyckahn.github.io/blog/2013/12/29/the-fear-of-1-dot-0-0/)

**Comment by JDGrimes** [comment]
I would probably opt to wait and make the "drop PHPCS 2.x support" release 1.0.0, but I can't really think of a good reason to do that, other than that it just wouldn't feel like time for 2.0.0 yet. So I guess if there are no objections, we may as well go ahead and make this release 1.0.0.

**Comment by GaryJones** [comment]
It's a good a time as any.

**Comment by ntwb** [comment]
Go for it 🎉

**Comment by jrfnl** [comment]
As there is clearly consensus, I've renamed the `0.15.0` milestone to `1.0.0` and added some more milestones for the future.
