### ISSUE TITLE
Warnings

### ISSUE THREAD

**Issue by urre** [WordPress-Coding-Standards/WordPress-Coding-Standards#1283]
Hi,

Setting up phpcs and WPCS on Codeship Basic. I think the setup is working mostly as it should but I cant understand why i get these warnings on on single file. Locally i don't get warnings. I Use wpcs installed via git.

Thankful for input!

## The setup

Setup 
```php
phpenv local 7.1
git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
git clone https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards.git wordpress-coding-standards
./php-codesniffer/bin/phpcs --config-set installed_paths ../wordpress-coding-standards
phpenv rehash
./php-codesniffer/bin/phpcs -i
./php-codesniffer/bin/phpcs --config-show
```
Test command
```php
./php-codesniffer/bin/phpcs --report=full --standard=WordPress --ignore=*/vendor/*,*/wordpress-coding-standards/*,*/php-codesniffer/* ~/clone --extensions=php
```

## The errors I get

```
FOUND 1 ERROR AND 4 WARNINGS AFFECTING 2 LINES
--------------------------------------------------------------------------------
1 | WARNING | [ ] The "WordPress.XSS.EscapeOutput" sniff has been renamed to
|         |     "WordPress.Security.EscapeOutput". Please update your
|         |     custom ruleset.
1 | WARNING | [ ] The "WordPress.VIP.ValidatedSanitizedInput" sniff has been
|         |     renamed to "WordPress.Security.ValidatedSanitizedInput".
|         |     Please update your custom ruleset.
1 | WARNING | [ ] The "WordPress.VIP.DirectDatabaseQuery" sniff has been
|         |     renamed to "WordPress.DB.DirectDatabaseQuery". Please
|         |     update your custom ruleset.
1 | WARNING | [ ] The "WordPress.CSRF.NonceVerification" sniff has been
|         |     renamed to "WordPress.Security.NonceVerification". Please
|         |     update your custom ruleset.
86 | ERROR   | [x] Opening PHP tag must be on a line by itself
--------------------------------------------------------------------------------
PHPCBF CAN FIX THE 1 MARKED SNIFF VIOLATIONS AUTOMATICALLY
--------------------------------------------------------------------------------
```

**Comment by jrfnl** [comment]
Thanks for reporting this. The warnings on line 1 are a known issue and will be fixed before the next version is released.

The error on line 86 is probably legitimate, but I'd need to see a code sample to be able to say for sure.

As for the difference between your local install and the one on CodeShip: you are probably using different versions of WPCS.

Looking at your script above, you are using the default branch, which for WPCS is `develop`. You may want to change the setup to use `master`, which will always be the latest stable release of WPCS.

I can't tell from your issue description what version you use locally, but you can check it by opening up the `CHANGELOG.MD` file in the root of the WPCS directory.

**Comment by urre** [comment]
@jrfnl Thanks for your great answer! Totally missed that `develop` was the default branch. `git clone -b master ...` worked perfectly! Thanks again.
