### ISSUE TITLE
Add property to restrict scope of XSS.EscapeOutput

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#129]
From the discussion on #13, it sounds like the [XSS/EscapeOutputSniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/Sniffs/XSS/EscapeOutputSniff.php) should take a property to set the strictness of the checks. There could be a sniff property to restrict checks to `echo` and `print` statements immediately preceded by `<?php`.

**Comment by GaryJones** [comment]
Is this concern still valid?

**Comment by westonruter** [comment]
Not to me.

**Comment by JDGrimes** [comment]
I don't think this is really still a concern. I think  at the time of #13 the `extra` stuff was not yet separate from the basic coding standards. This was the main issue, and what was causing folks confusion. Closing as `wontfix`. We can reopen later if the need arises.
