### ISSUE TITLE
Standard for format of calls to printf()

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1292]
There doesn't appear to be a standard for the format used when calling `sprintf()`, `printf()`, etc.

Some places in core use liberal newlines:

	printf(
		/* translators: %s: handshake emoji */
		__( 'Lend a Hand with Gutenberg %s' ),
		'&#x1F91D'
	);

Others don't:

	printf( __( 'Welcome to WordPress&nbsp;%s' ), $display_version );

I think it would be good to have a WPCS standard for formatting the calls to the `printf()` family of functions, and I guess `wpdb::prepare()` too.

My preference is to use liberal newlines.

**Comment by JDGrimes** [comment]
I use either, based on line length, but usually the code is long enough that it needs to be split over several lines like in your first example.

**Comment by jrfnl** [comment]
Yes, as @JDGrimes says: this is a line-length based choice, not something which is specific to select functions.

The core coding standards do not include a line-length rule, but you're free to add the sniff for this to your own custom ruleset: `Generic.Files.LineLength`.
The maximum line length the sniff uses, is configurable: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericfileslinelength

**Comment by jrfnl** [comment]
@johnbillion Was the previously given feedback useful ? If so, can we close this issue ?
If not: could you expand on what you expect WPCS to do here ?

**Comment by GaryJones** [comment]
> My preference is to use liberal newlines.

This is my personal preference as well - for the simple reason that it's easier to see if placeholder values have been escaped or not.
