### ISSUE TITLE
ValidatedSanitizedInputSniff.php included twice, causing "name already in use" fatal.

### ISSUE THREAD

**Issue by lgedeon** [WordPress-Coding-Standards/WordPress-Coding-Standards#1296]
A few weeks ago my local started complaining that it "Cannot declare class WordPress\Sniffs\Security\ValidatedSanitizedInputSniff, because the name is already in use in /private/tmp/wpcs/WordPress/Sniffs/Security/ValidatedSanitizedInputSniff.php on line 185" on every run of wpcs.

It seems the file is being included/required twice. I am kinda stuck at the moment. Can you help be debug? Is there any info I can provide to help?

**Comment by jrfnl** [comment]
@lgedeon  Based on what you describe, you seem to be using the `develop` version of WPCS, not a stable release. If that's your intention, please update the branch and try again.
Let us know if the issue still exists in the latest version of the `develop` branch and add some additional information on how you are running WPCS and how you've installed PHPCS and WPCS.
If you can no longer reproduce the issue (which I suspect will be the case), please close the issue.

Alternatively, use a stable release - such as the latest version `0.14.0`.

**Comment by jrfnl** [comment]
@lgedeon Did my previous remark help ? Have you got things working now ? If so, please close the issue. If not, please comment with additional information so we can help you better.

**Comment by lgedeon** [comment]
We ended up switching back to stable and that fixed it. Thanks.

**Comment by jrfnl** [comment]
@lgedeon Thanks for getting back to me.
