### ISSUE TITLE
PHPCBF introduces new lines / PEAR.Functions.FunctionCallSignature fixer

### ISSUE THREAD

**Issue by iandunn** [WordPress-Coding-Standards/WordPress-Coding-Standards#1305]
It looks like PHPCBF has unintended side-effects when fixing `WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned` violations.

If I run `phpcs` against something like this:

```php
$sessions = new WP_Query( array(
	'post_type' => 'wcb_session',
	'orberby' => 'title',
	'order' => 'DESC',
	'posts_per_page' => -1,
) );
```
...then it correctly warns about the misalignment.

And then if I manually fix it, it stops warning:

```php
$sessions = new WP_Query( array(
	'post_type'      => 'wcb_session',
	'orberby'        => 'title',
	'order'          => 'DESC',
	'posts_per_page' => -1,
) );
```

But, if instead of manually correctly, I run `phpcbf`, then the code is converted to this:

```php
$sessions = new WP_Query(
	array(
		'post_type'      => 'wcb_session',
		'orberby'        => 'title',
		'order'          => 'DESC',
		'posts_per_page' => -1,
	)
);
```

PHPCBF moved the array constructor to it's own line, rather than leaving it on the same line as the `WP_Query` constructor.

[The standard](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#indentation) doesn't say it has to be on a new line, and has examples where it's not. So, I think it should be left as-is, and only the items should be aligned.

* PHPCS `3.2.2`
* WPCS `master` @ cf6b310caad735816caef7573295f8a534374706
* PHP `7.1.12`

**Comment by jrfnl** [comment]
This is completely unrelated to the `WordPress.Arrays.MultipleStatementAlignment` sniff, but has to do with the `PEAR.Functions.FunctionCallSignature` sniff.

For the discussion on why it was decided to let the fixer of that sniff run, please see #968.

If you want to just and only fix the double arrow alignment, you can run PHPCBF like so:
`phpcbf . --standard=WordPress --sniffs=WordPress.Arrays.MultipleStatementAlignment`

**Comment by iandunn** [comment]
Huh, I'm confused by the conclusion on that ticket at first glance, since code that is correctly formatted according to the standard will be mangled by the fixer. I would think the desired outcome would be for the array items to be aligned, but everything else left untouched.

I'll admit that I haven't dug too deep into the discussion or original issue, though, so it's very possible that I'm missing some things.

Since it sounds like this isn't actually a bug from WPCS's perspective, I'll go ahead and close this. Thanks for pointing out #968, though, that (and some of your comments on related upstream issues)  helped me find a solution for the codebase I'm working on:

```
<exclude phpcbf-only="true" name="WordPress.Arrays.MultipleStatementAlignment.DoubleArrowNotAligned" />
<exclude phpcbf-only="true" name="PEAR.Functions.FunctionCallSignature.ContentAfterOpenBracket" />
<exclude phpcbf-only="true" name="PEAR.Functions.FunctionCallSignature.CloseBracketLine" />
```

This way, `phpcs` will warn about the mis-aligned items, but `phpcbf` won't try to fix them. I can just fix them manually instead. Thanks!

**Comment by jrfnl** [comment]
> I can just fix them manually instead.

@iandunn You may want to give the command I showed above a try instead of doing it manually: `phpcbf . --standard=WordPress --sniffs=WordPress.Arrays.MultipleStatementAlignment` :wink:

**Comment by iandunn** [comment]
The reason I'd prefer a `phpcs.xml` solution is that it fits my workflow better. Having to remember to run multiple commands with verbose and exacting syntax each time I want to clean up a file is inconvenient. Fixing them as part of the normal `phpcs` process is simple, though; I just highlight the lines in PHPStorm and hit `Cmd + Alt + L`.

You're right that excluding all of `FunctionCallSignature` is enough, though:

`<exclude phpcbf-only="true" name="PEAR.Functions.FunctionCallSignature" />`

I'd added `DoubleArrowNotAligned` because it was necessary when excluding `ContentAfterOpenBracket` and `CloseBracketLine` individually, but the side-effects of excluding all of `FunctionCallSignature` are probably less bad than the side-effects of excluding `DoubleArrowNotAligned`; the issues around the latter are more frequent in this codebase. Thanks :)
