### ISSUE TITLE
whats the setting to adjust spaces?

### ISSUE THREAD

**Issue by XeonG** [WordPress-Coding-Standards/WordPress-Coding-Standards#1313]
For the most part I prefere the Wordpress coding standards and I'm using them with https://github.com/squizlabs/PHP_CodeSniffer in vscode for general php formatting...

however one thing is pissing me off with it.. and that is the amount of extra spaces it is shoving everywhere.. like

return view( 'companies.index', [ 'companies' => $companies ] );

when I'm wanting this....

return view('companies.index', ['companies' => $companies]);

I just don't care for 'all' the extra spaces... where do I change it? the only spaces that should be in that return line are 3spaces and even then the spaces around => could be removed.. leaving just the 1 space after the ,

**Comment by GaryJones** [comment]
The amount of whitespace is somewhat fundamental to coding standards in WordPress.

But, have a read of https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#arbitrary-parentheses-amount-of-whitespace-required and similar whitespace custom properties.

**Comment by JDGrimes** [comment]
Run `phpcs -s` over the file, which will cause the sniff codes to be shown in the report. Then you can create your own custom ruleset, with those rules excluded. See the example ruleset: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/phpcs.xml.dist.sample#L37-L38

**Comment by jrfnl** [comment]
What @GaryJones and @JDGrimes said.

Also - if you go the custom ruleset way and want limited spaces, have a look at the [WPCS customizable properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) and the [PHPCS customizable properties](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties) - for a number of sniffs (by far not all), you can adjust the spacing which the sniff demands.
