### ISSUE TITLE
Unable to set WP standards along side Drupal standards

### ISSUE THREAD

**Issue by paulcanning** [WordPress-Coding-Standards/WordPress-Coding-Standards#1320]
I am struggling to install both WP standards and Drupals (extracted from the Coder module)

They live in two different folders, so I am doing the following:

`phpcs --config-set installed_paths ~/A_Folder/wpcs,~/Another_Folder/coder/coder_sniffer`

When I do `phpcs -i` I get:

> PHP Fatal error:  Uncaught UnexpectedValueException: DirectoryIterator::__construct(~/Another_Folder/coder/coder_sniffer): failed to open dir: No such file or directory in /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer.php:2250
> Stack trace:
> #0 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer.php(2250): DirectoryIterator->__construct('~/Another_Folder/code...')
> #1 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(1404): PHP_CodeSniffer::getInstalledStandards()
> #2 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(495): PHP_CodeSniffer_CLI->printInstalledStandards()
> #3 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(468): PHP_CodeSniffer_CLI->processShortArgument('i', 0)
> #4 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(403): PHP_CodeSniffer_CLI->setCommandLineValues(Array)
> #5 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(911): PHP_CodeSniffer_CLI->getCommandLineValues()
> #6 /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer/CLI.php(113 in /usr/local/Cellar/php71/7.1.8_20/lib/php/PHP/CodeSniffer.php on line 2250

I can set either individually, but not both!

I also can't seem ot set one, and then use `phpcs --standard=path/to/standard path/to/file` - it simply states the standard isn't installed.

**Comment by jrfnl** [comment]
That's a new one.

Ok, first off, before I can even begin to answer this, I need more information:
* Am I correct in that you are using PHP 7.1.8 ?
* What version of PHPCS are you using ?
* What version of WPCS are you using ?
* Where can I find a copy of the Drupal coding standard you are using to run some tests myself ?

**Comment by jrfnl** [comment]
Ok, so I've found the [git repo for Coder](http://git.drupal.org/project/coder.git), cloned it and added it to my `installed_paths` and `phpcs -i` works fine, both when using PHPCS 2.x as well as 3.x (both latest versions).
To run the Drupal standards, I switched PHPCS to 2.x as the Drupal standards are not compatible with PHPCS 3.x yet, ran both the Drupal standards against a random file and both work fine without any exceptions or fatal errors.

So...  please provide detailed steps on how to reproduce the error you are getting, as otherwise, there nothing I can do to help.

**Comment by paulcanning** [comment]
PHP 7.1.8, PHPCS 2.9.1, WPCS 0.13.1

**Comment by jrfnl** [comment]
Tried with that same combination, again working fine.

Without detailed steps to reproduce, there's nothing I can do.

**Comment by paulcanning** [comment]
Can you show how you added the two standards?

**Comment by jrfnl** [comment]
I cheated - I just edited the `CodeSniffer.conf` file in the root of my PHPCS install. I got quite a large number of standards installed, so manually typing all the paths in on the command line gets tiresome ;-)

**Comment by jrfnl** [comment]
@paulcanning Just checking - did you get it working ? And if so, how ? (for other people who come across the issue)

**Comment by paulcanning** [comment]
@jrfnl I have not looked at it since sorry, other things have taken priority. I might try going your route and editing the conf file. Could you provide an example of yours?

**Comment by jrfnl** [comment]
@paulcanning No worries, just checking.

This is what my `CodeSniffer.conf` file looks like (paths adjusted to protect the innocent - oh and based on Windows as you can see):
```php
<?php
$phpCodeSnifferConfig = array (
  'installed_paths' => 'X:/path/to/PHPCS/WordPress,X:/path/to/PHPCS/PHPCompatibility,X:/path/to/PHPCS/QA-WP-Projects,X:/path/to/PHPCS/DrupalCoder/coder_sniffer',
  'report_width' => '90',
)
?>
```

**Comment by jrfnl** [comment]
@paulcanning Did you get this working ? Can the issue be closed ?
