### ISSUE TITLE
Upstream Squiz.WhiteSpace.LanguageConstructSpacing sniff removed in PHPCS 3.3.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1328]
The upstream `Squiz.WhiteSpace.LanguageConstructSpacing` sniff is included in the `Extra` ruleset, but will be removed in PHPCS `3.3.0` (not yet released).
A new sniff `Generic.WhiteSpace.LanguageConstructSpacing` replaces it.

As WPCS still supports both PHPCS 2.x as well as 3.x, we cannot change this in the ruleset and just up the minimum required PHPCS version.

I think that - for now - we'll need to do some trickery until PHPCS 2.x support is dropped and we can up the minimum supported PHPCS version to `3.3.0`.

Trickery I'm thinking of, is:
* See if we can just work around the removal by adding a class alias for the old sniff name to the new sniff name.
* If that doesn't work, add a minimal new sniff in WPCS (temporarily) which just does a:
    ```php
    if ( class_exists('new_upstream_class') ) {
        class WPversionofthesniff extends new_upstream_class {}
    } else {
        class WPversionofthesniff extends old_upstream_class {}
    }
    ```

Other bright ideas welcome.

Oh ... and we should also probably set a Composer constraint to PHPCS <= 3.2.3 for WPCS 0.14.x and possibly even 0.13.x.

Ref: https://github.com/squizlabs/PHP_CodeSniffer/pull/1337

**Comment by GaryJones** [comment]
> we should also probably set a Composer constraint to PHPCS <= 3.2.3 for WPCS 0.14.x and possibly even 0.13.x.

How about also a 0.15.0 release that addresses the upstream sniff changes, and makes PHPCS 3.3.0 the minimum? This would be for those who _do_ have the flexibility to bump their minimum versions, so they aren't held back by those who can't.

**Comment by jrfnl** [comment]
@GaryJones After I posted this last night, I also posted in the PHPCS topic with a plea to please restore & deprecated the old sniff and to not remove it until v 4.0.

Greg has decided to do so, so the problem is now much less problematic :smile: 

It would be great if we could switch over to the new sniff, but that will have to wait until we drop PHPCS 2.x I will add a comment to that effect in the thread there so we don't forget.
