### ISSUE TITLE
Support arrays as constants

### ISSUE THREAD

**Issue by holisticnetworking** [WordPress-Coding-Standards/WordPress-Coding-Standards#1335]
PHPCS version: 2.9.1
PHP version: 7.1.12
WPCS version: latest

In the past, PHP has not supported constants that were arrays. That lack of support is no longer relevant, so I'm hoping the WPCS team can make a ruling on the field: is WPCS going to support this feature, or not?

Personally, I'm not crazy about constants as arrays. But my company uses constants to death, so this is a bit of a constant debate.

**Comment by jrfnl** [comment]
@holisticnetworking There is no reason why WPCS shouldn't support it as it is a PHP feature (since PHP 5.6/7.0).

Are there any particular sniffs in which you are missing support for this ?
Any specific issues with the existing sniffs which you are running into ?

Some example code and some info on what you would expect to happen when running WPCS over that code and what currently happens, would help to clarify the issue.

**Comment by holisticnetworking** [comment]
Fair enough!

So I'm checking into a Git repository through SourceTree. The repository is setup to automatically check the code standards on checkin. This is the message I get:
```Parse error: parse error in docroot/wp-content/plugins/company-plugin/common/common.php on line 96
Errors parsing docroot/wp-content/plugins/company-plugin/common/common.php```

Line 96 reads:
```} elseif ( YOUTUBE_API_STATUS['UPLOAD_VIDEO_SUCCESS'] === $video_status )```

If I alter that line to assign the array YOUTUBE_API_STATUS to a local variable $youtube_status, there is no error message.

**Comment by jrfnl** [comment]
@holisticnetworking Ok, that clears things up.

Based on the info provided, this is what I think is happening:
You are either using the `WordPress` or the `WordPress-Extra` ruleset. These rulesets contain the `Generic.PHP.Syntax` sniff which is just a simple sniff linting the PHP in each file.

As long as you are running the sniffs on a system which is using a PHP version which is equal to or higher than your minimum supported PHP version, that should be fine and you will not see any notices (unless there are parse errors of course).
In your case, based on the info provided, running the sniffs on PHP 5.6 or 7.0 or higher, should therefore be fine.

As you are seeing the parse error, I suspect that the SourceTree checks are being run on an older PHP version.

So there are two things you can do:
1. Check with SourceTree if there is anything you can do in the configuration to make sure that the PHP version your checks are being run on is in line with the minimum supported PHP version for your code.
2. Exclude the `Generic.PHP.Syntax` sniff from your custom ruleset or via the command-line.

**Comment by jrfnl** [comment]
Side-note: the error message coming from the sniff should actually look slightly different, so I wouldn't be surprised if SourceTree has a native PHP linting check on check-ins as well.
Solution 1 should solve both issues in that case.

**Comment by holisticnetworking** [comment]
I knew I should have tried checking in w/o SourceTree! 

Thanks so much!
