### ISSUE TITLE
get_comment_date() and get_comment_time() incorrectly marked as auto-escaped

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1339]
The `get_comment_time()` and `get_comment_date()` functions are marked as auto-escaped, but this is incorrect. The output from both comes from `mysql2date()` which is localised and not escaped.

**Comment by jrfnl** [comment]
As a side-note: both functions return a value which is run through `apply_filter()` which could undo any escaping present, so I concur these functions should be removed from the list.

**Comment by johnbillion** [comment]
> both functions return a value which is run through `apply_filter()` which could undo any escaping present

That's a whole other can of worms which I'm currently gathering my thoughts on. This line of thinking means that even the `esc_*()` functions themselves aren't safe because their output passes through a filter.

**Comment by jrfnl** [comment]
> This line of thinking means that even the esc_*() functions themselves aren't safe because their output passes through a filter.

Which in it's essence is true and is definitely something to which would be useful to discuss in a wider context IMHO. The way things stand now, there is no 100% safe output escaping possible based on the current WP `esc_*()` functions.

**Comment by JDGrimes** [comment]
The argument for the escaping functions is that when you are hooking into a filter within an escaping function it is explicit that the value you return needs to be properly escaped. With non-escaping functions, that is usually not apparent. I think I recall reading this in the VIP guidelines at some point.
