### ISSUE TITLE
Add readonly() to the auto-escaped function list

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1341]
The `readonly()` function was introduced in WordPress 4.9 and -- like its `checked()`, `selected()`, and `disabled()` siblings are -- it should be treated as auto-escaped.

**Comment by jrfnl** [comment]
Side-note: each of these functions has a `$echo` parameter which defaults to `true`.
I haven't looked at the code at this moment, but I imagine that how these functions are treated may need some additional logic to check for the value of the `$echo` parameter.
