### ISSUE TITLE
WPCS Naming

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#1342]
I've never really appreciated it until recently, but I think there's a difference between "_Code Standards_" and "_Coding Standards_", which is perhaps best elaborated on by examples:

# Code Standards

To me, code standards are about the code we write:

- whether it uses tabs or spaces,
- where braces are placed,
- what whitespace is used between characters,
- whether certain functions are avoided,
- that things are escaped,
- that correct text domains are used,
- if DocBlocks are formatted correctly,
- if CSS values of `0` contain units or not,
- if JS event names are namespaced or not,
- etc. 

All of these could be (and most are) tested with PHPCS, Eslint, Stylelint and similar tools. It's something where we could look at a code snippet out of context, and point out where violations would occur.

# Coding Standards

However, I think there are other items, related to _how_ we approach writing code, and to me, that comes down to a bunch of questions, like:

- Should CSS be written mobile-first?
- Should the structure of code assume offline-first?
- Is JavaScript a hard-dependency, or only used for progressive enhancement?
- Are decisions about data made on a Privacy by Design basis?
- Should the project support multilingual and RTL by default, even if the only expected locale is US English?
- Should a plugin support network activation?
- Should we aim for the majority of the logic to be in it's own package, wrapped in a light WP plugin?
- Should a theme aim to never be activated directly, but only through a child theme?
- Should we only support PHP 7.1 and above?
- Should feature X go into the free or paid version?

These focus perhaps more on questions an software engineer might consider, and some of those answers may be business decisions. Getting these documented and applied consistently in an organisation creating software, and in the wider community where relevant, has value.

# WPCS Naming

My question then is whether the name "WordPress **Coding** Standards", at least for this PHP repo and WP Handbook page titles, rather than the GitHub Organisation or hopefully future Make Team, is correct, or whether "WordPress **Code** Standards" (or indeed, since we have JS and CSS now, perhaps `WordPress-Coding-Standards/WordPress-PHP-Code-Standards`, or similar) is more accurate?

Do others agree with the above viewpoint? Is it important to make this distinction? Is this a difference that is too minor to care about? Should we bother to make changes that only has a idealistic philosphical value, or accept it as technical debt?

**Comment by jrfnl** [comment]
I do agree with these two interpretations. I don't agree that the naming conventions currently used have anything to do with it and making a distinction between "code standards" and "coding standards" is IMHO only going to lead to more confusion that it's worth.

I'd categorize everything under your first heading as coding standards. They are reasonably clear cut, can be objectively measured, tested and (auto-)fixed.

As for the second category, I'd categorize nearly everything in there as **_software-architecture_**. Insights on which evolve over time and can even do a 180 degree turn (think protocol-less URLs).
These are a lot more opinionated, though over time, opinions can converge in such a way that one or the other becomes a standard as such.

I do think it would be useful to have a handbook section addressing these software architecture questions, if only to make people aware of them.
I also think it's outside the purview of WPCS as such.

**Comment by jrfnl** [comment]
@GaryJones Just checking: should this issue stay open ?

**Comment by GaryJones** [comment]
Doesn't seem my viewpoint is sufficiently supported enough to bother making a change.
