### ISSUE TITLE
`cancel_comment_reply_link()` is not safe for output

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1346]
`cancel_comment_reply_link()` doesn't return a value, and is not safe for output regardless. It should be removed from the list of auto escaped functions.

**Comment by jrfnl** [comment]
As a side-note: the function just echos out the output of `get_cancel_comment_reply_link()`, the output of which is run through `apply_filter()` before being returned. Also see #1339
