### ISSUE TITLE
Remove `get_bookmark()` from the list of auto escaped functions

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#1352]
This function returns an object and is not suitable for output.

**Comment by jrfnl** [comment]
Actually, the function returns an `object` by default, but can return an associative or numeric `array` as well, depending on the parameter input.
Ref: https://developer.wordpress.org/reference/functions/get_bookmark/

It does look like all the parts returned will be sanitized properly to a reasonably degree of safety.

**Comment by johnbillion** [comment]
Correct, but none of the available return types are scalar.
