### ISSUE TITLE
Detected access of super global var $_POST, probably needs manual inspection

### ISSUE THREAD

**Issue by emfluenceindia** [WordPress-Coding-Standards/WordPress-Coding-Standards#1358]
I am getting PHPCS error

> Detected access of super global var $_POST, probably needs manual inspection

with the following code:
`if( isset( $_POST['user_role'] ) && '' !== $_POST['user_role'] ) { ... }`

Screenshot: https://tinyurl.com/ycvt3e73
Editor: PHP Storm
Coding standard used: WordPress

**Comment by tatthien** [comment]
I'm getting the same.

**Comment by GaryJones** [comment]
Please see https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data

**Comment by jrfnl** [comment]
I'm going to close this issue as this sniff was deprecated in WPCS 1.0.0 and has been removed in WPCS 2.0.0.
