### ISSUE TITLE
How to echo a variable that contains html

### ISSUE THREAD

**Issue by hegerpkd** [WordPress-Coding-Standards/WordPress-Coding-Standards#1367]
`echo $output;`

gives me an error 

> All output should be run through an escaping function (see the Security sections in the Wordpress Developer Handbooks), found '$output'.

however, I do not know of any escaping function that allows html inside (with form elements), I've tried wp_kses_data, but it doesn't work either.

Is there such an escaping function?

**Comment by dingo-d** [comment]
Not really a place for this question, but have you tried `wp_kses` or `wp_kses_post`?

**Comment by hegerpkd** [comment]
Ah, ok. Sorry. I don't know how I overlooked this. Thanks.
