### ISSUE TITLE
Short array tokens not handled in EscapeOutputSniff

### ISSUE THREAD

**Issue by sybrew** [WordPress-Coding-Standards/WordPress-Coding-Standards#1370]
Example code:
```php
$hello = 'hello';
$world = 'world';
vprintf(
	'<em>%s</em><strong>%s</strong>',
	[
		esc_html( $hello ),
		esc_html( $world ),
	]
);
```

Notification example:
```
All output should be run through an escaping function (see the 
Security sections in the WordPress Developer Handbooks), found '['.

(WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

Locally, I added this (temporarily) check to circumvent the notification in the for-loop at `WordPress\Sniffs\XSS\EscapeOutputSniff::process_token()` -- right beneath the `T_ARRAY` check; copying its behavior, which works as intended:
```php
if ( in_array( $this->tokens[ $i ]['code'], [ T_OPEN_SHORT_ARRAY, T_CLOSE_SHORT_ARRAY ], true ) ) {
	$i++; // Skip the opening parenthesis.
	continue;
}
```

PHPCS registers the two shorthand constants in `..\util\Tokens.php`

**Comment by jrfnl** [comment]
@sybrew Thanks for reporting this. This has already been fixed in the `develop` branch via #1333. The fix will be included in the WPCS 1.0.0 release.

Closing as duplicate.
