### ISSUE TITLE
check of posts_per_page isn't working properly when passing the value from array variable.

### ISSUE THREAD

**Issue by emgk** [WordPress-Coding-Standards/WordPress-Coding-Standards#1379]
As per WordPress-VIP standards, we must not set "-1" to posts_per_page, it show give me an proper error when passing -1 in any way. I expect to see error message like **"Disabling pagination is prohibited in VIP context, do not set `posts_per_page` to `-1` ever."** when I run `phpcs --standard=WordPress-VIP` 

But I'm not getting any error message when passing -1 passing/assigning value to posts_per_page using below syntax:

```
$args = array( 'posts_per_page' => -1 );
get_posts( $args);

```

```
function custom_get_posts(){
	$args = array( 'posts_per_page' => -1 );
	get_posts( $args);
}

```

```
$args = array( 'posts_per_page' => -1 );

function custom_get_posts(){
	get_posts( $args);
}

```
Working syntax is (means, giving me an error in terminal):
```
get_posts( 'posts_per_page=-1');
```
```
$args4 = array();
$args4['posts_per_page'] = -1;

get_posts( $args4 ); // Bad.
```
Please correct me if I missed anything.

**Comment by LC43** [comment]
i don't get a warning on using that last case
```
$args4 = array();
$args4['posts_per_page'] = -1;

get_posts( $args4 ); // Bad.
```

neither when using variables or constants

```
$max_500 = 500;
$args = array(
	'posts_per_page' => $max_500,
);
$post_list = get_posts( $args );
```

**Comment by jrfnl** [comment]
@LC43 PHPCS can not evaluate what the runtime value of a variable or constant would be. While your code samples are simple enough, the constant may be declared in another file, the variable may be a class property overloaded by a child class etc.

**Comment by LC43** [comment]
got it! thanks!
