### ISSUE TITLE
Class with property 'print' gets incorrectly flagged with WordPress.XSS.EscapeOutput.OutputNotEscaped

### ISSUE THREAD

**Issue by NielsdeBlaauw** [WordPress-Coding-Standards/WordPress-Coding-Standards#1385]
**It seems like the sniff incorrectly interprets `print` as a PHP keyword, instead of a class property.**

Create the following file (classes instantiated in single file for conciseness)

```php
<?php

class Printer {
	public function transform( $test ) {
		return strtolower( $test );
	}
}

class Something {
	public $print = null;
	public function __construct() {
		$this->print = new \Printer();
	}

}

$something = new \Something();
$something->print->transform( $test );

```

PHPCS incorrectly triggers the following warnings:

```
 12 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '='.
    |       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
 18 | ERROR | All output should be run through an escaping function (see the Security sections in the WordPress Developer Handbooks), found '->'.
    |       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
```

<details><summary>Versions - click to expand</summary>

```

$ vendor/bin/phpcs --version
PHP_CodeSniffer version 3.3.0 (stable) by Squiz (http://www.squiz.net)
```

```
"name": "wp-coding-standards/wpcs",
"version": "0.14.1",
```

```
$ php -v
PHP 7.0.30-1+ubuntu14.04.1+deb.sury.org+1 (cli) (built: May  2 2018 13:00:43) ( NTS )
Copyright (c) 1997-2017 The PHP Group
Zend Engine v3.0.0, Copyright (c) 1998-2017 Zend Technologies
    with Zend OPcache v7.0.30-1+ubuntu14.04.1+deb.sury.org+1, Copyright (c) 1999-2017, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
```
</details>

**Comment by jrfnl** [comment]
While it isn't a good idea to use a reserved PHP keyword as a property name, it is allowed, so yes, this is a bug.

PR #1386 should fix this.

**Comment by NielsdeBlaauw** [comment]
I agree using a keyword as a property or method name is not very elegant. Maybe an additional sniff triggering a warning is useful? Something like `Warning: You are using reserved keyword %s as a name. This might be confusing and is therefor discouraged.`?

**Comment by jrfnl** [comment]
> Maybe an additional sniff triggering a warning is useful?

@NielsdeBlaauw I think that's more something for the [PHPCompatibility](https://github.com/wimg/PHPCompatibility/) standard,

I just checked and while it does check for "ForbiddenNames", some of the reserved keywords are missing in the list it check against, including `print`. If I remember correctly, they were removed because of some false positives.
I'll have a look at this again at some point when I continue fixing https://github.com/wimg/PHPCompatibility/issues/79
