### ISSUE TITLE
Packagist indicates the wrong branch as "unstable"

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1393]
The `dev-master` branch is seen on Packagist as the `unstable` branch. This should be the `dev-develop` branch instead.

Who has admin access to the listing on Packagist to change this ? @westonruter ?

**Comment by Rarst** [comment]
Could you please clarify what do you mean by "unstable" ?

**Comment by jrfnl** [comment]
I interpret it as the branch which contains the changes which are not in a stable release yet, i.e. the `develop` branch in this repo.

**Comment by Rarst** [comment]
I am not following. What do you expect Packagist and Composer to show/do? What happens differently from what you expect?

I see both `dev-master` and `dev-develop` on Packagist, and all other branches as well.

**Comment by jrfnl** [comment]
When queried, Packagist indicates that `dev-master` is the `unstable` branch - see: https://poser.pugx.org/show/wp-coding-standards/wpcs#badges

**Comment by Rarst** [comment]
I am not sure what exactly badge service is querying there. I don't know if there is any special handling for `master` on Packagist, but from Composer point of view all branches are equal in their development status.

I've looked at Packagist settings for the repo and there simply aren't about branches.

**Comment by GaryJones** [comment]
In terms of Composer, anything that starts with `dev-` is considered unstable, and will [clone the repo](https://getcomposer.org/doc/articles/versions.md#branches) instead of just copying the files as it does with tags.

It's only in GitHub where we've set `develop` as the [base/default branch](https://help.github.com/articles/setting-the-default-branch/) to which all PRs are made by default.

It's only by convention of [Git Flow](https://nvie.com/posts/a-successful-git-branching-model/) of what `develop` and `master` stands for, and the [default branch naming in Git is `master`](https://git-scm.com/book/en/v1/Git-Branching-What-a-Branch-Is).

Beyond that Packagist has no semantics of `dev-master` over `dev-develop`.

**Comment by Seldaek** [comment]
Packagist will read the configured default branch from github. The badges though are created by poser.pugx.org and I have no idea what they use to decide which is the unstable branch.

**Comment by Rarst** [comment]
@Seldaek how does Packagist treat/display default branch exactly? At the moment https://packagist.org/packages/wp-coding-standards/wpcs shows `dev-master` on top of the branches list, seemingly implying its priority (you don't even see `dev-develop` without expanding the list).

**Comment by Seldaek** [comment]
Yeah for that we don't look at the default branch, the default branch only has an effect during the package update process where readme and description and whatnot for the package are taken from the default branch.

**Comment by Rarst** [comment]
I would _guess_ that's why badge service grabs master, but hard to be sure without knowing their code.

@jrfnl can I suggest we just put together custom badge pointing to desired branch explicitly, rather than relying on "magic" figuring it out here? :)

**Comment by jrfnl** [comment]
Thanks everyone for your input!

I'll look into creating a custom badge for now.

I've also opened an issue about this in the poer.pugx.org repo: https://github.com/PUGX/badge-poser/issues/227

**Comment by Rarst** [comment]
Quick take on a custom badge:
```
[![Latest Unstable Version](https://img.shields.io/badge/unstable-dev--develop-orange.svg)](//packagist.org/packages/wp-coding-standards/wpcs)
```
[![Latest Unstable Version](https://img.shields.io/badge/unstable-dev--develop-orange.svg)](//packagist.org/packages/wp-coding-standards/wpcs)

**Comment by jrfnl** [comment]
@Rarst Great minds and such.... 

I'm playing around and testing some variations right now: https://github.com/jrfnl/WordPress-Coding-Standards/blob/feature/readme-add-more-badges/README.md
