### ISSUE TITLE
GlobalVariableOverride doesn't actually detect override in the global namespace

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1395]
While looking at the `WordPress.WP.GlobalVariableOverride` sniff and fixing some other things, I suddenly realized the sniff does not actually check for overrides in the global namespace, except for when a `global` statement has been encountered.

Looking at the history, it looks like it never did and I cannot determine whether this was a conscious choice or an oversight.

It would be easy enough to add this. As variables are not affected by namespacing, all that is needed really is a check that the `$variable` is not scoped.
(Ok, some more changes are needed, but that's for the PR)

The only problem I can see is false positives for variables which are in a file (view) which is included from within a function in another file, making the variables local to that function.
This will mainly be a problem in themes.

There are two ways to deal with those false positives:
1. [File based] Add a `// phpcs:disable WordPress.WP.GlobalVariableOverride -- file included from within function abc()` in the file header.
2. [Project ruleset based] Add a public property to the sniff which would enable/disable the check for variable overrides in the global namespace, so people can enable/disable this check project-wide from within their custom ruleset.

So, the question is:
* Should the check for overrides of WP global variables in the global namespace be added ?
* And if so, with or without the public property ? and if with, what should be the default ?
    I'd advocate for enabled, but that's just me (better safe than sorry principle).

Opinions ?

Related #26, #213

**Comment by JDGrimes** [comment]
I am pretty sure that this worked at some point. In my opinion it should definitely check for variables in the global namespace. I'd lean against the project ruleset option, but I don't have a strong opinion.

**Comment by jrfnl** [comment]
> I am pretty sure that this worked at some point.

Based on the code history, it never has.

**Comment by JDGrimes** [comment]
> Based on the code history, it never has.

OK, maybe I was thinking of the prefix sniff.
