### ISSUE TITLE
Add custom error name to addError function

### ISSUE THREAD

**Issue by jonathanbardo** [WordPress-Coding-Standards/WordPress-Coding-Standards#140]
It would be great if addError function in WPCS ([example here](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/b46eedae7fb41aebee2632520e84f0ced47debd1/Sniffs/Arrays/ArrayDeclarationSniff.php#L425)) function would implement the 3rd argument of phpcs [Ref Squiz Lab](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/File.php#L734).

This could add more granularity in custom ruleset based on top of this standard like so : http://www.squizlabs.com/view?a=6160.

Right now we can only exclude a sniff but not an error message inside a sniff.

**Comment by westonruter** [comment]
PR merged into `develop`.
