### ISSUE TITLE
Migrate Remaining VIP Sniffs and Deprecate

### ISSUE THREAD

**Issue by tomjn** [WordPress-Coding-Standards/WordPress-Coding-Standards#1409]
Currently these sniffs in `WordPress/Sniffs/VIP` need to be migrated to other rulesets and deprecated:

 - `SuperGlobalInputUsageSniff`
 - `SessionVariableUsageSniff`
 - `SessionFunctionsUsageSniff`
 - `RestrictedVariablesSniff`
 - `RestrictedFunctionsSniff`
 - `OrderByRandSniff`
 - `FileSystemWritesDisallowSniff`
 - `AdminBarRemovalSniff`

The `RestrictedFunctionsSniff` seems an odd one out in that it's very VIP context specific, and references a lot of VIP functions unique to WordPress.com. It might be a candidate for deprecation without migration, or at the least behaviour modification

**Comment by jrfnl** [comment]
@tomjn Note: most of these should *not* be migrated to other rulesets as they are too VIP specific. Most sniffs which should be migrated, have already been handled in #1157 / #1242.

**Comment by tomjn** [comment]
Ah then I shall work on just the deprecation part :)

**Comment by tomjn** [comment]
order by rand might want to be included in the future as the problem isn't VIP specific, but it will need a non-VIP specific solution in the suggestion

**Comment by jrfnl** [comment]
Related #1309

**Comment by jrfnl** [comment]
Closing now #1310 has been merged.
