### ISSUE TITLE
Remove VIP ruleset and sniffs

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#1424]
#1309 deprecated the `WordPress-VIP` ruleset and sniffs, and remove it from the `WordPress` ruleset, but left the code as part of WPCS to not completely break those who reference the VIP ruleset or sniffs.

As of WPCS `2.0.0`, this ruleset and remaining VIP sniffs should be removed.

**Comment by jrfnl** [comment]
Closing as this has been done in PR #1551
