### ISSUE TITLE
VIP Warnings when supposedly excluded

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#1425]
Now, when using `WordPress` ruleset with the `develop` branch, I get the following:

```
  1 | WARNING | The "WordPress.VIP.PluginMenuSlug" sniff has been renamed to "WordPress.Security.PluginMenuSlug". Please update your custom ruleset. (WordPress.VIP.PluginMenuSlug.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.SessionFunctionsUsage" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.SessionFunctionsUsage.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.FileSystemWritesDisallow" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.FileSystemWritesDisallow.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.TimezoneChange" sniff has been renamed to "WordPress.WP.TimezoneChange". Please update your custom ruleset. (WordPress.VIP.TimezoneChange.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.AdminBarRemoval" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.AdminBarRemoval.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.RestrictedFunctions" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.RestrictedFunctions.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.RestrictedVariables" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.RestrictedVariables.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.DirectDatabaseQuery" sniff has been renamed to "WordPress.DB.DirectDatabaseQuery". Please update your custom ruleset. (WordPress.VIP.DirectDatabaseQuery.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.ValidatedSanitizedInput" sniff has been renamed to "WordPress.Security.ValidatedSanitizedInput". Please update your custom ruleset. (WordPress.VIP.ValidatedSanitizedInput.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.SessionVariableUsage" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.SessionVariableUsage.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.SuperGlobalInputUsage" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.SuperGlobalInputUsage.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.SlowDBQuery" sniff has been renamed to "WordPress.DB.SlowDBQuery". Please update your custom ruleset. (WordPress.VIP.SlowDBQuery.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.OrderByRand" sniff has been deprecated. Please update your custom ruleset. (WordPress.VIP.OrderByRand.DeprecatedSniff)
  1 | WARNING | The "WordPress.VIP.CronInterval" sniff has been renamed to "WordPress.WP.CronInterval". Please update your custom ruleset. (WordPress.VIP.CronInterval.DeprecatedSniff)
```

on the first reported file. If I switch to use `WordPress-Core`, then I don't get those warnings.

Using `-vv`, the only time the VIP/ sniffs are mentioned are during the initial processing of the ruleset:

```
Processing rule "WordPress"
        => /path/to/vendor/wp-coding-standards/wpcs/WordPress/ruleset.xml
        * rule is referencing a standard using ruleset path; processing *
        Processing ruleset /path/to/vendor/wp-coding-standards/wpcs/WordPress/ruleset.xml
            Adding sniff files from /path/to/vendor/wp-coding-standards/wpcs/WordPress/Sniffs directory
                => /path/to/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/PluginMenuSlugSniff.php
                => /path/to/vendor/wp-coding-standards/wpcs/WordPress/Sniffs/VIP/DirectDatabaseQuerySniff.php
```

`WordPress-VIP` is one of the registered standards for `phpcs -i`, by virtue of the DealerDirect plugin seeing and registering it.

The `<exclude name="WordPress.VIP"/>` doesn't seem to be fully excluding the sniffs, at least not to the point of calling the `process_token()` method.

cc @tomjn

**Comment by GaryJones** [comment]
We're still going to need a solution, pre- or post- release.

Could the VIP sniffs be moved outside of the main `WordPress/` directory, and have some way of aliasing the individual sniffs back to what they currently resolve to?

**Comment by jrfnl** [comment]
> Could the VIP sniffs be moved outside of the main WordPress/ directory, and have some way of aliasing the individual sniffs back to what they currently resolve to?

Based on my earlier assessment, I suspect the simplest solution would be to copy/move the relevant sniffs & their tests to a `Sniffs` and `Tests` directory in the `WordPress-VIP` directory and let the original sniffs have only the deprecation warnings which would be excluded from the `WordPress` ruleset, i.e. should only show if someone has a names sniff in their own ruleset - very similar to what was previously done when I moved the other sniffs. I need to think a little more about this though to be sure.

**Comment by tomjn** [comment]
Could we exclude each VIP sniff individually?

**Comment by jrfnl** [comment]
@tomjn What would that achive ?

We could at the sniff level, but that would make the deprecation messages unreachable too and would overrule explicit includes from a custom ruleset.

If you would do it at the error code level, which code would you exclude ?
- If just the `DeprecatedSniffFound`, then the sniff is not really removed from the ruleset for people not explicitly including it and would still throw the "normal" sniff errors.
- If you would exclude the error codes of the "normal" sniff errors too, you would overrule an explicit include from a custom ruleset.

**Comment by jrfnl** [comment]
I think I may have found a simple solution. PR upcoming.

**Comment by tomjn** [comment]
hmmm silencing the VIP sniffs in the main WordPress ruleset via:

```xml
	<!-- Prevent deprecation notice when the sniff is not explicitely included. -->
	<rule ref="WordPress.VIP">
		<severity>0</severity>
	</rule>
```

Then resetting the severity in the VIP ruleset could work, it'll make the VIP ruleset XML more verbose though

**Comment by jrfnl** [comment]
@tomjn I was thinking along the same lines ;-)

**Comment by jrfnl** [comment]
Note: While the solution from @tomjn would work to silence the VIP sniffs when included from the `WordPress` ruleset, it will **also** silence the deprecation warnings when people use the `WordPress` ruleset + explicitly set custom properties for any of the VIP sniffs from their custom ruleset.

So there will still be people who will not see the deprecation warnings while they should.

**Comment by GaryJones** [comment]
I've been trying different combinations of severity levels (`3`, `6`, etc.) in the `ruleset.xml` files, and also in the `DeprecatedSniffs` `addError()` calls themselves. No luck in finding a solution that works for the `phpcs.xml.dist` scenarios I tried.

**Comment by GaryJones** [comment]
We could rename `/VIP/` to `/.VIP/`, as PHPCS doesn't load "hidden" directories inside `/Sniffs/`, but then that would break `WordPress.VIP...` references, and there doesn't seem to be a way to tell PHPCS that it will find classes for `WordPress.VIP...` in `/.VIP/`.

**Comment by jrfnl** [comment]
WPCS 1.0.0 needs to get released.

So just checking in: is anyone currently actively working on a PR to solve this ? If so, will that PR be ready within the next 48 hours ?

If not: I suggest changing the current implementation to a "soft" deprecation, i.e. throw deprecation notices when properties are being changed for the deprecated sniffs, but not when the sniff is being used.

That way we can release 1.0.0.

If someone would then want to fix this later anyway, the "hard" deprecation can be included in a 1.x release.

**Comment by GaryJones** [comment]
> is anyone currently actively working on a PR to solve this ?

No PR from me. I tried a few different approaches, but nothing worked.

I wondered if @gsherwood had any suggestions.
