### ISSUE TITLE
Add a sniff to detect git merge conflict resolution text

### ISSUE THREAD

**Issue by tomjn** [WordPress-Coding-Standards/WordPress-Coding-Standards#1432]
There's a pending PR by @david-binda for the VIP standards at https://github.com/Automattic/VIP-Coding-Standards/pull/126 that tries to detect conflict resolution text in files, e.g.

```php
<?php
function is_prime( $n ) {
<<<<<<< HEAD
	if ( 2 === $n  ) {
		return true;
	}
=======
	if ( $n % 2 === 0 ) {
		return false;
	}
>>>>>>> branch-a
}
```

It might be worth merging into WPCS rather than VIPCS given its platform agnostic nature.

If the PR is good as is I can adjust the namespaces etc and create a PR to put the sniff in the `WordPress` ruleset, perhaps under `WhiteSpace`?

**Comment by grappler** [comment]
This might be even useful further upstream.

**Comment by jrfnl** [comment]
There is already a PR (by me) open for a sniff to do just this in PHPCS upstream: https://github.com/squizlabs/PHP_CodeSniffer/pull/1724

**Comment by jrfnl** [comment]
FYI: The upstream PR has been merged. Also see #1500.
