### ISSUE TITLE
Next version: 1.0.1 or 1.1.0 ? & release schedule

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1455]
As WPCS 1.0.0 has been released and semantic versioning is now properly in effect, releasing new versions on a more regular basis will be easier as we can manage expectations better through the version number.

There are currently 8 issues/PRs in the [`1.0.1` milestone](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/milestone/17) with only two of those being interesting to end-users - #1417, which has some trouble passing Travis, and #1437 (merged).

There are also currently 4 open PRs in the [`1.1.0` milestone](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/milestone/18).

With that in mind, I'd like to propose for the next release to be `1.1.0` and to re-milestone the issues in the `1.0.1` milestone to `1.1.0`.

While I don't have an exact release date/schedule in mind, I'd also like to propose to target the release of the 1.1.0 version somewhere end of August/beginning of September.

What about defining the release schedule as such: "_release approximately once a month as long as there are a minimum of two changes in `develop` which are interesting for end-users_" ?

Opinions ?

**Comment by jrfnl** [comment]
> I've found from other projects I'm involved in release dates are more troublesome than they are worth

Please see my proposal above, I'm not setting a release date, just proposing a basic principle which is quite close to what you are saying anyway, so I don't understand your objection ?

> Why not release 1.0.1 now, and punt the two remaining issues in the 1.0.1 milestone to the 1.1.0 milestone?

Because the one change interesting to end-users currently in that milestone is quite esoteric and the rest is just internal stuff, so I don't see a point in putting the effort in to create a release for that.

**Comment by GaryJones** [comment]
> With that in mind, I'd like to propose for the next release to be 1.1.0 and to re-milestone the issues in the 1.0.1 milestone to 1.1.0.

Agreed and done.
