### ISSUE TITLE
Changing between single quotes and double quotes.

### ISSUE THREAD

**Issue by corsacca** [WordPress-Coding-Standards/WordPress-Coding-Standards#1467]
PHPCS 3.3.1 WPCS 1.0.0 PHP:7.2

```
if ( isset( $_POST[ 'currentid' ] ) ){
            $id = (int) $_POST[ "currentid" ];
}
```
throws this error: `Detected usage of a non-validated input variable: $_POST `
Where this code does not:
```
if ( isset( $_POST[ 'currentid' ] ) ){
            $id = (int) $_POST[ 'currentid' ];
}
```
Is this a bug? Can you not switch between double and single quotes?

**Comment by jrfnl** [comment]
@corsacca Thanks for reporting this You're right, that looks like a bug to me and I can confirm this is happening.

**Comment by jrfnl** [comment]
@corsacca FYI: I have a fix ready for this, but the PR would conflict with another open PR, so I'm waiting to pull it until the other PR has been merged/rejected.

**Comment by corsacca** [comment]
@jrfnl thanks!

**Comment by jrfnl** [comment]
PR #1479 should fix this. Testing appreciated.
