### ISSUE TITLE
WP Core: always use short/normalized forms of type casts

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1481]
I'm just now going through the handbook again to update the WP-Core ruleset documentation to be in line and noticed a code example which triggered me:

In the **Space Usage** section: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage
> When type casting, do it like so:
> `foreach ( (array) $foo as $bar ) { ...`
> `$foo = (boolean) $bar;`

I would have expected the second example to read: `$foo = (bool) $bar;`.

While it is not a formal rule, previous art in WordPress Core suggests that it is indeed a convention to always use the short form of type casts - i.e. `(bool)` not `(boolean)` and `(int)` not `(integer)` and to prefer `(float)` over `(double)` or `(real)`.

### Metrics based on WP Core `trunk`
```
Typecast encountered:
        (int)     =>   862 ( 42.44%)
        (array)   =>   673 ( 33.14%)
        (object)  =>   220 ( 10.83%)
        (bool)    =>   142 (  6.99%)
        (string)  =>   123 (  6.06%)
        (float)   =>    10 (  0.49%)
        (boolean) =>     1 (  0.05%)
        -----------------------------
        total     => 2,031 (100.00%)
```

### Handbook change proposal

I would like to suggest adding the following to the WP Core handbook:
"_Type casts must be lowercase. Always prefer the short form of type casts, `(int)` instead of `(integer)` and `(bool)` rather than `(boolean)`. For float casts use `(float)`._".

Where necessary, example code, like shown above should be adjusted to comply.

/cc @pento

### WPCS implications
As for sniffs, there are a few candidates which come close, but writing a WPCS native sniff for this shouldn't be difficult either.

PHPCS 3.3.0 introduced the `Generic.PHP.LowerCaseType` sniff which verifies the case used in type casts, but also for function declaration parameter and return types, including an auto-fixer.

PHPCS 3.3.0 also introduced the `PSR12.Keywords.ShortFormTypeKeywords` sniff which throws errors for the long form type casts and can auto-fix these, but does not handle the `(float)` vs `(double)`/`(real)` part.

In the external [`SlevomatCodingStandard`](https://github.com/slevomat/coding-standard), the `SlevomatCodingStandard.PHP.TypeCast` sniff does handle both, but it also forbids the use of the `(unset)` and the binary cast. This sniff also contains an auto-fixer for all, but the last two issues.

### Open question
Should WPCS have an opinion on the use of the `(unset)` type cast and the binary cast ?

### Refs:
* http://php.net/manual/en/language.types.type-juggling.php#language.types.typecasting
* https://github.com/php-fig/fig-standards/blob/master/proposed/extended-coding-style-guide.md#25-keywords-and-types
* https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.3.0

Opinions (on any part of the proposal, not just the open question) ?

**Comment by pento** [comment]
> "Type casts must be lowercase. Always prefer the short form of type casts, (int) instead of (integer) and (bool) rather than (boolean). For float casts use (float).".

👍🏻

> Should WPCS have an opinion on the use of the (unset) type cast and the binary cast ?

Wow, look at those things I didn't even know existed. I have no problem saying they can't be used in core, they don't appear to have an actual purpose, but they're confusing.

**Comment by dingo-d** [comment]
The PHP manual says that the `binary` casting is 
> essential the same as (string), but it should not be relied upon.

And for `unset` it says that it's deprecated as of PHP 7.2.0, and will be removed in PHP 8.0.0.

If one is not recommended, and the other is deprecated, I wouldn't add those. I agree with pento that they are only confusing.

**Comment by jrfnl** [comment]
PR #1483 should take care of this.

**Comment by jrfnl** [comment]
The sniff has been merged and added to the `Core`ruleset.

As for the handbook update, as per the above remarks, the sniff will warn against using unset and binary casts, so I'd like to suggest this paragraph to be added to the handbook somewhere - possibly just as an addition to the reference I mentioned above:
"_Type casts must be lowercase. Always prefer the short form of type casts, (int) instead of (integer) and (bool) rather than (boolean). For float casts use (float).
Using the `(unset)` or `(binary)` cast is discouraged._".

Oh and let's make sure that any example code in the handbook which uses casts complies.

**Comment by jrfnl** [comment]
The WP Core handbook hasn't been adjusted yet. Anyone available who can quickly do this ? The text is already available in the comment above. /cc @pento

**Comment by ntwb** [comment]
I've updated the handbook just now
