### ISSUE TITLE
Error generated while editing code

### ISSUE THREAD

**Issue by mrmukaoy** [WordPress-Coding-Standards/WordPress-Coding-Standards#1496]
Every time I type any character while editing a php file, phpcs linter is generating the following error. The package author said they are merely passing on the error, and that I should report it here:

[Linter] Error running PHPCS Error: PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /usr/local/bin/wpcs/WordPress/Sniffs/WP/I18nSniff.php on line 234
PHP Stack trace:
PHP   1. {main}() /usr/local/bin/phpcs:0
PHP   2. PHP_CodeSniffer_CLI->runphpcs() /usr/local/bin/phpcs:6
PHP   3. PHP_CodeSniffer_CLI->process() phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php:113
PHP   4. PHP_CodeSniffer->processFile() phar:///usr/local/bin/phpcs/CodeSniffer/CLI.php:1016
PHP   5. PHP_CodeSniffer->_processFile() phar:///usr/local/bin/phpcs/CodeSniffer.php:1772
PHP   6. PHP_CodeSniffer_File->start() phar:///usr/local/bin/phpcs/CodeSniffer.php:1894
PHP   7. WordPress_Sniffs_WP_I18nSniff->process() phar:///usr/local/bin/phpcs/CodeSniffer/File.php:576
PHP   8. WordPress_Sniffs_WP_I18nSniff->check_argument_tokens() /usr/local/bin/wpcs/WordPress/Sniffs/WP/I18nSniff.php:208
    at ChildProcess.<anonymous> (/Users/myoakum/.atom/packages/linter-phpcs/node_modules/sb-exec/lib/index.js:56:20)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)

**Comment by GaryJones** [comment]
@mrmukaoy Can you please confirm what version of WPCS, and PHP, you're using?

For WPCS `1.0.0`, `1.1.0`, and `develop`, [line 234](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/1.0.0/WordPress/Sniffs/WP/I18nSniff.php#L234) is a comment.

I'd suggest updating to the latest version of WPCS and see if the error is still present.

**Comment by mrmukaoy** [comment]
I've got PHP 7.2.2 and npm wpcs 6.4.1.

**Comment by jrfnl** [comment]
Sorry, but in that case, you are in the wrong repo to report your issue: https://github.com/oknoorap/wpcs

The NPM package is completely unrelated to the WordPress Coding Standards Project and looks to use a ripped off and outdated version of the code in this repo.
