### ISSUE TITLE
Don't overcomplicate string comparision

### ISSUE THREAD

**Issue by szepeviktor** [WordPress-Coding-Standards/WordPress-Coding-Standards#1497]
I think

```php
if ( ! isset( $_SERVER['REQUEST_METHOD'] ) || 'GET' !== $_SERVER['REQUEST_METHOD'] ) {
```

is safe. WPCS tells me to

```php
if ( ! isset( $_SERVER['REQUEST_METHOD'] ) || 'GET' !== sanitize_text_field( wp_unslash( $_SERVER['REQUEST_METHOD'] ) ) ) {
```

Could we have an exception for literal (string) comparisons?

**Comment by jrfnl** [comment]
@szepeviktor Hi Viktor, I've been trying to reproduce this issue, but am having no luck with the code sample you provided as the sniff already takes a direct comparison into account (and has done for the longest time). 

Could you provide the exact code with which you are getting the error ?

**Comment by szepeviktor** [comment]
I think it has been fixed meanwhile.

**Comment by szepeviktor** [comment]
#feedback :)

**Comment by jrfnl** [comment]
@szepeviktor Thanks for getting back so quickly.

AFAICS, the sniff has not had any changes to that feature between when you reported it and now, so if you do come across that snippet again, please drop it in a comment & feel free to re-open the issue.
