### ISSUE TITLE
Ruleset for WordPressc ore

### ISSUE THREAD

**Issue by szepeviktor** [WordPress-Coding-Standards/WordPress-Coding-Standards#1501]
1. Is there a ruleset that core complies with?
1. Are there efforts to make core pass WPCS?

**Comment by GaryJones** [comment]
1. `WordPress-Core` is the one that best matches the handbook. You can see it's PHPCS configuration here: https://core.trac.wordpress.org/browser/trunk/phpcs.xml.dist

2. Yes - all the auto-fixable violations have been done, and there are other tickets open to manually address the rest. See the `coding-standards` focus/keyword on Core Trac.

**Comment by szepeviktor** [comment]
Thank you.
There are only 52 of them
https://core.trac.wordpress.org/query?status=!closed&focuses=~coding-standards

**Comment by jrfnl** [comment]
Please note that this applies to the (currently closed for commits) `trunk` branch of WP Core which will become WP 5.1.

**Comment by szepeviktor** [comment]
@jrfnl Does WPCS detect parenthesis for `require`?

Core seems to full of it.
https://core.trac.wordpress.org/browser/trunk/src/wp-load.php#L49

**Comment by jrfnl** [comment]
@szepeviktor The `WordPress-Extra` ruleset does, however the WP Core handbook has no rule about this, so the sniff is not included in the `WordPress-Core`.

**Comment by szepeviktor** [comment]
Thank you.
