### ISSUE TITLE
Drop Squiz.Commenting.InlineComment.SpacingAfter from Docs ruleset

### ISSUE THREAD

**Issue by Rarst** [WordPress-Coding-Standards/WordPress-Coding-Standards#1534]
## Is your feature request related to a problem?

The rule enforces "There must be no blank line following an inline comment".

This presumes that _all_ inline comments only and ever refer to code, immediately following them. One example where that might not be true would be TODOs, which Docs ruleset explicitly acknowledges as allowed.

```
(some code)

// TODO implement additional thing X here.

(some code)
```

## Describe the solution you'd like

Exclude this sniff from Docs ruleset.

**Comment by Rarst** [comment]
Could you please cite where does "inline comments can only refer to code following them" _rule_ comes from then?

**Comment by mundschenk-at** [comment]
I can offer another usecase

```php
// Comment on something, but not the code
if (something) {  
    (code)
} elseif (someotherthing) {
    // Comment on some other thing, but not the code

    (code)
} else {
...
```

For the first if, you can have the comment outside the condition. For the `elseif` conditions, that's not possible.
