### ISSUE TITLE
allow trigger_error

### ISSUE THREAD

**Issue by kkmuffme** [WordPress-Coding-Standards/WordPress-Coding-Standards#1550]
WordPress.PHP.DevelopmentFunctions.error_log_error_log disallows the use of trigger_error (among others) as a development function

In my opinion, trigger_error should not be in this rule, since there are mostly valid use cases for production. Since trigger_error can be handled by custom error handlers (unless the other functions in this rule), the plugin might want to send these errors to a custom handler or notify the user about something.

Furthermore it is useful e.g. when there is an error that can be handled without throw new exception to send something to the error log.

I can provide a pull request if wanted/needed.

**Comment by GaryJones** [comment]
Pinging @grappler for thoughts, since the whole sniff was [added](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/021b279d9b2df52eec3596f7f6e7ac6a513c5c57#diff-43cf2d00e0765cb1d135fb191aa0f4cc) by him.

**Comment by jrfnl** [comment]
> only one error handler can be used at a time

Actually error handlers can be chained, however I do admit coming across too few devs who know how to do this correctly....

> What indeed may be better though, is to adjust the groupings of that sniff

AFAICS that's not necessary as this (and other sniffs like it) are set up so:
* You can ignore a complete group using the custom WPCS [`exclude` property](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#excluding-a-group-of-checks).
* You can ignore an individual error by error code, like so `<exclude name="WordPress.Category.SniffName.group_name_function_name"/>`

**Comment by jrfnl** [comment]
@kkmuffme Glad to hear that solved it for you.

> It would be great if you could add this to the Wiki, as this could be helpful to a lot of people.

That's default PHPCS behaviour as documented in [the PHPCS wiki](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-Ruleset) which we point and link to on several of our wiki pages, including the Customizable Properties page.

**Comment by GaryJones** [comment]
> I now disabled the error with
> `<exclude name="WordPress.PHP.DevelopmentFunctions.error_log_trigger_error"/>`

Not sure what I was thinking. My quick scan of the code told me this wouldn't be possible, but in this case it already was possible.

**Comment by jrfnl** [comment]
For future reference: I just checked and the WPCS wiki [section about the `exclude` property](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#excluding-a-group-of-checks) actually also mentions the possibility to exclude individual error codes (just below the big code sample block).
