### ISSUE TITLE
WordPress.Files.FileName.strict_class_file_names exception for plugin main file

### ISSUE THREAD

**Issue by kkmuffme** [WordPress-Coding-Standards/WordPress-Coding-Standards#1566]
Plugin files should be named like the folder:
e.g. woocommerce/woocommerce.php

When having a class in the plugin file however, then the class- rule is enforced.

It is possible to disable the rule:

```
<rule ref="WordPress.Files.FileName">
	<properties>
		<property name="strict_class_file_names" value="false" />
	</properties>
</rule>
```

However, when this rule is wanted EXCEPT for the main plugin file (== the file that contains Plugin Name: ) there is no current option to set it up like this

**Comment by GaryJones** [comment]
The simplest solution would be to move your class out of your main plugin file. It's good practice (and part of [PSR-1](https://www.php-fig.org/psr/psr-1/#23-side-effects)) and while it seems to be omitted from the WP core handbook (cc @pento, @drewapicture), WordPress core follows the approach of classes being in their own file too.

The advantage of having the class in its own file, is that it can it be included with no side effects - the instantiation can be left in the main plugin file, along with any PHP / WP version checks that you may wish to run before even including the file.

Beyond that, you may be able to do something like:

```
<rule ref="WordPress.Files.FileName.InvalidClassFileName">
	<exclude-pattern>your-plugin-slug.php</exclude>
</rule>
```

...which is similar to what I [do](https://github.com/GaryJones/plugin-boilerplate/blob/master/.phpcs.xml.dist#L78-L80) to stop a check for strict_types declaration from running in my main plugin file.

**Comment by kkmuffme** [comment]
Thanks
