### ISSUE TITLE
Add Sniff for Yoda conditions

### ISSUE THREAD

**Issue by shadyvb** [WordPress-Coding-Standards/WordPress-Coding-Standards#158]
As per [WPCS] (http://make.wordpress.org/core/handbook/coding-standards/php/#yoda-conditions):

> 
```php
if ( true == $the_force ) {
    $victorious = you_will( $be );
}
```
When doing logical comparisons, always put the variable on the right side, constants or literals on the left.
>
In the above example, if you omit an equals sign (admit it, it happens even to the most seasoned of us), you’ll get a parse error, because you can’t assign to a constant like true. If the statement were the other way around ( $the_force = true ), the assignment would be perfectly valid, returning 1, causing the if statement to evaluate to true, and you could be chasing that bug for a while.
>
A little bizarre, it is, to read. Get used to it, you will.
>
This applies to ==, !=, ===, and !==. Yoda conditions for <, >, <= or >= are significantly more difficult to read and are best avoided.

/cc: @fjarrett

**Comment by JDGrimes** [comment]
Fixed by #221.
