### ISSUE TITLE
WPCS 2.0.0 Documentation tasks

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#1594]
WordPressCS 2.0.0 contains a lot of changes and the existing documentation needs to be adjusted/updated to match the "new reality".

It would be absolutely fabulous to get more people involved to help with this.

To this end, this is a list of documentation tasks from the various WPCS 2.0.0 related issues we need help with.
More information about the changes which need to be documented can be found in the linked issues:

- [x] ~~Change~~ **Remove** [Flagged Superglobal usage in WordPress](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress/) ~~to reference the `ValidatedSanitizedInput` and `NonceVerification` sniffs~~.
- [x] Go through all the wiki pages and remove/adjust any other references to the VIP ruleset and sniffs.
    The VIP ruleset and sniffs were deprecated in WPCS 1.0.0 and removed in WPCS 2.0.0.
    More info: #1551
- [x] Go through all the wiki pages and remove/adjust any references to the other sniffs which were previously deprecated and have been removed in WPCS 2.0.0.
    More info: #1446, #1552
- [x] Go through all the wiki pages and remove/adjust any references to the sniffs which have been removed outright in WPCS 2.0.0.
    More info: #1576, #1578, #1579, #1581, 
- [x] [Customizable properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) wiki page: update all the code samples for array properties to the PHPCS 3.3+ array format.
    More info/examples: #1563, https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1048#issuecomment-378570641
- [x] [Customizable properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) wiki page: add a notice that support for incorrectly passed array properties has been removed in WPCS 2.0.0.
    More info: #1584
- [x] [Whitelisting errors](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors) wiki page: add a notice that the WPCS native whitelist comments have been deprecated in WPCS 2.0.0 and will be removed in WPCS 3.0.0 and add code samples of how to whitelist code using the PHPCS 3.2+ native whitelist comments.
    More info: #1580
- [x] Go through the wiki pages to see if the old error codes for the `NonceVerification` and `PrefixAllGlobals` sniffs are mentioned anywhere and if necessary, update them.
    More info: #1487 and #1556
- [x] [Customizable properties](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties) wiki page: remove/adjust references to properties which were previously deprecated and have since been removed.
    More info: #1554
- [x] Remove the [PHPCS 3 and including individual sniffs](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/PHPCS-3-and-including-individual-sniffs) wiki page as it's no longer applicable.
 - [x] Change snippets with `{space}/>` (space before slash) to `/>` (no space). Now there's an XSD, and linting is possible, fixing these minor bits is useful.

If you're starting work on one of these action items, please leave a comment in this thread to claim the action.

Also, please leave comments if you think of action items I've forgotten, so they can be added to the list.

**Comment by GaryJones** [comment]
Another small item - changes snippets with ` />` (space before slash) to `/>` (no speace). Now there's an XSD, and linting is possible, fixing these minor bits is useful.

**Comment by GaryJones** [comment]
> * Go through all the wiki pages and remove/adjust any references to the VIP ruleset and sniffs.

Done, though I've hadn't changed https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress-VIP/_edit to reference `ValidatedSanitizedInputSniff`.

**Comment by GaryJones** [comment]
> Am I right in thinking you removed that page instead ?

No - I started and had renamed it to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress - but rather than delete, I presumed you'd want it to be refactored to be based around `ValidatedSanitizedInputSniff` instead. I started looking at it, but didn't get very far.

**Comment by jrfnl** [comment]
Ah, ok, I couldn't find the link anymore on the wiki home page and the link in the right bar menu 404s now, so I wasn't sure what was happening...

Might be good if that page gets rewritten to center it around both `ValidatedSanitizedInput` as well as `NonceVerification` as most people will get both those errors when a superglobal is used without security checks.

**Comment by GaryJones** [comment]
> Might be good if that page gets rewritten to center it around both ValidatedSanitizedInput as well as NonceVerification as most people will get both those errors when a superglobal is used without security checks.

I think your expertise may be better suited for the rewrite :-)

**Comment by jrfnl** [comment]
> I think your expertise may be better suited for the rewrite :-)

Not sure if I'm the best person for that job. Can't help but miss @JDGrimes ... 

Then again, who knows, I might be able to interest @andizer to write it and show off everything he learned last week *_nudge_* :sunglasses:

**Comment by jrfnl** [comment]
I've just done a quick glance over the wiki page and made some small additional adjustments. Thank you @GaryJones for doing the bulk of what needed to be done.

Aside from the [Fixing errors for input data](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Fixing-errors-for-input-data) page, I consider this issue sufficiently addressed now.

**Comment by GaryJones** [comment]
> As an update to the [Flagged superglobal usage in WordPress](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress) would duplicate a lot of the info on the "_Fixing errors for input data_" page, I think the "_Flagged superglobal usage in WordPress_" should be removed in favour of improving the "_Fixing errors for input data_" page (where necessary).

Agreed. The "Flagging superglobals..." page seemed quite specific. Go ahead and delete it when you're ready. May also need to see if any of these now-deleted wiki pages are referenced in the code base (comment, etc.)

**Comment by jrfnl** [comment]
> May also need to see if any of these now-deleted wiki pages are referenced in the code base (comment, etc.)

Just checked & no links to the wiki found in inline docs, only in the Readme/Contributing/Changelog/sample ruleset.
Most to either the PHPCS wiki, the WPCS wiki homepage, the customizable properties page or the whitelist flags page. As far as I can see no (direct) links to any of the wiki pages we're removing.

It may be worth checking if those links are all still valid, but especially for the changelog, I'm not too concerned, we don't need to rewrite history.

**Comment by jrfnl** [comment]
I've removed the "Flagging superglobals" page + removed both that page as well as the other removed page (PHPCS3 & including individual sniffs) from the Wiki sidebar.

IMO that finishes what needed to be done here.
