### ISSUE TITLE
ERROR: Referenced sniff "Generic.WhiteSpace.LanguageConstructSpacing" does not exist

### ISSUE THREAD

**Issue by metalandcoffee** [WordPress-Coding-Standards/WordPress-Coding-Standards#1614]
## Bug Description

After pulling the latest wpcs from the `master` branch, I get an error when attempting to lint a `php` file from the terminal. I was able to avoid the error by reverting back to a previous commit ( about 10 days ago, `git checkout b686b37ea869a6d489c40af023b2bd69b92569a3 .` )

## Minimal Code Snippet

```php
phpcs --standard=WordPress page-home.php
```

## Error Code
```
ERROR: Referenced sniff "Generic.WhiteSpace.LanguageConstructSpacing" does not exist

Run "phpcs --help" for usage information
```

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.2.1 
| PHP_CodeSniffer version | 3.4.0
| WPCS version            | whatever version `master` is on 🤷🏾‍♀️
| WPCS install type       | git clone

## Tested Against `develop` branch?
- [ x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by GaryJones** [comment]
PHPCS 3.4.0 does still contain https://github.com/squizlabs/PHP_CodeSniffer/blob/3.4.0/src/Standards/Generic/Sniffs/WhiteSpace/LanguageConstructSpacingSniff.php and it has done since the 3.0 shift around.

Thanks - we'll take a look :-)

**Comment by metalandcoffee** [comment]
Sure :)

```
metalandcoffee$ phpcs --standard=WordPress page-home.php
ERROR: Referenced sniff "Generic.WhiteSpace.LanguageConstructSpacing" does not exist

Run "phpcs --help" for usage information

metalandcoffee$ phpcs --version
PHP_CodeSniffer version 3.4.0 (stable) by Squiz (http://www.squiz.net)
metalandcoffee$ phpcs -i
The installed coding standards are PEAR, Zend, PSR2, MySource, Squiz, PSR1, PSR12, WordPress, WordPress-Extra, WordPress-Docs and WordPress-Core
metalandcoffee$ 
```

**Comment by metalandcoffee** [comment]
I did some more investigation into my `phpcs` install and found the file referenced by @GaryJones missing. When I run `pear install PHP_CodeSniffer`, it says that it installed version 3.4.0. However when I check the files from the install, that sniff is no where to be found.

So unfortunately it looks like using PEAR to install the latest PHP CodeSniffer is not ideal. Instead - I just installed the PHP CodeSniffer by downloading the Phar files themselves and I don't have a problem at all.

My apologies for making it seem like a `wpcs` bug!

**Comment by jrfnl** [comment]
@metalandcoffee Ah! That explains it. Thanks for letting us know.
I've just had a quick look at the PHPCS `package.xml` file which PEAR use it looks like someone forgot to add the new sniff to that, so you've actually identified a bug in PHPCS itself.
I will fix this and send a PR to PHPCS, as well as see about adding something to the PHPCS build check to prevent these type of issues from occurring in the future.

**Comment by metalandcoffee** [comment]
Thanks @jrfnl !!!

**Comment by jrfnl** [comment]
FYI: I've opened two PRs in the PHPCS repo.
PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2340 is the hotfix for the current issues with the PEAR install (including the one reported here).
PR https://github.com/squizlabs/PHP_CodeSniffer/pull/2341 should guard against this ever happening again.
