### ISSUE TITLE
Core: Exceptions to WordPress.Files.FileName.NotHyphenatedLowercase

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#1621]
## Bug Description

There are a handful of exceptions to the `WordPress.Files.FileName.NotHyphenatedLowercase` sniff:

```
/src/_index.php
/src/wp-admin/_index.php
/src/wp-content/themes/twentythirteen/taxonomy-post_format.php
/src/wp-content/themes/twentyfourteen/taxonomy-post_format.php
```

## Error Code

`WordPress.Files.FileName.NotHyphenatedLowercase`

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.1.23
| PHP_CodeSniffer version | 3.3.1
| WPCS version            | 1.0.0
| WPCS install type       | Composer project local

## Tested Against `develop` branch?
- [ ] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by jrfnl** [comment]
Sniffs can't and shouldn't be based on exceptions, so this is typically something which would need to be handled in the project ruleset:

```xml
<rule ref="WordPress.Files.FileName.NotHyphenatedLowercase">
    <exclude-pattern>/src/_index\.php$</exclude-pattern>
    <exclude-pattern>/src/wp-admin/_index\.php$</exclude-pattern>
</rule>
```

or simplified (regex untested):
```xml
<rule ref="WordPress.Files.FileName.NotHyphenatedLowercase">
    <exclude-pattern>/src/(*/)?_index\.php$</exclude-pattern>
</rule>
```


As for the theme files, I wonder if the themes shouldn't be excluded from the "normal" run and have their own ruleset which inherits from the main ruleset.

For themes, the sniff has an [`is_theme` property](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Customizable-sniff-properties#themes-allow-filename-exceptions) which can be set to `true` which would allow for these exceptions and all the others described in:
* https://developer.wordpress.org/themes/basics/template-hierarchy/
* https://developer.wordpress.org/themes/template-files-section/

Alternatively, you could just add them to the exclude list mentioned above as those file name are valid in the context of the themes.

**Comment by ntwb** [comment]
> As for the theme files, I wonder if the themes shouldn't be excluded from the "normal" run and have their own ruleset which inherits from the main ruleset.

I'd like to see this, in my mind I'm thinking that the core themes should use the WPTRT ruleset

**Comment by jrfnl** [comment]
> I'm thinking that the core themes should use the WPTRT ruleset

@ntwb I personally would say they'd need to use `WordPress-Core` + the WPTRT ruleset.
The WPTRT ruleset has nothing about code style as for a community theme it is perfectly valid to use PSR-2 or any other standard.
I'd like to think that the WP native themes _should_ however comply with the WP code style rules.

**Comment by jrfnl** [comment]
@pento Was my answer sufficient ? Can we close this issue ?

**Comment by pento** [comment]
Aye, let's not worry about fixing it in WPCS.
