### ISSUE TITLE
Disallow use of non wp_remote_get functions

### ISSUE THREAD

**Issue by kkmuffme** [WordPress-Coding-Standards/WordPress-Coding-Standards#1631]
Like in VIP ruleset
https://vip.wordpress.com/documentation/vip-go/code-review-blockers-warnings-notices/#remote-calls

**Comment by kkmuffme** [comment]
Yes I know, that is why I propose to add a rule for wp_remote_* in this standard, as it makes sense for general WP as explained in the above link.
So normal functions like curl,... will get flagged and prompt to use wp_remote_*

**Comment by lkraav** [comment]
It would certainly help from an educational perspective. People, esp. non-WP devs, often just don't know about WP API details.

**Comment by dingo-d** [comment]
That wouldn't make much sense as WordPress core itself contains `cURL` (`wp-includes/class-wp-http-curl`).

All the `wp_remote_*` methods are in one or another way, a wrappers around native php remote libraries like `cURL` or methods like `file_get_contents()`.

And [WPThemeReview](https://github.com/WPTRT/WPThemeReview) standard already has a sniff for forbidden functions 🙂 

@kkmuffme you are welcomed to take a look and contribute to Theme Review standards if you wish 🙂

**Comment by kkmuffme** [comment]
Yes, obviously WP contains curl et al. under the hood, but that is the case with most WP function (see esc, sanitize, ...) but it's always preferred to use the WP equivalent, as it often contains some additional logic that is missing when using e.g. curl directly.

This is also the reason, why it is encouraged/required by WP VIP and would make sense generally.


WPThemeReview might have it, the official (new) Wordpress VIP code standard might have it too.
But it makes sense to add it here, to this general standard, as it is something that is often done incorrectly, but explicitly mentioned in the VIP docs and a general issue

**Comment by jrfnl** [comment]
I suggest closing this issue as this is already covered by the `WordPress.WP.AlternativeFunctions` sniff.

**Comment by jrfnl** [comment]
Closing for lack of response.

If you believe there are functions missing from the lists in the `WordPress.WP.AlternativeFunctions` sniff which should be covered, feel free to open a new issue with suggestions and/or a PR.
