### ISSUE TITLE
How to change labels in the projects page wp-admin

### ISSUE THREAD

**Issue by marwasaaid** [WordPress-Coding-Standards/WordPress-Coding-Standards#1637]
​I want to change labels in this page ex: Client -> Owner What is the file name where I can change these labels from?

screenshot:

![image](https://user-images.githubusercontent.com/42501580/51870663-eeb03700-235c-11e9-9562-79ee70fed70b.png)

I tried to do it by javascript, but it caused effect on all website pages, on previewing, editing or updating, the page turns to white.

This is my piece of code:

```
echo "<script type='text/javascript'>
        window.onload = replaceTxt; 
         function replaceTxt() {
         var vr1 = document.getElementById('_bunch_bunch_projects_settings[client]').childNodes[1].childNodes[1].innerHTML;
         var vr11 = vr1.replace('Client','Owner');
}
         </script>";
```

**Comment by jrfnl** [comment]
@marwasaaid You are asking this in the wrong place. This repository is about the WordPress Coding Standards and automated checks to verify compliance.

For general support about using and/or customizing WordPress, please visit the [WordPress support forums](https://wordpress.org/support/).
