### ISSUE TITLE
Warn if using ** at beginning of non doc block multiline comments

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#165]
If inside of a function, instead of:

```php
/**
 * Hello
 * world!
 */
```

The first line of the multiline comment should have a single `*` as:

```php
/*
 * Hello
 * world!
 */
```

I was requested to do this when contributing to Core: https://github.com/x-team/wordpress-develop/commit/74e3568af4efaf3fb1c3eef0f7a1ee78622123ec

**Comment by GaryJones** [comment]
This should be captured under #241.
