### ISSUE TITLE
Sanitizing a multi-dimensional array

### ISSUE THREAD

**Issue by kkmuffme** [WordPress-Coding-Standards/WordPress-Coding-Standards#1660]
How can I sanitize a multi-dimensional array in POST?

`$_POST['my-example']` is a multi-dimensional array like:

```php
array(
	array( 
		'someValue' => 123,
		'hello' => 'world',
	),
	array(
		'someValue' => 456,
		'hello' => 'mars',	
	)
);
```

This doesn't work (since it only works for 1 level of arrays)
```php
$my_example = array_map( 'sanitize_text_field', wp_unslash( $_POST['my-example'] ) );
```

and using:

```php
$my_example = array();
foreach( $_POST['my-example'] as $value ) {
	$my_example[] = array_map( 'sanitize_text_field', wp_unslash( $value ) );
}
```

throws an error that I am using unsanitized POST

Is there any way without using phpcs:ignore?

Thanks for your help!

**Comment by GaryJones** [comment]
Would [`map_deep()`](https://developer.wordpress.org/reference/functions/map_deep/) help here?

**Comment by NielsdeBlaauw** [comment]
Maybe use [`filter_input()`](https://secure.php.net/manual/en/function.filter-input.php) with [`FILTER_CALLBACK`](https://secure.php.net/manual/en/filter.filters.misc.php)?

**Comment by kkmuffme** [comment]
@GaryJones it works (output is correct, which I also get with array_walk_recursive) but I still get: Detected usage of a non-sanitized input variable: $_POST

```
$my_example = map_deep( wp_unslash( $_POST['my-example'] ), 'sanitize_text_field' );
```

Ideally map_deep (& array_walk_recursive & also the solution suggested by @NielsdeBlaauw ) with sanitize_text_field (and FILTER_SANITIZE_STRING respectively) should be set as a sanitization function, so this error doesn't come up incorrectly.

**Comment by jrfnl** [comment]
Duplicate of #1618 ?

**Comment by kkmuffme** [comment]
@jrfnl I closed https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1618 now because similar, but the issue is better & more comprehensively described in this current issue.

**Comment by jrfnl** [comment]
I've looked into this and will pull a PR to partially fix this soon.

The fix in the PR will add allowance for using `map_deep` to the sniff.

It will **not** add `array_walk()` or `array_walk_recursive()`. The reason behind this is two-fold:
1. These cannot easily be used for sanitization as they can't be combined with unslashing, so you could combine them with the `$unslashingSanitizingFunctions`.
    ```php
    // This would alter the return value of `wp_unslash()` as it is in the PHP memory and
    // would throw a "Only variables should be passed by reference" error.
    // The actual value of `$_POST['my_form']` would be unchanged.
    if ( isset( $_POST['my_form']['field'] ) && array_walk( wp_unslash( $_POST['my_form'] ), 'sanitize_text_field' ) ) {}
    ```
2. Additionally as they alter the array by reference, at this moment, accessing the array after sanitization through one of these function would _still_ trigger errors as the sniff looks for usage of the superglobals.
    ```php
    if ( isset( $_POST['your_form']['field']['sub'] ) && array_walk_recursive( $_POST['your_form'], 'intval' ) ) {
        // I should be able to safely use the value now, but the sniff would still trigger errors as it is now.
        $string = '<input name="test" value="' . $_POST['your_form']['field']['sub'] . '" />';
    }
    ```

All in all, it seemed better to not give the impression that the `array_walk...()` functions are supported, while they aren't really.

@NielsdeBlaauw's suggestion of using `filter_input()` will also work and already doesn't throw an error, so no action was needed to support it.
Do be aware of server quirks when using `filter_input()` though - see: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/1541#issuecomment-478246098
