### ISSUE TITLE
To Add Custom Restricted function in PHP.RestrictedPHPFunctions

### ISSUE THREAD

**Issue by amritansh24** [WordPress-Coding-Standards/WordPress-Coding-Standards#1663]
## Is your feature request related to a problem?
 I use PHP console library for the debugging purpose and want to ensure that debugging functions are not part of the real package. The functions are like PC::debug($variable); 

## Describe the solution you'd like
 I am not sure but if we can provide a way to add custom restrcited functions in PHP.RestrictedPHPFunctions , just like we do with WordPress.Security.ValidatedSanitizedInput

**Comment by jrfnl** [comment]
@amritansh24 No, you will need to write a custom sniff for that.

As for why:
* You don't want to look for native PHP functions, but for userland methods.
* WPCS has the `AbstractFunctionRestrictionsSniff` base class (which the `WordPress.PHP.RestrictedPHPFunctions` extends), but using that would not be suitable for your usecase as it tries to only look at calls to _global_ functions and purposefully tries to exclude mismatching PHP native functions vs userland methods of the same name, i.e. it won't match on `MyClass::create_function()` or `\MyNameSpace\create_function()`.
* PHPCS upstream has a similar sniff, [`Generic.PHP.ForbiddenFunctions`](https://github.com/squizlabs/PHP_CodeSniffer/wiki/Customisable-Sniff-Properties#genericphpforbiddenfunctions), but again, it will only look at calls to _global_ functions.

So, if you want to match calls to methods in combination with a certain class name (static calls), namespace or with a certain object variable, you will need a custom sniff.

**Comment by amritansh24** [comment]
Hi @jrfnl , 
Thanks for the explanation. 
Could you guide me to take a look at some of the existing sniffs to get some idea from?

**Comment by jrfnl** [comment]
@amritansh24 The above named sniffs are a good starting point.

**Comment by amritansh24** [comment]
Okay @jrfnl , 
Thanks for the suggestions.

**Comment by jrfnl** [comment]
@amritansh24 Good luck writing the sniff. As there's nothing for us to do here, I'll close this issue now.
