### ISSUE TITLE
Flag unescaped variables passed to printf, fwrite, etc

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#170]
There are functions other than the `echo` and `print` statements which output data. The `printf` function, for example, we've seen used at times to get around PHPCS warnings.

**Comment by JDGrimes** [comment]
We now flag `printf()`. Do you still think `fwrite()` be added to the list?

**Comment by westonruter** [comment]
Perhaps, but in practice I don't think I've ever seen `fwrite()` used in any theme or plugin code, so it seems like a very low priority.

**Comment by GaryJones** [comment]
Also, use of the Filesystem API should be encouraged.

**Comment by grappler** [comment]
`fwrite()` is now included in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/633
