### ISSUE TITLE
Creating a new Anonymous class require Parenthesis.

### ISSUE THREAD

**Issue by LC43** [WordPress-Coding-Standards/WordPress-Coding-Standards#1721]
## Bug Description
Creating a new Anonymous class require Parenthesis but it shouldn't ( i think )

## Minimal Code Snippet

```php
return new class implements SomeInterface {}
```

vs
```php
return new class() implements SomeInterface {}
```

## Error Code
WordPress.Classes.ClassInstantiation.MissingParenthesis

## Environment

| Question               | Answer
| ------------------------| -------
| PHP version             | 7.2.17
| PHP_CodeSniffer version | 3.4.2
| WPCS version            | 2.1.1
| WPCS install type       | Composer project local
| IDE (if relevant)       | VSCode 1.34.0

## Tested Against `develop` branch?
- [x] I have verified the issue still exists in the `develop` branch of WPCS.

**Comment by LC43** [comment]
Related:

"should also consider if this suggested rule should (also) be applied to anonymous classes."
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/919#issuecomment-315167559

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/1033

**Comment by jrfnl** [comment]
The choice was made to make parentheses required on all class instantiations. I see no reason why anonymous classes should be exempt from this, especially as the rule has been in place for two years already.

**Comment by LC43** [comment]
Hi  

i searched around. the only mention in bugs is that line above, and the handbook still has no references to this. It seems there's no real justification other than conformity.

closing it for now. My preference is to have clean code, so i'll just had the exception to our cs.
thanks
