### ISSUE TITLE
Add sniff to require a $wpdb->prepare() to have a 2nd argument

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#19]

**Comment by JDGrimes** [comment]
Related: [WP#22262](https://core.trac.wordpress.org/ticket/22262 "Possible invalid uses of wpdb::prepare()").

**Comment by GaryJones** [comment]
Could we count the `%s`, `%d` etc. and make sure there's enough arguments to cover the placeholders?

**Comment by jrfnl** [comment]
Closing - the original issue is already covered. The remaining additional issues have been been added to a new ticket: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/641

**Comment by jrfnl** [comment]
Definitively fixed in #1160
