### ISSUE TITLE
PHP-CS-Fixer 

### ISSUE THREAD

**Issue by Mte90** [WordPress-Coding-Standards/WordPress-Coding-Standards#223]
After this ticket https://github.com/fabpot/PHP-CS-Fixer/issues/329 i've written this config file but i don't know if is correct.
https://github.com/Mte90/WordPress-Plugin-Boilerplate-Powered/blob/master/plugin-name/.php_cs

I think that an official config file for PHP-CS-Fixer will be very useful for everybody

**Comment by corysimmons** [comment]
Why was this closed?

**Comment by GaryJones** [comment]
PHPCS now supports automatic fixing via the phpcbf feature. None (or very few) of the custom WP sniffs have been adapted to support automatic fixing yet, but it is something to consider when someone has sufficient time to contribute.

**Comment by corysimmons** [comment]
Yeah I just noticed the phpcbf feature. Nice!

It seems to act weird sometimes but I'll open up new issues for those.
