### ISSUE TITLE
Use prefix for whitelisting comments

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#228]
As per the [Wiki page](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Flagged-superglobal-usage-in-WordPress-VIP) I just created, the quieting of superglobals flagging can be done with adding:

``` php
// input var okay
```

...at the end of the relevant line.

I'd like to see this (and any other similar whitelisting comments) changed to include a prefix, i.e.:

``` php
// WPCS: input var okay
```
- Just like `translators:`, it programatically namespaces the comment, so it avoids clashes with other programs that might be looking at comments as directives.
- It also differentiates the comment for humans, as it looks less like a random comment that a future developer who doesn't know about WPCS might delete not realising it's purpose.

**Comment by JDGrimes** [comment]
After #334, whitelisting is accepted, but it isn't required.

**Comment by westonruter** [comment]
Alternative proposal: #393

**Comment by GaryJones** [comment]
The [whitelisting wiki page](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors) has all the examples with `WPCS:` as a prefix, but I'm happy that while this creates a de facto format, we don't specifically require it. It helps to avoid confusion when multiple whitelist flags need to be added to the same line too (the "best guess" format just works).
