### ISSUE TITLE
ReadMe's install instructions miss step for Windows users and Troubleshooting section refers to pear install

### ISSUE THREAD

**Issue by crazyjaco** [WordPress-Coding-Standards/WordPress-Coding-Standards#232]
Basically, the install instructions in the Readme.md offer a way to install phpcs w/o pear.
Thank you to whomever wrote that!

Couple problems:
1. The troubleshooting section still refers to pear.
2. As a Windows user, it works fine for the most part from the git shell, but not at all from a command window. 

I discovered that the php.bat file has several variables that are expected to be replaced by pear upon install.
It is easy enough to fix, but I thought it might help if it was mentioned in the Readme.md's instructions.

I cannot create a valid pre-commit hook in git using the current instructions. Fixing the variables in the php.bat remedied the problem for me.

`"@php_bin@" -d auto_append_file="" -d auto_prepend_file="" -d include_path="'@php_dir@'" -f "@bin_dir@\phpcs" -- %*`

@php_bin@ - path to php.exe (including the file name - (ie: c:\xampp\php\php.exe)
@php_dir@ - path to (and including) directory containing php.exe (ie: c:\xampp\php)
@bin_dir@ - path to phpcs (ie: c:\PHPCodeSniffer\phpcs\scripts )

**Comment by JDGrimes** [comment]
I think the install instructions have changes since this ticket was opened, and there isn't a Troubleshooting section anywhere anymore that I can see. It sounds like this was mostly an upstream issue anyway.
