### ISSUE TITLE
False positive - Expected 1 space before "!"

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#234]
~~~php
	if (
		empty( $_GET['refid'] ) &&
		empty( $_GET['nolinks'] ) &&
		! is_page_template( 'page_strategy-center.php' ) &&
		! is_page_template( 'page_confirmation.php' ) &&
		! is_page_template( 'page_debartolo.php' ) &&
		! is_singular( 'offer' )
	) {
~~~

This gives errors including:

> 13 | ERROR   | [ ] Expected 1 space before "!"; 2 found
 14 | ERROR   | [ ] Expected 1 space before "!"; 2 found
 15 | ERROR   | [ ] Expected 1 space before "!"; 2 found
 16 | ERROR   | [ ] Expected 1 space before "!"; 2 found

The whitespace before the `!` are two correct tabs for indentation. There are no spaces hidden in there.

**Comment by Roberto-Sudo** [comment]
#252 is already merged but this issue was never closed (just a heads up)
