### ISSUE TITLE
Create sniff to warn if too much logic is appearing in the template

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#24]
Logic should be placed in functional includes, encapsulated with other logic for the component (e.g. in a class). Templates should consist of template tags, some conditionals, and building queries.

**Comment by GaryJones** [comment]
How much is "too much"?

**Comment by westonruter** [comment]
If a function is defined in a template file, that would probably be an
automatic too-much-logic warning. Creating variables would also be a red
flag. Otherwise, there are tools that calculate code complexity (e.g. PHP
Depend?) that might inspire here.

But this might be overly pedantic and might as well be closed.
