### ISSUE TITLE
Some VIP errors should be Extras warnings

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#240]
VIP contains, as an example, sniffs that say [changing timezone](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/WordPress/Sniffs/VIP/TimezoneChangeSniff.php) is prohibited, as is using a [session functions](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php), and that [superglobals should be sanitized](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/master/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php) or even warnings that they are being used.

I'd like to see versions of these and others applied to the Extras ruleset, but as warnings (that can be hidden with changes of severity). Not all are going to be suitable - [this PR](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/239/files) for instance says to use `wpcom_vip_*()` functions, but some of the VIP best practices that aren't VIP environment specific could be applied as Extras so everyone could optionally tighten up their coding practices.

**Comment by grappler** [comment]
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/633 should fix most of this.

**Comment by JDGrimes** [comment]
#1261 add more rules from VIP to Extra.

Remaining `.VIP` sniffs not in `Extra`:

- `AdminBarRemoval`
- `OrderByRand`
- `RestrictedFunctions`
- `RestrictedVariables`
- `SessionFunctionsUsage`
- `SessionVariableUsage`
- `SuperGlobalInputUsage`

I'm not sure if any of these are really needed in `Extra` or not.

**Comment by jrfnl** [comment]
Let's not forget the other three mentioned in #1261:

> Note: There are three more candidates for this:
> 
> * DB.DirectDatabaseQuery
> * DB.SlowDBQuery
> * Security.ValidatedSanitizedInput
>
> I've not included the first two (yet) as those may need some more discussion first.
> The third one is not included as it throws a lot of noise messages and has quite some open issues surrounding it, which should be addressed first IMO.

**Comment by jrfnl** [comment]
AFAICS everything but the last comment in this thread has been addressed and the last comment has a dedicated (open) issue: #1440 

@GaryJones Can we close this issue ? or am I missing something ?

**Comment by GaryJones** [comment]
All good to close.
