### ISSUE TITLE
What's the difference between autoescaped and escaping functions?

### ISSUE THREAD

**Issue by kkmuffme** [WordPress-Coding-Standards/WordPress-Coding-Standards#2411]
It's not clear from the code nor from the docs. Could someone clarify this?

**Comment by dingo-d** [comment]
As noted in the docblock above the properties, `autoEscapedFunctions` are functions whose output is automatically escaped for display.

`escapingFunctions` are functions that escape values for display.

Ref: https://github.com/WordPress/WordPress-Coding-Standards/blob/develop/WordPress/Helpers/EscapingFunctionsTrait.php

**Comment by dingo-d** [comment]
The difference is the purpose of the function.

We put functionalities in the function for the sake of some intention. The intention or purpose of escaping functions is to escape - that is, _make the output safe to use_. That is what they do. You pass the input in, and the output you get is safe to display.

Autoescaped functions are not about escaping. For instance, the `wp_title` function's purpose is to _display or return the page title_. That function is safe, in that, no matter what you pass, the result you get is safe to use.

**Comment by dingo-d** [comment]
Code is written for humans, and knowing the distinction between the two is very useful to have documented. 

I can tell you from first-hand experience that this list was useful when reviewing themes for instance 😉
