### ISSUE TITLE
Sniff for strict rather than loose comparisons

### ISSUE THREAD

**Issue by mattyrob** [WordPress-Coding-Standards/WordPress-Coding-Standards#242]
I wonder if we should be encouraging use of === and !== instead of == and !=.

Sniff and unit tests available if you want them.

**Comment by JDGrimes** [comment]
The PR for this ended up being #351 instead. However, the sniff wasn't added to any of the rulesets. I don't know if it will still run with the `WordPress` ruleset or not. Do we want to consider adding it to `WordPress-Extra`? Or do we want to leave it as an optional one that you have to add to a custom ruleset yourself?

**Comment by westonruter** [comment]
Adding it to the `WordPress-Extra` ruleset makes sense to me. It seems like a best practice to do strict comparisons.

**Comment by westonruter** [comment]
VIP flagged some code to me that had a loose comparison, so I've gone ahead and added the sniff to `WordPress-VIP`: b9fedd9a86778507423b309fcafaa7f83bc16022
