### ISSUE TITLE
Notice: Undefined index: parenthesis_closer

### ISSUE THREAD

**Issue by wedi** [WordPress-Coding-Standards/WordPress-Coding-Standards#248]
Good day!
When checking my plugin files using your great work I get the following notice:

Notice: Undefined index: parenthesis_closer in [WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php on line 117](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/7150994d34f6d01892e3903c2bbddfdef7b55aff/WordPress/Sniffs/VIP/ValidatedSanitizedInputSniff.php#L117)

```
Call Stack:
    0.0021     232280   1. {main}() ~/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs:0
    0.0210    1186312   2. PHP_CodeSniffer_CLI->process() ~/.composer/vendor/squizlabs/php_codesniffer/scripts/phpcs:37
    0.0274    1240616   3. PHP_CodeSniffer->process() ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/CLI.php:622
    0.1842    2449128   4. PHP_CodeSniffer->processFile() ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:488
    0.1843    2449432   5. PHP_CodeSniffer->_processFile() ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1351
    0.1843    2449880   6. PHP_CodeSniffer_File->start() ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1471
    0.3347    5710256   7. WordPress_Sniffs_VIP_ValidatedSanitizedInputSniff->process() ~/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer/File.php:506
```

```
php -v
PHP 5.4.33 (cli) (built: Oct 10 2014 18:46:18)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.4.0, Copyright (c) 1998-2014 Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

**Comment by grappler** [comment]
I got this error with this code as it is missing a bracket at the end. 

```php
echo add_filter( get_the_excerpt( get_the_ID() ) ;
```

> Error: PHP Notice: Undefined index: parenthesis_closer in /WordPress/Sniffs/XSS/EscapeOutputSniff.php on line 322 PHP Notice: Undefined index: parenthesis_closer in /WordPress/Sniffs/XSS/EscapeOutputSniff.php on line 220

Was running `PHP 7.1.0 (cli)` and the latest dev version of WPCS and PHPCS `2.7.1`

**Comment by jrfnl** [comment]
I suggest adding a complete review for "live coding" type of situations (which will typically be code with parse errors like this) to the other reviews as suggested in #763, #764

@grappler Just wondering: did the `Generic.PHP.Syntax` sniff throw an error for that file for the missing bracket / parse error ? (only in `extra`)

**Comment by grappler** [comment]
@jrfnl No, because the PHPCS failed at that point but `Generic.PHP.Syntax` throws an error when I test your PR.

**Comment by jrfnl** [comment]
@grappler Ok, good.
I tested this myself as well (as travis was failing and I had to look at the unit tests) and found something off in that sniff, so opened an upstream PR to fix that: https://github.com/squizlabs/PHP_CodeSniffer/pull/1260
