### ISSUE TITLE
Merge relevant changes (cherry-pick) from other forks

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#28]
There are 3 other forks (by @bigfishdesign, @rarescosma, and @yapapaya) from the original @mrchrisadams repo and we should integrate their relevant changes: https://github.com/mrchrisadams/WordPress-Coding-Standards/network

https://github.com/bigfishdesign/bigfish-coding-standards
https://github.com/rarescosma/WordPress-Coding-Standards
https://github.com/yapapaya/WordPress-Coding-Standards

**Comment by GaryJones** [comment]
Was there anything specific you wanted from these other forks?

**Comment by westonruter** [comment]
It has been so long that anything from other forks would probably have made
its way here by now via PRs, I would hope. If any of the fork owners want
to upstream their changes, it can be done via new issues.

#close
