### ISSUE TITLE
XSS escaping and the ternary operator

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#281]
I got this error:

> 211 | ERROR | Expected next thing to be a escaping function, not '('

The offending line:
```
value="<?php echo ( $args['placeholders'] && 'hidden' !== $field['type'] ) ? '<% if ( typeof ' . sanitize_key( $name ) . ' !== "undefined" ) { print( ' . sanitize_key( $name ) . ' ); } %>' : esc_attr( $value ); ?>"
```
While on the one hand this is messy, I chose to do it anyway because it was the best way to do the escaping immediately before output.

When dealing with the ternary operator, I think we need to ignore everything before the `?`.

**Comment by westonruter** [comment]
> Neither of those solutions will work. The backbone template will break if it is put through `esc_attr()`.

@JDGrimes Can you show how it breaks?

In the case of:

* `class="<?php echo ( $i % 2 ) ? 'even' : 'odd'; ?>"`
* `<td <?php echo ( $is_hidden ? ' style="display:none;"' : '' ); ?>>`

The problem is that the two conditions for the ternary are both literal strings, without any variables being output. So it should be treated the same way as `echo "...";`. This is something which should be fixed.

**Comment by JDGrimes** [comment]
> >Neither of those solutions will work. The backbone template will break if it is put through esc_attr().
> 
> @JDGrimes Can you show how it breaks?

The result will be this:

`&lt;% if ( typeof thing !== &quot;undefined&quot; ) { print( thing ); } %&gt;`

And Underscore won't recognize that as being a [template placeholder](http://underscorejs.org/#template) when calling `_.template()`.

**Comment by westonruter** [comment]
But

**Comment by westonruter** [comment]
But won't:

```
&lt;% if ( typeof thing !== &quot;undefined&quot; ) { print( thing ); } %&gt;
```

Be properly unescaped when JavaScript accesses the property from the DOM?

**Comment by JDGrimes** [comment]
All I know is, it didn't work. The value wasn't replaced by Underscore with the value from the object when the template was processed. Underscore didn't recognize it as being a placeholder.

**Comment by westonruter** [comment]
Oh, of course. Because you're using Underscore to build out the HTML string. You're not trying to store the Underscore template as the value of the placeholder, which doesn't make sense anyway.
