### ISSUE TITLE
Whitelisting for the input sanitization sniff

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#293]
In the XSS output escaping sniff there is a check for a comment at the end of the line (like `// XSS OK`) which can be used to whitelist  a location. It would be nice to have this for the sanitized input sniff.

**Comment by westonruter** [comment]
> I did look for other tickets, and I found #228, but I don't see a ticket asking for a base method for getting EOL whitelisting comments. Maybe it hasn't been created yet?

Correct.
