### ISSUE TITLE
Defining custom rules 

### ISSUE THREAD

**Issue by jitendraharpalani58** [WordPress-Coding-Standards/WordPress-Coding-Standards#305]
I want to ignore certain rules, specifically Wordpress.Function.CallSignature. According to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards#user-content-using-custom-ruleset, i have defined `ruleset.xml`, but, it doesn't seem to work. 

Here is my directory structure after i install composer. 
![screen shot 2015-01-22 at 4 54 20 pm](https://cloud.githubusercontent.com/assets/7255301/5854787/68db1436-a257-11e4-85d5-64008d9d8249.png)

**Comment by GaryJones** [comment]
Your `ruleset.xml` should usually be in the root of your plugin / theme project directory.

What are the contents of your `ruleset.xml`?

**Comment by jitendraharpalani58** [comment]
i am using a very basic version of `ruleset.xml` as i just need to ignore one rule 

```
<?xml version="1.0"?>
<ruleset name="Fusion">
	<description>A custom set of rules to check for a WPized WordPress project</description>

	<rule ref="Squiz.PHP.CommentedOutCode"/>
	<rule ref="Squiz.WhiteSpace.SuperfluousWhitespace"/>
	<rule ref="Generic.CodeAnalysis.UnusedFunctionParameter"/>
	<rule ref="Generic.Commenting.Todo"/>
	<rule ref="Generic.ControlStructures.InlineControlStructure"/>

	<!--
	We may also want to to include all the rules in a standard
	-->
	<rule ref="WordPress">
		<!--
		We may want a middle ground though. The best way to do this is add the
		entire ruleset, then rule by rule, remove ones that don't suit a project. We
		can do this by running `phpcs` with the '-s' flag, to see the names of the
		different Sniffs, as their rules are broken. From here, we can opt to
		exclude problematic sniffs like so.
		-->

		<exclude name="WordPress.Functions.FunctionCallSignature" />
	</rule>
</ruleset>

```

I also tried moving my `ruleset.xml` to root of my theme based on your recommendation, but, it didn't work. 

I am running `phpcs --standard=WordPress functions.php `, do i need to use the path to my `ruleset.xml` instead of `--standard=WordPress`?

**Comment by JDGrimes** [comment]
> I am running phpcs --standard=WordPress functions.php, do i need to use the path to my ruleset.xml instead of --standard=WordPress?

Yes, that is the problem. Use `--standard=ruleset.xml` instead.

**Comment by jitendraharpalani58** [comment]
>Yes, that is the problem. Use `--standard=ruleset.xml` instead.

I tried running that, still getting error that `rulese.xml` not installed
```
vagrant@vip:/srv/www/wp-content/themes/vip/fusion-theme$ phpcs --standard=rulset.xml functions.php
Failed loading /usr/lib/php5/20121212/xdebug.so:  /usr/lib/php5/20121212/xdebug.so: cannot open shared object file: No such file or directory
ERROR: the "rulset.xml" coding standard is not installed. The installed coding standards are PSR2, Squiz, PSR1, Zend, MySource, PHPCS, PEAR and WordPress
```

**Comment by jrfnl** [comment]
What about if you fix the typo ? `ruleset.xml` not `rulset.xml`....

**Comment by jitendraharpalani58** [comment]
My bad.. it worked!!  :)

Thanks!!

Resolution is: `ruleset.xml` should be under root of the theme.
