### ISSUE TITLE
VIP: flag get_tag_link()

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#310]
When using the WordPress-VIP coding standard flag get_tag_link() as needing replacement by wpcom_vip_get_term_link().

**Comment by westonruter** [comment]
Cool, want to open a PR with the necessary change to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php ?

**Comment by paulschreiber** [comment]
Sure: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/311

**Comment by westonruter** [comment]
Thanks!

**Comment by GaryJones** [comment]
> When using the WordPress-VIP coding standard flag get_tag_link() as needing replacement by wpcom_vip_get_term_link().

@paulschreiber: Out of interest, what does the VIP function do differently?

**Comment by paulschreiber** [comment]
Caching. Same as pretty much all the other wpcom_vip_* functions.

More notes:
http://vip.wordpress.com/documentation/caching/uncached-functions/
