### ISSUE TITLE
Create sniff to flag missing PHPDoc comments

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#32]
All functions should include a PHPDoc comment block which indicate the parameters and return value, along with a description of what the function does.

Example.  Note: curly braces should not be used around type statement eg: `@param {array} $some_array`  These can not be parsed by PHPDocumenter.

    //Correct
	/**
	 * Sets the post thumbnail on the list table
	 *
	 * @param int $post_id
	 * @param string $size, The thumbnail size to use (optional)
	 * @return bool|string, post thumbnail if post has thumbnail, false if not
	 */
    function wpized_list_thumbnail( $post_id, $size='medium' ) {

Reported by @c3mdigital

**Comment by GaryJones** [comment]
Closing in favour of #241.
