### ISSUE TITLE
Flag wp_get_object_terms() as restricted by VIP

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#321]
https://vip.wordpress.com/documentation/caching/uncached-functions/

* wp_get_post_terms(), wp_get_post_categories(), wp_get_post_tags(), and wp_get_object_terms()
  * Use get_the_terms() along with wp_list_pluck to extract the IDs

**Comment by JDGrimes** [comment]
This was fixed in #491.
