### ISSUE TITLE
Add JDGrimes as a project collaborator

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#323]
No more needs to be said than https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commits/develop?author=JDGrimes

**Comment by westonruter** [comment]
Done. @JDGrimes you can now merge PRs, and open feature branches directly on this repo instead of on your fork if you wish.

**Comment by JDGrimes** [comment]
:smile: Thanks @westonruter!

**Comment by GaryJones** [comment]
+10000000000000.000000001
