### ISSUE TITLE
enqueued script error

### ISSUE THREAD

**Issue by Emetrop** [WordPress-Coding-Standards/WordPress-Coding-Standards#329]
I'm trying convert an old code to the WP standards and I stuck with registering scripts via wp_enqueue_script function.

In footer.php file I have code like this:

    

And phpcs gives me error output like this:
    ----------------------------------------------------------------------
    FOUND 1 ERROR AFFECTING 1 LINE
    ----------------------------------------------------------------------
     110 | ERROR | Scripts must be registered/enqueued via
         |       | wp_enqueue_script
    ----------------------------------------------------------------------

But I cannot just create a new .js file and write there the inner body of the script tag to my code via wp_enqueue_script because I need leave there that condition . How can I do it?

**Comment by JDGrimes** [comment]
There is no easy way to do it until WordPress 4.2 is released. See [WP#16024](https://core.trac.wordpress.org/ticket/16024 "Conditional Comments for JS").

**Comment by jrfnl** [comment]
Suggest closing this issue as WP 4.2 has been out for quite a while now.
