### ISSUE TITLE
false positive: vip_powered_wpcom() is flagged as needing escaping

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#336]
```
 50 | ERROR | Expected a sanitizing function (see Codex for 'Data
    |       | Validation'), but instead saw 'vip_powered_wpcom'
```

**Comment by westonruter** [comment]
@paulschreiber add to an exclusion list?

**Comment by paulschreiber** [comment]
In my project? Or can I add it to WPCS? If so, how?

**Comment by westonruter** [comment]
You could add it to [`WordPress_Sniffs_XSS_EscapeOutputSniff::$autoEscapedFunctions`](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/1efcfd5e4491483e40a412289b92dbf1bf8a26f5/WordPress/Sniffs/XSS/EscapeOutputSniff.php#L29).
