### ISSUE TITLE
XSS sniff: Add _doing_it_wrong() to list of output functions

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#340]
WordPress provides some error-reporting functions, like `_doing_it_wrong()`, which won't generate output by default. However, they do generate output when `WP_DEBUG` and `WP_DEBUG_DISPLAY` are on. In that case, passing un-escaped user input to these functions may result in XSS.

Of course, it is bad practice to enable error display on production servers. I'd like to hear any thoughts on whether escaping should be required here anyway.

FWIW, in the few instances in WordPress core where untrusted input is passed to `_doing_it_wrong()`, it is put through `esc_html()`.

Note that `_doing_it_wrong()` is just the scapegoat here, representative of a broader range of functions:

```
_deprecated_argument()
_deprecated_function()
_deprecated_file()
trigger_error()
user_error()
error_log()
debug_print_backtrace()
...
```

**Comment by GaryJones** [comment]
If core is doing it, then that alone is sufficient "prior art" to say that it should be included in WPCS, even if it's not explicitly mentioned in the WP Handbooks for PHP CS, since it's covered by the general best practices anyway.
