### ISSUE TITLE
Install: does not work if I have phpcs.phar installed

### ISSUE THREAD

**Issue by chestozo** [WordPress-Coding-Standards/WordPress-Coding-Standards#348]
If I have `phpcs` installed as `.phar` file like it is said here https://github.com/squizlabs/PHP_CodeSniffer#installation
```
curl -OL https://squizlabs.github.io/PHP_CodeSniffer/phpcs.phar
```
installing code style rules like so will not work
```
phpcs --config-set installed_paths /path/to/wpcs
```
I am getting some error messages about `phpcs.phar` file checksum errors.

**Comment by chestozo** [comment]
And everything works if I run `phpcs` as php script like so `php scripts/phpcs`.

**Comment by westonruter** [comment]
This sounds like something you show raise with the PHP_CodeSniffer project
itself.

**Comment by chestozo** [comment]
Thank you )
