### ISSUE TITLE
Add $_FILE to the list of superglobals that need to be validated/sanitized

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#354]
I noticed while working on #294 that `$_FILE` isn't included. It definitely should receive validation, and though the sanitization might be somewhat different it is still needed. (Actually, we might want to consider creating a similar sniff that requires files to be uploaded using WordPress-provided functions, to avoid arbitrary file upload.)

**Comment by westonruter** [comment]
:+1:
