### ISSUE TITLE
Inline control structures sniff can be passed with halfway effort, bug?

### ISSUE THREAD

**Issue by lkraav** [WordPress-Coding-Standards/WordPress-Coding-Standards#355]
Sniff detects this to be wrong

    if ( "condition" != $yoda ) return;

It appears, that I can pass the sniff with

    if ( "condition" != $yoda ) { return; }

I would've expected only multi-line control structure to pass

    if ( "condition" != $yoda ) {
        return;
    }

Bug or not? Documentation patch somewhere?

**Comment by JDGrimes** [comment]
Yeah, this doesn't match the standards. I think we need to add `Squiz.ControlStructures.ControlSignature` to the ruleset. I think that will fix #17 as well.
