### ISSUE TITLE
Travis export question

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#365]
Is https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/.travis.yml#L20 still needed? We don't seem to be using `PHPCS_GITHUB_SRC` anywhere?

**Comment by JDGrimes** [comment]
No. It was added in 696b21499a36fbacd916b74e48d80b5150b0e7ec, but not used after 04ef08bd325296126e8984e87e3ff2fc93b1e12b.
