### ISSUE TITLE
Integrate Sniffs with WP-CLI

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#37]
We could introduce a new WP-CLI subcommand called `lint` or `phpcs` which would apply the sniffs in this project to the WordPress install in the current scope.

I'm not sure of the best route to go as for integrating the sniffs into WP-CLI. Perhaps it would mean forking WP-CLI <https://github.com/wp-cli/wp-cli> and then adding this repo as a submodule dependency.

**Comment by GaryJones** [comment]
What's the status on this from the WP-CLI side? (I'm not familiar with WP-CLI)

**Comment by Rarst** [comment]
I am a little "why bother" on this. What does running it with wpcli does which is better than... just running it?

**Comment by GaryJones** [comment]
> I am a little "why bother" on this. What does running it with wpcli does which is better than... just running it?

That's a good point. If one has command-line access to run WP-CLI, then one could also use the command line to do `phpcs` too.

Might be some advantage to being able to have WP-CLI loop through each plugin and theme and trigger phpcs for each with any custom `phpcs.xml`? It's not really how many folks work though.

**Comment by danielbachhuber** [comment]
> What does running it with wpcli does which is better than... just running it?

I don't see much utility in a WP-CLI command for running `phpcs`.

**Comment by Rarst** [comment]
@westonruter do you have any additional thoughts on what merit of such command could be?

**Comment by westonruter** [comment]
No. I don't remember why I thought this was a good idea 😄
