### ISSUE TITLE
Unsupported operand types

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#372]
~~~
PHP Fatal error:  Unsupported operand types in .../WordPress/Sniff.php on line 436
~~~

Happened with PHP 5.4.38 and 5.6.8, when running PHPCS with WPCS on develop branch of [TGMPA](https://github.com/thomasgriffin/tgm-plugin-activation).

Call Stack:
1. {main}() .../phpcs/scripts/phpcs:0
2. PHP_CodeSniffer_CLI->runphpcs() .../phpcs/scripts/phpcs:25
3. PHP_CodeSniffer_CLI->process() .../phpcs/CodeSniffer/CLI.php:95
4. PHP_CodeSniffer->processFiles() .../phpcs/CodeSniffer/CLI.php:867
5. PHP_CodeSniffer->processFile() .../phpcs/CodeSniffer.php:619
6. PHP_CodeSniffer->_processFile() .../phpcs/CodeSniffer.php:1679
7. PHP_CodeSniffer_File->start() .../phpcs/CodeSniffer.php:1801
8. WordPress_Sniffs_CSRF_NonceVerificationSniff->process() .../phpcs/CodeSniffer/File.php:567
9. WordPress_Sniff->is_only_sanitized() .../wpcs/WordPress/Sniffs/CSRF/NonceVerificationSniff.php:119
10. WordPress_Sniff->is_sanitized() .../wpcs/WordPress/Sniff.php:343

**Comment by JDGrimes** [comment]
Can you give an example of code that causes this?

**Comment by JDGrimes** [comment]
Are you sure that is the whole call stack? It seems like there must be more after that.

**Comment by GaryJones** [comment]
Nope, that's the full lot:

![screenshot 2015-05-01 22 00 02](https://cloud.githubusercontent.com/assets/88371/7437199/7c5c4ad6-f04d-11e4-8c81-4c5bee6f570d.png)

**Comment by JDGrimes** [comment]
Ah, I missed the `line 436` at the top. That makes more sense. :smile:

**Comment by JDGrimes** [comment]
I see what the problem is, it is related to sanitization with `array_map()`.
