### ISSUE TITLE
Question: Escaping when string is HTML attributes and values string?

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#379]
The Genesis Framework has a `genesis_attr()` function which outputs ultimately outputs a string of HTML attribute and values. It is used like:

~~~php
printf( '<div %>', genesis_attr( 'some-context' ) );
~~~

That is currently flagged as `WordPress.XSS.EscapeOutput.OutputNotSanitized`.

Going on the assumption that this is NOT a false positive, how should the second arg be escaped?

**Comment by westonruter** [comment]
Add it to your project's PHPCS XML noting that `genesis_attr` is an `autoEscapedFunctions` function? Ref: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniffs/XSS/EscapeOutputSniff.php#L29

**Comment by GaryJones** [comment]
Excellent, thank you! I saw there was a customAutoEscapedFunctions property I could use that gets merged with the defaults. I had to set the property as `type="array"` too, but I'm no longer getting any error. Here is the phpcs.xml:

~~~xml
<?xml version="1.0"?>
<ruleset name="Utility Pro">
	<description>The code standard for Utility Pro is WordPress.</description>
	<file>.</file>
	<arg name="extensions" value="php"/>
	<exclude-pattern>assets/*</exclude-pattern>
	<exclude-pattern>node_modules/*</exclude-pattern>
	<exclude-pattern>dist/*</exclude-pattern>
	<exclude-pattern>includes/vendors/*</exclude-pattern>
	<exclude-pattern>js/*</exclude-pattern>
	<exclude-pattern>xml/*</exclude-pattern>
	<arg name="report" value="full"/>
	<arg name="report" value="summary"/>
	<arg name="report" value="source"/>
	<arg value="sp"/>
	<rule ref="WordPress.XSS.EscapeOutput">
		<properties>
		   <property type="array" name="customAutoEscapedFunctions" value="genesis_attr"/>
		</properties>
	</rule>
	<rule ref="WordPress">
		<!-- <exclude name="WordPress.VIP"/> -->
		<exclude name="WordPress.Files.FileName.UnderscoresNotAllowed"/>
		<exclude name="Squiz.Commenting.FileComment.DuplicateAuthorTag"/>
	</rule>
</ruleset>
~~~

**Comment by JDGrimes** [comment]
You can also use `customSanitizingFunctions` property the same way. At present they have the same effect, but it's possible that could change in the future.

**Comment by GaryJones** [comment]
Yep, I saw that once pointed in the right direction - good stuff. In this case, there's no sanitization going on though - it's just escaped attributes values and their attributes being concatenated into a string.

**Comment by GaryJones** [comment]
I thought I had this worked out, but I can't see to get it working for a different project:

```xml
<?xml version="1.0"?>
<ruleset name="...">
    <file>.</file>
    <rule ref="WordPress.XSS.EscapeOutput">
        <properties>
            <property type="array" name="customAutoEscapedFunctions" value="oec_icon"/>
        </properties>
    </rule>
    <rule ref="WordPress">
        <exclude name="WordPress.VIP"/>
    </rule>
</ruleset>
```

Reports still flag `echo oec_icon(...)`.

I've got `var_dump($this->customAutoEscapedFunctions);` inside the sniff `process()`, and it displays an empty array.

![screenshot 2016-03-27 12 05 42](https://cloud.githubusercontent.com/assets/88371/14065107/4ad630be-f414-11e5-9094-6dec4971b355.png)

I've tried changing the order of the rules in my ruleset.xml in case `ref="WordPress" was somehow overwriting the specific XSS sniff. I've tried nesting the rules. I've tried removing `type="array"`. I've tried excluding the XSS sniff inside `WordPress` rule.

I'm using up to date `develop` branch.

Second question - if I need to add in multiple functions, are they comma separated?

```xml
<property type="array" name="customAutoEscapedFunctions" value="oec_icon, genesis_attr"/>
```

**Comment by JDGrimes** [comment]
> Second question - if I need to add in multiple functions, are they comma separated?

Yes.

As for the first question, I've just tested this locally and it is working for me. So I think that maybe you are running `phpcs` without using the custom ruleset file. Add `--standard=/path/to/ruleset.xml` to the command and see if it works then.

**Comment by GaryJones** [comment]
Bizarre. I did test with explicitly giving a standard, but it does now indeed work. The `ruleset.xml` is in my plugin root, so I'm not sure why it's not picking it up. I've now tried with it called `phpcs.xml` as well, and now `phpcs path/to/tested/file.php` now works as it should.

PEBCAK.
