### ISSUE TITLE
Duplicate implementation of spacing detection in control structures

### ISSUE THREAD

**Issue by Rarst** [WordPress-Coding-Standards/WordPress-Coding-Standards#385]
WPCS currently seems to have spacing in control structure implemented as forked `WordPress.WhiteSpace.ControlStructureSpacing` sniff.

PHP CS now got `Squiz.ControlStructures` sniffs which can do this.

I think it would make sense to look into getting rid of the forked sniff (whose maintenance is on us) in favor of upstream implementation?

**Comment by JDGrimes** [comment]
Yes, we should look into this, and also any other sniffs that have upstream duplicates.

Previously: #236, #237, #244, #251, #258.

**Comment by JDGrimes** [comment]
Fixed in #417.
