### ISSUE TITLE
Add identifier to all errors and warnings in custom sniffs

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#386]
Including a unique identifier in all errors and warnings in our custom sniffs allows developers to target them to exclude them from reports without disabling the whole sniff.

**Comment by JDGrimes** [comment]
Previously: #297 

So most of the errors/warnings should have an identifier.

**Comment by JDGrimes** [comment]
Note that this will be required in PHPCS 3.0 (see https://github.com/squizlabs/PHP_CodeSniffer/commit/c587b2744535b195d3249c8c74ace2c2d18cad0f).

**Comment by JDGrimes** [comment]
One sniff that doesn't have a uid for each error is `VIP.DirectDatabaseQuery`.
