### ISSUE TITLE
Add support for automatic error fixing

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#388]
We should add support for automatic error fixing to all of the sniffs where appropriate. See https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/223#issuecomment-103151426.

**Comment by GaryJones** [comment]
Unless you fancy making and maintaining a checklist of all the sniffs that could have automatic fixing added, would it be better to close this in favour of more specific Issues / PRs (i.e. "Add automatic fixing to WordPress.xxx.yyy")?

**Comment by jrfnl** [comment]
AFAICS all whitespace related sniffs in WPCS are currently auto-fixable and there are a few isolated other errors which can be auto-fixed.

I concur that if there is any other check still remaining which should be auto-fixable, that it would be better to open a separate issue for this.
