### ISSUE TITLE
Integrate checks for JavaScript Coding Standards

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#39]
On 21 March 2013, Tom McFarlin [posted](http://tommcfarlin.com/wordpress-javascript-coding-standards/) that he contributed the first ever WordPress JavaScript Coding Standards:

> Anyway, one of the things about the WordPress Coding Standards that’s always seemed incomplete to me is how little it focused on JavaScript. It provides guides for PHP, for HTML, and it even has a stub for CSS, but there’s nothing in the Codex about JavaScript.

> For the past few months, I’ve been working on exactly that. Today, I contributed to the WordPress Coding Standards by introducing the [WordPress JavaScript Coding Standards](http://codex.wordpress.org/WordPress_Coding_Standards#JavaScript).

The JavaScript Coding Standards have been moved over to the Core Contributor Handbook: http://make.wordpress.org/core/handbook/coding-standards/javascript/

We should look at creating sniffs specifically for enforcing the JavaScript rules.

**Comment by GaryJones** [comment]
While PHPCS can check JS, I think JSCS is going to be a better tool for the job.
