### ISSUE TITLE
Standardize whitelisting by using sniff name

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#393]
We have a pretty ad-hoc system of whitelisting certain usages from being flagged by PHPCS (`xss ok`, `input var ok`, `db call ok`, etc), and it's something that has to be built into each sniff to support it.

What if we just used the sniff name and named error instead?

For instance:

``` php
$q = new WP_Query( array(
    'posts_per_page' => 200, // wpcs:ok WordPress.VIP.SlowDBQuery.slow_db_query 
) );
```

This draws inspiration from JSCS and its directives like:

``` js
//jscs:disable requireCamelCaseOrUpperCaseIdentifiers
```

This could then be worked into the new `WordPress_Sniff` base class.

It would be better, however, if this was part of PHP_CodeSniffer core. I've opened a ticket for that: https://github.com/squizlabs/PHP_CodeSniffer/issues/604

Also relates to #228.

---

TIL `// @codingStandardsIgnoreLine`

**Comment by GaryJones** [comment]
+1 for something more logical, even if not so guessable.

**Comment by GaryJones** [comment]
A couple of years has since passed, and as such, considerably more whitelisting comments will have been added to code.

Is this change to whitelisting format still desired?

**Comment by JDGrimes** [comment]
I think this is something that PHPCS itself should fix, and the upstream issue is now marked as high priority and milestoned to 3.2.0, so it appears that may happen before long. So I don't think that we need to pursue this in WPCS. 

I think there is also something to be said for the brevity of our current whitelist comments. 😄

**Comment by JDGrimes** [comment]
Since https://github.com/squizlabs/PHP_CodeSniffer/issues/604 has now been closed, I'm going to close this issue. If anybody else still sees a need for this, feel free to reopen.

**Comment by JDGrimes** [comment]
Good idea, I've added a brief note there. If anyone else wants to add more info on that there, feel free.

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors
