### ISSUE TITLE
Add sniff to require 3rd argument ($strict) to in_array()

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#399]
VIP has cautioned against some code using `in_array()` that lacked the 3rd `$strict` parameter. In this way, it is like #242, where we added a sniff for strict comparisons.

**Comment by GaryJones** [comment]
Like #242, it should probably be added to `WordPress-Extra` too.

**Comment by paulschreiber** [comment]
I just got the same note from VIP. This would be very helpful.

**Comment by westonruter** [comment]
See #490.
