### ISSUE TITLE
Check for 'orderby'   => 'rand',

### ISSUE THREAD

**Issue by nicoladj77** [WordPress-Coding-Standards/WordPress-Coding-Standards#409]
Recently i was doing an audit and found this code

	// Setup base query
	$args = array(
		'post_type'      => 'post',
		'post_status'    => 'publish',
		'post__not_in'   => array( $post->ID ),
		'posts_per_page' => absint( $limit ),
		'orderby'        => 'rand',
		'tax_query'      => array(),
		'date_query'     => array(
			'after'       => '2 years ago',
		),
	);
	$related = get_posts( $args );

I remember that ORDER BY RAND() was [bad for mysql](http://stackoverflow.com/questions/1117761/sql-query-to-return-rows-in-random-order) should a check for this be added?

**Comment by westonruter** [comment]
This is now a [blocker for WordPress.com VIP](https://vip.wordpress.com/documentation/code-review-what-we-look-for/#order-by-rand):

> MySQL queries that use ORDER BY RAND() can be pretty challenging and slow on large datasets. You can either retrieve 100 posts and pick one at random or use this helper function: https://vip.wordpress.com/functions/vip_get_random_posts/
