### ISSUE TITLE
Twig files should be ignored

### ISSUE THREAD

**Issue by insprintorob** [WordPress-Coding-Standards/WordPress-Coding-Standards#418]
Twig files should be ignored, because scanning them will trigger phpcs errors.

**Comment by insprintorob** [comment]
Pull request here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/419

**Comment by westonruter** [comment]
@insprintorob How are you normally invoking PHPCS that it would result in Twig files being processed in the first place? What's keeping it from processing HTML files or TXT files, for instance?

**Comment by insprintorob** [comment]
I actually wrote a script that runs phpcs with the right switches to
exclude anything besides php files, so I normally run that.

I just thought this might be useful for developers who are setting up the
WordPress coding standards for the first time, one less step they would
need to take.
