### ISSUE TITLE
esc_url_raw not listed as sanitizing function

### ISSUE THREAD

**Issue by jjeaton** [WordPress-Coding-Standards/WordPress-Coding-Standards#420]
According to the [Codex](http://codex.wordpress.org/Data_Validation#URLs), `esc_url_raw` should be used for sanitizing URLs, however the following fails WPCS:

```
$referer = esc_url_raw( $_SERVER['HTTP_REFERER'] );
```

*Detected usage of a non-sanitized input variable: $_SERVER*

Should this be added to the list of sanitizing functions? There isn't a `sanitize_url`, but there was, and it's now in deprecated.php and calls `esc_url_raw`. If this isn't the right function, if you could point me in the right direction as to which function should be used for sanitizing URLs, I'd greatly appreciate it! :smile:

**Comment by JDGrimes** [comment]
Yes, I think you're right.

**Comment by jjeaton** [comment]
Awesome, thanks!
