### ISSUE TITLE
Unexpected "Expected next thing to be a escaping function" error

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#421]
When I run the WordPress ruleset over a function with ternary functions nested in an escape call, I get an unexpected "Expected next thing to be a escaping function" error.

```
phpcs -s --standard=WordPress ~/test.php
```

Output:
```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 6 | ERROR | Expected next thing to be a escaping function, not '$r'
   |       | (WordPress.XSS.EscapeOutput.OutputNotEscaped)
----------------------------------------------------------------------
```

Code:
```php
<?php
	echo '<div class="'
		. esc_attr( 'baz-'
			. $r
			. ( $r === $active_round ? ' foo' : '' )
			. ( $r < $active_round ? ' bar' : '' )
		)
		. '">';
?>
```

If you remove line 6 (`. ( $r < $active_round ? ' bar' : '' )`), the error goes away.

**Comment by paulschreiber** [comment]
Previously filed as https://github.com/squizlabs/PHP_CodeSniffer/issues/673.

**Comment by GaryJones** [comment]
Confirming the reported error.

Certainly not to be dismissive of this issue, but the example given is not the easiest code to read.

~~~php
<?php
$class = sanitize_html_class( 'baz-' . $r );

if ( $r === $active_round ) {
	$class .= ' foo';
} elseif ( $r < $active_round ) {
	$class .= ' bar';
}

?>
<div class="<?php echo esc_attr( $class ); ?>">
~~~

^ That would be cleaner to read for me - logic separated from view, sanitizing of unknown class, easier to refactor generating the value of `$class` into it's own function, etc. and it doesn't throw any PHPCS errors or warnings.

**Comment by JDGrimes** [comment]
The sniff is supposed to handle ternary conditions (see #281), and it seems to be handling the first one correctly, so I'll have to dig into the code to find out why it isn't handling the second one.

**Comment by paulschreiber** [comment]
@GaryJones Don't worry, I didn't write the code. (I did clean up some of the gnarlier bits.) I didn't want to let this bug slip away, though.
