### ISSUE TITLE
Missing wp_unslash() before sanitization called on intval()

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#426]
This code:
```
get_permalink( intval( $_POST['id'] ) );
```

generates a "Missing wp_unslash() before sanitization" error.

I can see that making sense before `sanitize_text_field()`, but it seems unnecessary before `intval()`.

**Comment by westonruter** [comment]
Unnecessary, true. But I think it is also good to make such a rule global to avoid having to second guess. 

Nevertheless, it shouldn't be too hard to add exceptions to the `wp_unslash` requirement when the input var is being passed through `intval()` and `boolval()`.

**Comment by JDGrimes** [comment]
We already do this for `absint()` and some other similar functions. I've opened #427, which adds these functions to that list.
