### ISSUE TITLE
do_shortcode() flagged as needing escaping

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#428]
`do_shortcode()` is currently flagged as needing escaping.

I discussed this with VIP support (#44195). David, after conferring with another team member, said that it's unnecessary, as we do the escaping where the HTML is emitted (in the shortcode's code).

**Comment by JDGrimes** [comment]
Previously: #167.

There I argued that we shouldn't do this, but that I'd change my mind if VIP said it was OK. So, I'm fine with it (though I still don't like `do_shortcode()` itself, but that's a different story :smile: ).
