### ISSUE TITLE
No space after opening parenthesis is probihited

### ISSUE THREAD

**Issue by fbm-static** [WordPress-Coding-Standards/WordPress-Coding-Standards#431]
I'm not sure why it's happening but it's showing this error on the `use` statements:

```
<?php

namespace Foo;

use Foo\Admin\Admin;
use Foo\Admin\User;
use Foo\Admin\Work;
```

**Comment by GaryJones** [comment]
There was a recent commit that looked at `use` for closures, so it looks like it's catching this as well. cc @JDGrimes

**Comment by fbm-static** [comment]
I'm using the develop branch :D haha

**Comment by JDGrimes** [comment]
The offending commit is 7d192722e6a6c3b8a3f7d9b5216f0582685de8af. I'll try to fix this later today.
