### ISSUE TITLE
sprintf() parameters aren't checked for safety

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#443]
The following code is unsafe, but does not cause an `Expected a sanitizing function...` warning in WPCS. I presume it's being tripped up by the presence of the `esc_` function which escapes the formatted string _before_ it goes into `printf()` for its tokens to be replaced.

```php
$foo = $_GET['foo'];
printf( esc_html__( 'foo %s' ), $foo );
```

**Comment by JDGrimes** [comment]
I am not able to reproduce with that example code when run against `develop` (which shouldn't be any different than if run against the latest release). Can you please make sure that you are up to date, and if so, double check that you can reproduce it with your example? Thanks!

**Comment by johnbillion** [comment]
Looks like I had an old version of wpcs sitting around. Ugh.
