### ISSUE TITLE
`WPCS: sanitization ok` comment not working

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#445]
The following code triggers an `Expecting next thing to be an escaping function` warning. Does the `sanitization ok` comment not cover escaping too? If not, is there an equivalent comment that can be used to silence warnings about escaping?

```php
echo implode( ', ', $out ); // WPCS: sanitization ok.
```

Running up-to-date `develop` branch.

**Comment by JDGrimes** [comment]
Sanitization and escaping are (sort of) opposites, and are covered by separate sniffs. The comment for the escaping sniff is:

```php
echo implode( ', ', $out ); // WPCS: XSS ok.
```
