### ISSUE TITLE
Whitelist comments don't work inside sprintf()

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#447]
Given the following code, the first whitelist comment silences the escaping warning, but the second doesn't.

```php
echo $hello; // WPCS: XSS ok.
printf( '%s',
	$hello // WPCS: XSS ok.
);
```

**Comment by JDGrimes** [comment]
Whitelist comments only work at the end of a statement, to ignore the whole statement. In other words, they need to come after the semicolon.

```php
printf( '%s',
    $hello
); // WPCS: XSS ok.
```

We could change this, but it would make processing slower.

**Comment by johnbillion** [comment]
Works for me. I've added an example to the wiki.

**Comment by johnbillion** [comment]
There appears to have been a regression here. The below code triggers an escaping function warning regardless of where the silencing comment goes.

```php
printf(
	'<b>%s</b>',
	$var // WPCS: XSS ok.
); // WPCS: XSS ok.
```

Using phpcs 2.5.1, wpcs 0.9.0, and the VIP ruleset.

**Comment by jrfnl** [comment]
@johnbillion With multi-line functions, I've noticed it only works if the whitelisting comment is the last thing on the line on which the function starts (at this moment).

So the below should work in my experience:
```php
printf( // WPCS: XSS ok.
    '<b>%s</b>',
    $var 
);
```

**Comment by johnbillion** [comment]
Thanks @jrfnl, the wiki has been updated too.
