### ISSUE TITLE
Detected usage of a non-sanitized input variable: when esc_url() is used

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#453]
I get a "Detected usage of a non-sanitized input variable:" error on this line:

```php
$featured_embed_url = esc_url( wp_unslash( $_POST['foo'] ) ); // input var okay
```

Does esc_url() count as sanitizing?

**Comment by JDGrimes** [comment]
No, `esc_url()` is not a sanitizing function, it is an escaping function. There used to be a `sanitize_url()`, but it has been deprecated in favor of `esc_url_raw()`. I think that `esc_url_raw()` would be the correct function to use to sanitize a URL for the database/redirect/other use, while `esc_url()` would be used to escape it for display. And in fact, `esc_url_raw()` is already in our list of sanitizing functions, so if you change this to `esc_url_raw()` the error should go away. :smile:

**Comment by paulschreiber** [comment]
That fixes it. Thanks!
