### ISSUE TITLE
VIP: Check get_current_blog_id() in pre_option_* filters

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#475]
When adding a `pre_option_*` filter, we should try to check if `get_current_blog_id()` is being referenced.

> Since the theme is being loaded even in non-standard situations (api, jobs system) you should always check if current blog_id matches the real blog_id of the site running the theme. The pre_option_ hooks you should be careful with are:
> - pre_option_blogname
> - pre_option_blogurl
> - pre_option_post_count

See https://vip.wordpress.com/documentation/code-review-what-we-look-for/#pre_option_

**Comment by GaryJones** [comment]
Closing here, since it is not related to anything currently in WPCS, but I've made a note of it for VIPCS.
