### ISSUE TITLE
Potential False Positive on Catching Exceptions

### ISSUE THREAD

**Issue by drmmr763** [WordPress-Coding-Standards/WordPress-Coding-Standards#476]
Hi All

Thanks for all the work on this project. It's been very useful to get my code all up to sniff ;)

I'm getting what I think might be a potential false positive. I have the following try / catch code block:

```php
// View variables.
try {
     $jid   = get_query_var( 'jid', 0 );
     $job = $this->jobsApp->getJob( $jid );

     $title = $this->getJobTitle( $job );
} catch ( \ErrorException $e ) {
     // Log error data.
     echo $e->getMessage();
     exit();
}
```

PHPCS is complaining that I'm echoing directly without escaping:

`Expected next thing to be an escaping function (see Codex for 'Data Validation'), not '$e'`

I guess that's a reasonable requirement, but considering its a thrown exception from further up the chain I don't see why escaping it would be necessary. I can rid myself of the error by using the escape function:

```php
echo esc_textarea( $e->getMessage() );
```

And I'm sure I could whitelist it as well. I don't know if it matters much, I'm fine with using the escape function, it won't hurt anything. But just incase anyone else agrees with me this should be allowed I figured I'd mention it. Any thoughts?

**Comment by JDGrimes** [comment]
> I guess that's a reasonable requirement, but considering its a thrown exception from further up the chain I don't see why escaping it would be necessary.

What if, up the chain, was this:

```php
throw new Exception( 'Unknown value: ' . $_POST['var'] );
```

Oops, now we have the potential for XSS.

By looking at this code, I have no way of knowing whether it is safe:

```php
     echo $e->getMessage();
```

_You_ have no way of knowing whether it is safe, and WPCS has no way of knowing whether it is safe.

However, we can all agree that this is safe, without any knowledge of what happened up the chain:

```php
     echo esc_html( $e->getMessage() );
```

And even WPCS is smart enough to figure it out.

That is the basic principle of late escaping: make no assumptions about whether the data is safe already, just escape it at the last possible moment.

This could be a false positive (its possible that everything up the chain is safe), but ignoring it is just as likely to result in some false negatives.

**Comment by drmmr763** [comment]
Ah, you're right. Thanks for the example, that explains the reasoning and issue perfectly.
