### ISSUE TITLE
How to sanitize $_FILES super global?

### ISSUE THREAD

**Issue by jjeaton** [WordPress-Coding-Standards/WordPress-Coding-Standards#482]
Is there a way to sanitize the $_FILES array or is whitelisting my only option?

```
if ( ! empty( $_FILES['avatar']['name'] ) ) {
    $avatar = wp_handle_upload(
		wp_unslash( $_FILES['avatar'] ),
		array(
			'mimes'                    => $this->mime_types,
			'test_form'                => false,
			'unique_filename_callback' => array( $this, 'unique_filename_callback' ),
		)
    );
}
```

Gives:

```
Detected usage of a non-sanitized input variable: $_FILES
```

**Comment by JDGrimes** [comment]
I think that `wp_handle_upload()` and `wp_handle_sideload()` should be added to the list of sanitizing functions. They both use `_wp_handle_upload()`, which sanitizes the file name, type, and extension.

**Comment by JDGrimes** [comment]
I should note that some filters and error functions could be called before the sanitization occurs, however.
