### ISSUE TITLE
Multi-line function call

### ISSUE THREAD

**Issue by evgenykireev** [WordPress-Coding-Standards/WordPress-Coding-Standards#496]
Hi guys,

after phpcs updated to 2.4.0 (specifically after this commit https://github.com/squizlabs/PHP_CodeSniffer/commit/7ae3c57f6083a09d089d6e3dc710874946369598) multi-line function calls in VIP return a phpcs error "Multi-line function call not indented correctly"

Example of test.php

```
print_r( array(
[tab]'parent' => array(
[tab][tab]'key' => 'value',
[tab]),
) );
```

then run 

```
$ phpcs --standard="WordPress-VIP" test.php

FILE: test.php
FOUND 1 ERROR AFFECTING 1 LINE

 4 | ERROR | [x] Multi-line function call not indented correctly;  |       |     expected 4 spaces but found 8
```

The same code works fine agains PEAR standards, so I guess some of WordPress-VIP phpcs code clash with the recent changes.

**Comment by westonruter** [comment]
@evgenykireev hi :)

The PHP_CodeSniffer maintainer responded the commit comments:

> This commit is over 2.5 years old and the code was in every 2.x version, not just 2.4.0. Are you sure this is the right commit? If so, what error are you actually reporting?

**Comment by JDGrimes** [comment]
Maybe it is related to https://github.com/squizlabs/PHP_CodeSniffer/issues/721?

**Comment by evgenykireev** [comment]
@westonruter It might relate to some other changes, but I noticed that the code above do not return any errors when run on phpcs 2.3 and return PEAR.Functions.FunctionCallSignature error with phpcs 2.4. 

@JDGrimes yes, it looks like a similar issue, but I only have errors when using WordPress-VIP standards and we do not put commas  in front in function calls.

**Comment by jrfnl** [comment]
@evgenykireev Considering there have been a lot of changes to WPCS (and PHPCS) over the last year, I've run some test on how this snippet is now handled.

The error you mention is no longer thrown and auto-fixing the snippet would result in:
```php
print_r(
	array(
		'parent' => array(
			'key' => 'value',
		),
	)
);
```

Is this ok for you ? Can we close this issue ?

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and we can reopen the issue.

**Comment by aubreypwd** [comment]
I get this using:

```php
	return array_merge( $array, array(
		'one,
		'two',
	) );
```

![](http://aubrey.pw/d/2018/Q4QRGWSOk6.png)

```
./wp-content ⑂ feaure/search-wp $ phpcs --version
PHP_CodeSniffer version 3.4.0 (stable) by Squiz (http://www.squiz.net)
ph
./wp-content ⑂ feaure/search-wp ++ $ php --version
PHP 7.1.23 (cli) (built: Oct 11 2018 16:19:26) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.23, Copyright (c) 1999-2018, by Zend Technologies
```

This is using `1.2.1` of WPCS.

**Comment by jrfnl** [comment]
@aubreypwd This is a very old closed issue, so you may want to open a new issue. Also, your comment doesn't contain a question, so what are you trying to say ?

The errors you show are exactly as expected and should be fixed. See #1330.

Both of the below are ways to write this code which _will_ pass the CS check:
```php
	// This would pass WPCS.
	return array_merge( $array, array( 'one', 'two' ) );

	// This would pass WPCS too.
	$second_array = array(
		'one',
		'two',
	);
	return array_merge( $array, $second_array );

```
