### ISSUE TITLE
Require strict=true for array_search()

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#503]
Require that `array_search()`'s third parameter, strict, be true as is done for `in_array()`.

**Comment by JDGrimes** [comment]
Also the third parameter of [`array_keys()`](https://secure.php.net/manual/en/function.array-keys.php) (when the second parameter is given).

**Comment by jrfnl** [comment]
Implemented in #624
