### ISSUE TITLE
Missing sniff in project.ruleset.xml.example breaks PHPCS

### ISSUE THREAD

**Issue by lgaechter** [WordPress-Coding-Standards/WordPress-Coding-Standards#505]
When I use the example ruleset (`project.ruleset.xml.example`) from the repository I get the following error:

`Fatal error: Uncaught exception 'PHP_CodeSniffer_Exception' with message 'Referenced sniff "WordPress.Functions.FunctionCallSignature" does not exist' in /Users/lgaechter/.composer/vendor/squizlabs/php_codesniffer/CodeSniffer.php:1122`

I’m completely new to PHPCS’s rulesets, but changing

```xml
<exclude name="WordPress.Functions.FunctionCallSignature" />
```

to

```xml
<exclude name="PEAR.Functions.FunctionCallSignature" />
```

solved it for me. It guess since it was deleted in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/eb3cc6c59d4991d3e5e78c4c020936ff1c66214b?diff=unified#diff-6af8d9fa23796c0c8792547a27017150L48 the exclude can’t be found in the example ruleset anymore?

Now I’m not sure whether excluding `PEAR.Functions.FunctionCallSignature` inside `<rule ref="WordPress-Core">` is good practice or whether it should be excluded in another rule?

**Comment by jrfnl** [comment]
FYI: I've seen similar issues in the past when I was using an older PHPCS version. Since upgrading to the latest PEAR version, I haven't seen this type of error anymore.

Not sure what version of PHPCS you are on, but it may help.

**Comment by JDGrimes** [comment]
> Now I’m not sure whether excluding PEAR.Functions.FunctionCallSignature inside <rule ref="WordPress-Core"> is good practice or whether it should be excluded in another rule?

I think it really doesn't matter either way, but I'm actually not entire sure.
