### ISSUE TITLE
Add whitelisting comment for NonEnqueuedScript

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#516]
I have some PHP code with an embedded dynamic JavaScript block:

```
<script src="<?php echo esc_url( self::LOADER_URL ); ?>"></script>
```

It results in this error:

```
----------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 130 | ERROR | Scripts must be registered/enqueued via
     |       | wp_enqueue_script
     |       | (WordPress.WP.EnqueuedResources.NonEnqueuedScript)
----------------------------------------------------------------------
```

I'd like to be able to whitelist that line.

**Comment by jrfnl** [comment]
Just out of curiousity: why wouldn't you use `wp_enqueue_script()` for that anyway ? It looks like just the url is dynamic. If that's the case and the url is not available 'early', you can still use `wp_enqueue_script()` and set the first argument to `true` to load the js file in the footer of the HTML page.

**Comment by paulschreiber** [comment]
I tried that, and it didn't work. The reason is that this particular `<script>` tag goes inside TinyMCE's `iframe` (along with some other JS).

**Comment by jrfnl** [comment]
@paulschreiber Ah! Then I understand. I'm not sure if there is a way to enqueue for the TinyMCE frame.. Hmm.. good question.

**Comment by grappler** [comment]
@paulschreiber Would the `wp_enqueue_editor` hook work for you?

Related to https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/393

**Comment by paulschreiber** [comment]
* My code part of a larger block of JavaScript (the rest is allowed)
* As I understand it, `wp_enqueue_editor` won't let me add scripts to enqueue.
* What I needed is a parallel function to `add_editor_style`— `add_editor_style`. Filed [core ticket 39423](https://core.trac.wordpress.org/ticket/39423).

**Comment by jrfnl** [comment]
As PHPCS itself now offers modular ignore comments since [PHPCS 3.2.0](https://github.com/squizlabs/PHP_CodeSniffer/releases/tag/3.2.0) and the WPCS native whitelist comments have been deprecated since WPCS 2.0.0, I'm going to close this issue.
