### ISSUE TITLE
Atom Linter Configuration

### ISSUE THREAD

**Issue by corysimmons** [WordPress-Coding-Standards/WordPress-Coding-Standards#518]
Anyone happen to know if there is an Atom plugin for this? I couldn't find one.

Too busy/lazy to make one myself, but I know a lot of people would love it if one of you heroes wants to undertake such a journey. :guardsman:

**Comment by corysimmons** [comment]
Apparently https://atom.io/packages/linter-phpcs exists. Would you mind adding some instructions to the README for how to make it work with WP Coding Standards?

**Comment by JDGrimes** [comment]
If you've installed WPCS properly (so that the config path is registered with PHPCS), then you should be able to just specify `WordPress` (or `WordPress-Core` or `WordPress-VIP`, etc.) as the standard name.

**Comment by corysimmons** [comment]
Thanks. Would you mind testing this out and adding to README for future WPCS Atom devs?

**Comment by GaryJones** [comment]
If none of us here use Atom, then having someone who does (presumably you) write an initial pull request with the required steps, would make far more sense ;-)

**Comment by corysimmons** [comment]
But I'm llaaaaazzzzy :(

**Comment by corysimmons** [comment]
Alright, done. =)
