### ISSUE TITLE
1.0.0?

### ISSUE THREAD

**Issue by JDGrimes** [WordPress-Coding-Standards/WordPress-Coding-Standards#519]
Since I just released 0.9.0, I guess it is a good time to decide whether the next version should be 1.0.0 or 0.10.0. It really doesn't matter to me. Any thoughts?

**Comment by westonruter** [comment]
I guess the question is whether or not we consider the project to ever come to a point where it would not be backwards-compatible. If so, then a major version break would make sense. If we feel that in its current state the project is stable and a foundation to build upon, declaring a 1.0.0 would communicate that we feel it is a mature project. But then I should think that we never arrive at a 2.0.0, but just keep bumping the minor version each month, so in a couple years we could have 1.24.0

**Comment by JDGrimes** [comment]
There will definitely be times where we have to break back compat, just because PHPCS itself will. When PHPCS 3.0 is released, for example, we'll need to release a new version of WPCS that will not be compatible with PHPCS 2.0.

Other than that, we probably will have little need to ever break back-compat.

So maybe we wait until PHPCS 3.0 comes out and then decide if we want to release a 1.0 then? Or we could release a 1.0 now and release a 2.0 then, if we think that WPCS is mature.

**Comment by JDGrimes** [comment]
There are two different things to consider in terms of compatibility here: the code itself (for people that are creating custom child sniffs) and the configuration. PHPCS 3.0 will break code back-compat, but not necessary configuration.

**Comment by GaryJones** [comment]
I'd vote for 0.10.0. 

1. Once you move to 1.0.0, you can't go back. 
2. There are big areas of WP PHP Inline Documentation standards that we don't cover (or claim to cover), so a 1.0 would seem presumptuous in that regard.
3. Until the big holes in the WP standards have been unambiguously filled, I wouldn't want folks to think that we're the canonical authority on all aspects of how all WP code should be written, just because we're 1.0.

**Comment by westonruter** [comment]
> I'd vote for 0.10.0.

:+1: Great arguments.

**Comment by JDGrimes** [comment]
:+1: 0.10.0 it is.
