### ISSUE TITLE
Provide facility to ignore reporting on lines already committed

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#52]
In order to be really useful, it should be possible to only report errors and warnings on lines that have been touched, and ignore the lines that have already been there. This is key for use with Core development.

A wrapper script could be provided which invokes phpcs, but which filters out lines from the report that do not correspond with uncommitted changes.

**Comment by GaryJones** [comment]
https://github.com/xwp/PHP_CodeSniffer/pull/1 was closed in favour of https://github.com/xwp/PHP_CodeSniffer/pull/5.

**Comment by westonruter** [comment]
I'm going to close this because a solution has been developed which is not specific to PHPCS but can also restrict the scope of checks to JSHint and JSCS, by filtering the output of the generated reports: https://github.com/xwp/wp-dev-lib#limiting-scope-of-checks
