### ISSUE TITLE
Does WPCS do php -l as well?

### ISSUE THREAD

**Issue by corysimmons** [WordPress-Coding-Standards/WordPress-Coding-Standards#522]
Just curious if it will catch broken PHP as well.

**Comment by JDGrimes** [comment]
No. PHPCS doesn't explicitly check for syntax errors. There are times when a sniff may detect some tokens that it thinks are invalid, and sometimes the sniff will flag these with an error. But it doesn't intentionally run a syntax check. That's what `php -l` is for. :smile: 

https://github.com/squizlabs/PHP_CodeSniffer/wiki/FAQ#does-php_codesniffer-parse-my-code-to-ensure-it-will-execute

**Comment by westonruter** [comment]
:+1: I run `php -l` before PHPCS as well: https://github.com/xwp/wp-dev-lib/blob/82206f2ebf92fbf200809729bf1e638e34415abc/check-diff.sh#L613-L634

**Comment by corysimmons** [comment]
Thanks. Out of curiosity, might this be a feature worth considering? Seems like the #1 rule for WPCS should be "Make sure code is valid". :)

**Comment by westonruter** [comment]
Yes, but this would be an issue to introduce upstream in the PHPCS project itself: https://github.com/squizlabs/PHP_CodeSniffer

Nevertheless, since the project specifically calls out the use of `php -l`, I doubt it would be integrated.

**Comment by JDGrimes** [comment]
> Out of curiosity, might this be a feature worth considering?

It really isn't something that WPCS can do efficiently, because PHPCS doesn't actually parse/execute the code. It would be a lot of work to make a hammer do the job of a screw driver—when we already have a screw driver (`php -l`) that will do the job just fine.

WPCS is just one tool in your arsenal. The wp-dev-lib repo that @westonruter is a great example of how you can use it along with many others to run a variety of different types of checks on your code. Syntax checking is one check, coding standards is another.

**Comment by JDGrimes** [comment]
> Nevertheless, since the project specifically calls out the use of php -l, I doubt it would be integrated.

IIRC, it has already been suggested on several occasions, and rejected. PHPCS strives not to blow up when handed malformed code, but it doesn't try to catch every syntax error either.

**Comment by jrfnl** [comment]
FYI: there is actually a sniff upstream available which *will* run the parser over the file. Not sure how well it works, but could be worth looking into ?

Link: [`Generic.PHP.SyntaxSniff`](https://github.com/squizlabs/PHP_CodeSniffer/blob/master/CodeSniffer/Standards/Generic/Sniffs/PHP/SyntaxSniff.php)

**Comment by westonruter** [comment]
@jrfnl looks like it is just a wrapper for calling `php -l`. Probably would be a good thing to add to `WordPress-Core`.
