### ISSUE TITLE
Does this catch spaces vs tabs?

### ISSUE THREAD

**Issue by corysimmons** [WordPress-Coding-Standards/WordPress-Coding-Standards#523]
Not getting an error in Atom. Using `WordPress` config.

![image](https://cloud.githubusercontent.com/assets/224636/12820917/1c971f46-cb2f-11e5-88fd-274f6c9c5414.png)
(dots are spaces)

In fact, does the WPCS just not care about HTML inside of .php ??

**Comment by JDGrimes** [comment]
> In fact, does the WPCS just not care about HTML inside of .php ??

Yes. WPCS does flag spaces vs tabs in PHP, but not in strings or HTML.

**Comment by corysimmons** [comment]
So, according to WPCS, it's fine to mix tabs and spaces in same file...?

**Comment by JDGrimes** [comment]
No. In your PHP code you must use tabs. But I'm not sure if PHPCS can flag use of spaces in HTML. It looks like in your mixed HTML and PHP, it isn't flagging spaces in the HTML. But in a block of PHP code it should flag any spaces.

**Comment by corysimmons** [comment]
Indeed it does flag it in my PHP.

So this is a problem with phpcs?

**Comment by JDGrimes** [comment]
> So this is a problem with phpcs?

I don't know if PHPCS supports checking for spaces in HTML or not. It might be possible to have it do that by using a different configuration, or using different sniffs. You'd have to ask @gsherwood.

**Comment by corysimmons** [comment]
Alright, thanks. Will take this over there.
