### ISSUE TITLE
<script> inside <?php if () : ?> throws error

### ISSUE THREAD

**Issue by corysimmons** [WordPress-Coding-Standards/WordPress-Coding-Standards#529]
![image](https://cloud.githubusercontent.com/assets/224636/12946505/037166aa-cfc3-11e5-925a-e8df40782628.png)

This is valid right?

**Comment by corysimmons** [comment]
This might be a problem with SublimeLinter-phpcs. I'm not able to reproduce this error with the CLI.

**Comment by JDGrimes** [comment]
That must be an issue with Sublime, WPCS shouldn't be flagging that. Actually, it looks like it might not have to do with PHPCS at all, Sublime is saying that it is a parse error, so it might be a bug in the editor itself (or whatever syntax checking plugin flagging the error). You could try disabling SublimeLinter-phpcs and see if the error persists.

**Comment by corysimmons** [comment]
https://github.com/SublimeLinter/SublimeLinter-phpcs#sublimelinter-phpcs

> This linter plugin for SublimeLinter provides an interface to phpcs. It will be used with files that have the “PHP”, **“HTML” and “HTML5” syntax.**

Sorry for bothering you. =)
