### ISSUE TITLE
Better message for cat_ID?

### ISSUE THREAD

**Issue by mackensen** [WordPress-Coding-Standards/WordPress-Coding-Standards#531]
Using the deprecated/alternative `cat_ID` property of the category object trips the snake_case sniff:

```
 62 | ERROR | Variable "cat_ID" is not in valid snake_case format
```

I don't know of a reason to employ `cat_ID` instead of `term_id`, so perhaps phpcs could suggest that as a resolution?

**Comment by jrfnl** [comment]
Duplicate of #549 ? I believe this has now been solved through #551.
