### ISSUE TITLE
Another subset?

### ISSUE THREAD

**Issue by FlyerUA** [WordPress-Coding-Standards/WordPress-Coding-Standards#533]
Is it possible to get a subset without rules about spaces, new lines, etc? Basically without more of a 'formatting 'preferences' errors? Or move these 'formatting preferences' standards to a separate rules set, something like wordress-extra?
I'd rather focus on something actually important but I get flooded with errors about my formatting.

**Comment by JDGrimes** [comment]
You can run the checks from `WordPress-Extra` without the formatting checks from `WordPress-Core` with a ruleset like this:

```xml
<?xml version="1.0"?>
<ruleset name="WordPress-Extra-Only">
	<description>Extra errors without formatting errors.</description>

	<rule ref="WordPress-Extra">
		<exclude name="WordPress-Core" />
	</rule>
</ruleset>
```

Just save that in a `ruleset.xml` file and run `phpcs --standard=path/to/ruleset.xml`.

**Comment by GaryJones** [comment]
> I'd rather focus on something actually important but I get flooded with errors about my formatting.

Formatting is important - that's a key part of what a code standard defines.

**Comment by FlyerUA** [comment]
Thank you, JDGrimes
