### ISSUE TITLE
wp_die(WP_Error)

### ISSUE THREAD

**Issue by fbm-static** [WordPress-Coding-Standards/WordPress-Coding-Standards#534]
```php
if ( is_wp_error( $foo ) ) {
	/** @var \WP_Error $foo */
	wp_die( $foo );
}
```

> Expected next thing to be an escaping function, not $foo.

How do I escape `WP_Error`?

**Comment by westonruter** [comment]
So you're using a different error handler than the default, as the default `wp_die()` expects a string for the  first arg? If so, you can do:

```php
wp_die( $foo ); // WPCS: xss ok.
```

**Comment by fbm-static** [comment]
wp_die accepts either a string or an instance of WP_Error

https://core.trac.wordpress.org/browser/tags/4.4.2/src/wp-includes/functions.php#L2438

**Comment by westonruter** [comment]
Ah, good to know :) Well, there's no simple way to get PHPCS to know that you're passing in a `WP_Error` as opposed to a string to echo. It's not sophisticated enough to parse the phpdoc you have there. In any case, the `WP_Error` itself could include messages that have characters that need to be escaped, so an explicit `// WPCS: xss ok.` would flag that you acknowledge this, and that you are marking it as being safe.

**Comment by JDGrimes** [comment]
I've added a [new page to the wiki](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Escaping-a-WP_Error-object) explaining how to do this.
