### ISSUE TITLE
ConcatenationSpacing?

### ISSUE THREAD

**Issue by samwilson** [WordPress-Coding-Standards/WordPress-Coding-Standards#535]
My understanding is that the string concatenation operator `.` should be surrounded by whitespace in WordPress code. Something like the opposite of `Squiz.Strings.ConcatenationSpacing`.

The [docs read](https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage): "Always put spaces after commas, and on both sides of logical, comparison, string and assignment operators."

**Comment by westonruter** [comment]
You are right.

**Comment by samwilson** [comment]
:) I'll send a PR?

**Comment by westonruter** [comment]
Yes you will! :)

**Comment by samwilson** [comment]
Hurrah! :) Thanks for being speedy. (I'm in UTC+8 and normally feel a bit alone...)

**Comment by samwilson** [comment]
PR submitted.
