### ISSUE TITLE
WordPress.Arrays.ArrayDeclaration does not terminate

### ISSUE THREAD

**Issue by Akigiri** [WordPress-Coding-Standards/WordPress-Coding-Standards#539]
The sniff WordPress.Arrays.ArrayDeclaration does not terminate for the following code:
```
$a = array(
	'key' =>
);
```

Tested with wpcs 0.9:
`phpcs --standard=Wordpress-Core --sniffs=WordPress.Arrays.ArrayDeclaration <file>`

I do not get any error message and the phpcs thread starts to use 100% of a cpu core. In conjunction with SublimeLinter it also causes to allocate a lot of memory (probably Sublime Text's fault) which slows down the whole system even more. It only seems to occur when you have an array with closing parentheses and you start to add new items. Once you write the `T_DOUBLE_ARROW` without a trailing value the sniff causes problems. If I remove the lines 276-316 the sniff terminates again without any errors but I am not sure about exact cause.

**Comment by jrfnl** [comment]
Which version of PHPCS are you using ? Sounds like this might be an upstream issue.

**Comment by Akigiri** [comment]
I use PHP_CodeSniffer version 2.5.1 (stable)

**Comment by westonruter** [comment]
The code has a syntax error:

> Parse error: syntax error, unexpected ')'

This is outside the scope of PHP_CodeSniffer. See #522.

**Comment by Akigiri** [comment]
That makes sense. Thanks for your response.
