### ISSUE TITLE
New Logo

### ISSUE THREAD

**Issue by schlessera** [WordPress-Coding-Standards/WordPress-Coding-Standards#540]
I have created a quick logo idea following the proposal by @Rarst here: https://twitter.com/Rarst/status/709732150912876544

Feel free to use this however you see fit.

It is a cross between the official [WordPress logo](https://s.w.org/about/images/logos/wordpress-logo-notext-cmyk.pdf), using the official [WordPress Colors](https://wordpress.org/about/logos/), and the [`search`](https://github.com/WordPress/dashicons/blob/master/svg/search.svg) icon from [`dashicons`](https://github.com/WordPress/dashicons).
- [Download `wpcs-logo.svg`](https://drive.google.com/file/d/0B0SemNHyc3ksSXhZNk4tYklxS28/view?usp=sharing)
- [Download `wpcs-logo.png`](https://drive.google.com/file/d/0B0SemNHyc3ksX3BwaWV5cVNsbGM/view?usp=sharing)

![wpcs-logo.png](https://cloud.githubusercontent.com/assets/83631/13810357/baa988d0-eb6f-11e5-9368-d080f85e65d1.png)

**Comment by GaryJones** [comment]
http://wordpressfoundation.org/trademark-policy/

> **Permission from the WordPress Foundation is required to use the WordPress** or WordCamp name or **logo as part of any project**, product, service, domain or company name.

**Comment by jrfnl** [comment]
So did anyone request permission when this repo was named ? :sunglasses:

**Comment by GaryJones** [comment]
The [original project](http://urbangiraffe.com/articles/wordpress-codesniffer-standard/) was blogged about in 2009.

The WP Foundation didn't exist until 2010.

(The [trademark](http://tmsearch.uspto.gov/bin/showfield?f=doc&state=4806:tko7ga.2.8) was registered in 2006.)

**Comment by westonruter** [comment]
I consider this to be permission granted: https://ma.tt/2009/04/wordpress-codesniffer/ :smile:

**Comment by schlessera** [comment]
Well, one of you package maintainers could ask permission (provided that you like the logo, of course).

**Comment by westonruter** [comment]
I've submitted a request.

**Comment by jrfnl** [comment]
@westonruter Any update or response yet ?

**Comment by westonruter** [comment]
No.

**Comment by jrfnl** [comment]
@westonruter Just wondering - what with there being a Slack channel now and all - whether permission for the logo has been granted yet ? Maybe time to tickle whoever is responsible for these decisions ?

**Comment by ntwb** [comment]
We should look to get it added as a Dashicon also FWIW

It'll help in places such as Slack as a custom emoji and various places such as the Make P2s

**Comment by GaryJones** [comment]
If it's potentially going to be added to Dashicons, worth getting feedback from @melchoyce about the logo in general?

**Comment by melchoyce** [comment]
You'll need a one-color version for dashicons, and I don't think it'll hold up to all the detail — maybe wp + magnifying glass, but not the brackets. Bringing in @empireoflight since he's more experienced and maintaining Dashicons.

**Comment by field2** [comment]
I'm a bit confused about why we need this logo/icon and where it will appear. I think it's for the header design of the repo, and replaces the basic W logo in the top left. Where else would it be used? On first observation, it seems far too specific to warrant addition to Dashicons, but maybe I"m not fully understanding the scope here.

**Comment by Rarst** [comment]
My original observation was about GitHub organization (which right now confusingly uses generic WP logo).

Not sure why @ntwb brought up dashicons inclusion above.

**Comment by westonruter** [comment]
@jrfnl:

> Just wondering - what with there being a Slack channel now and all - whether permission for the logo has been granted yet ? Maybe time to tickle whoever is responsible for these decisions ?

There has been no discussion about officially granting the use of the WP logo. I never got a reply when I inquired.

**Comment by jrfnl** [comment]
Wowie! It took a while, but... the Coding Standards dashicon has been committed to WP Core and will be included in the WP 5.2 release! Thanks @Rarst and @schlessera for getting this started and providing the initial direction, @cathibosco for creating the icon, @desrosj for committing it and everyone else who contributed with ideas and in the discussions.

https://core.trac.wordpress.org/changeset/45040

Would be awesome if the icon for the WPCS organisation could be changed to match... :sunglasses:  @westonruter I believe you have the admin rights to do so ?

**Comment by westonruter** [comment]
> I believe you have the admin rights to do so ?

@jrfnl you do now as well! I thought you had such access already.
