### ISSUE TITLE
don't require md5() to be escaped

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#541]
Don't require the output of `md5()` to be escaped.

**Comment by jrfnl** [comment]
I've had a look at this and some other hash functions such as `sha1()`, `hash()` and `hash_hmac()`.

I would advice against this as this whole group of functions allows for passing an option argument to get the `raw` binary output. If that function argument is set, the output of these functions can definitely not be considered safe,

Suggest: close.
