### ISSUE TITLE
TravisCI integration

### ISSUE THREAD

**Issue by szepeviktor** [WordPress-Coding-Standards/WordPress-Coding-Standards#559]
Hello!

Could you advise how to use WPCS in Travis?
It would be nice to include it in the README.

**Comment by westonruter** [comment]
One implementation can be found in https://github.com/xwp/wp-dev-lib

**Comment by jrfnl** [comment]
Or a more basic example: https://github.com/jrfnl/debug-bar-localization/blob/master/.travis.yml
