### ISSUE TITLE
get_pages() incorrectly reported as uncached

### ISSUE THREAD

**Issue by davidpagepsycle** [WordPress-Coding-Standards/WordPress-Coding-Standards#569]
As noted on https://github.com/Automattic/vip-scanner/pull/310 `get_pages()` function is cached. The function is also not listed as restricted on https://vip.wordpress.com/documentation/caching/uncached-functions/. Should it therefore be removed from the restricted functions sniff?

**Comment by westonruter** [comment]
@davidpagepsycle yeah, looks like it! If you like, you can revert the relevant bits of #491.

**Comment by davidpagepsycle** [comment]
Ok at second glance though `get_pages()` is cached it does have no limit by default. So would it need to be switched to be part of the PostsPerPage sniff, detecting the lack of a 'number' arg or high setting?

**Comment by westonruter** [comment]
If VIP isn't flagging `get_pages()` as a non-caching plugin, then I don't think we'd worry about flagging it, unless maybe @sboisvert advises differently.

**Comment by sboisvert** [comment]
I think it was mistakenly on our list for a while but yes it has caching and we don't flag it.

**Comment by davidpagepsycle** [comment]
I've not removed the entire group in the PR as `get_children()` is there and that definitely doesn't cache. But it does wrap `get_posts()` so would you prefer `get_children()` to be merged into that group?

**Comment by sboisvert** [comment]
@davidpagepsycle That sounds like a good idea :)

**Comment by davidpagepsycle** [comment]
@sboisvert PR has been updated to merge the sniff groups together.
