### ISSUE TITLE
Port over checks from VIP Scanner into sniffs

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#57]
Automattic has a [VIP Scanner](https://github.com/Automattic/vip-scanner) tool which would greatly benefit from integrating PHP_CodeSniffer. From looking at the tool, the [checks](https://github.com/Automattic/vip-scanner/tree/master/vip-scanner/checks) are implemented with regular expressions and so they'll be less powerful than PHPCS's sniffs which operate on tokenized streams.

The checks in the VIP Scanner should be ported over to PHPCS sniffs, then a fine-tuned ruleset (to opt-in/opt-out of the relevant rules) could be employed by the VIP Scanner. In effect, the scanner would become just be a wrapper for PHPCS.

**Comment by GaryJones** [comment]
Can you please create a checkbox list of which checks are still needed?

**Comment by jrfnl** [comment]
What @GaryJones said :wink: or maybe even better: could separate issues be opened for the checks which are still needed (and which don't already have an issue) ?

> Can you please create a checkbox list of which checks are still needed?

**Comment by GaryJones** [comment]
Shouldn't Automattic be undertaking this change?

**Comment by jrfnl** [comment]
I'd be very much in favour of that. All the same, there will probably be some checks in there which could benefit the wider WP community - like some existing VIP sniffs already do.
For those, a case can be made to add them to WPCS and it would be useful to get some idea of what we're talking about.

**Comment by jrfnl** [comment]
@westonruter @GaryJones Can this issue be closed ? If not, it should be made more actionable.
