### ISSUE TITLE
Should there be a check for alternative open tags ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#580]
Like ASP tags and the PHP Script tag ?

Also see: https://github.com/squizlabs/PHP_CodeSniffer/issues/1063

**Comment by JDGrimes** [comment]
Yes, I think so. Using them isn't going to be portable across sites.

**Comment by jrfnl** [comment]
@JDGrimes Does the `extra` tag mean you feel this should go into the `extra` ruleset rather than the `core` ruleset ? (If so, I'll adjust the PR :sunglasses: )

**Comment by westonruter** [comment]
@jrfnl that's right. But should it not be `WordPress-Core` ruleset?

**Comment by jrfnl** [comment]
@westonruter That was what I thought as well, which is why it's there in the PR (still tweaking the PR a bit now for some outliers in the unit tests)

**Comment by JDGrimes** [comment]
I meant to ask whether others thought whether this should be extra or not. I agree that there's really no reason that it shouldn't go in the core ruleset, so I've removed the `extra` tag.
