### ISSUE TITLE
Cleanup of discouraged functions 

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#582]
We should have better separation of the different function types

A possible list
- [ ] PHPRestricted (ereg, eval and the like)
- [ ] PHPAlternativePreferred/PHPDiscouraged (create_function, curl, split and the like)
- [ ] PHPDeprecated (ereg and the like)
- [ ] PHPDevelopment (print_r and the like)
- [ ] WPDiscouraged (query_posts and the like)
- [ ] WPDeprecated (get_link and the like)
- [ ] WPCacheRestricted (get_pages, get_post_terms and the like)
- [ ] WPAlternatives (json_encode, parse_url and the like)
- [ ] VIPAlternatives (all those which have wpcom_...() alternative functions)
- [ ] BatcacheRestricted (cookies and the like)
- [ ] Theme (a few theme specific sniffs)

Currently we have the following sniffs
- [WordPress.PHP.DiscouragedFunctions](https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/theme-review-sniffs/WordPress/Sniffs/PHP/DiscouragedFunctionsSniff.php) related: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/581
- [WordPress.VIP.FileSystemWritesDisallow](https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/theme-review-sniffs/WordPress/Sniffs/VIP/FileSystemWritesDisallowSniff.php)
- [WordPress.VIP.RestrictedFunctions](https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/theme-review-sniffs/WordPress/Sniffs/VIP/RestrictedFunctionsSniff.php)
- [WordPress.VIP.SessionFunctionsUsage](https://github.com/WPTRT/WordPress-Coding-Standards/blob/feature/theme-review-sniffs/WordPress/Sniffs/VIP/SessionFunctionsUsageSniff.php)

Some of the functions being checked are duplicated or would better in another sniff.that is more general or a new sniff.

**Comment by jrfnl** [comment]
Marked #583 as duplicate.

> Some of the functions being checked are duplicated.

I'm not too worried about lines triggering several different errors from different sniff for different reasons. Sniffs can be disabled on a per sniff per project basis, so if there are several reasons a function should not be used, I'm quite happy to have it in several different sniffs.

**Comment by grappler** [comment]
I have reworked the proposal list of sniffs with a bit of inperation from @jrfnl's issue. Let me know what you think so that I can get started on the PR.

**Comment by jrfnl** [comment]
For the `PHPDevelopment` sniff, you may want to consider using or extending the upstream `Squiz.PHP.DiscouragedFunctions` which covers `error_log()`, `print_r()` and `var_dump()`.

**Comment by grappler** [comment]
Closing as completed in #633
