### ISSUE TITLE
Check for (no) PHP close tag at end of file ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#588]
While I can't seem to find the rule in the handbook, not having a PHP closing tag if it's at the end of a file is an unwritten rule AFAIK.

So... should we add it ? `PSR2.Files.ClosingTag` should do the trick or alternatively `Zend.Files.ClosingTag`.

As it's not in the handbook, probably in `extra` ?

**Comment by grappler** [comment]
Related to this: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#remove-trailing-spaces

**Comment by jrfnl** [comment]
@grappler Thanks, added the ref to the PR.
