### ISSUE TITLE
Question - why are three abstract sniffs not abstract ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#594]
Apart from the main `WordPress_Sniff`, there are three sniffs in WPCS which do not have native functionality, but look to be intended as abstract classes to be implemented in concrete child classes.

* `WordPress_Sniffs_Arrays_ArrayAssignmentRestrictionsSniff` - 3 child classes
* `WordPress_Sniffs_Functions_FunctionRestrictionsSniff` - 1 child class
* `WordPress_Sniffs_Variables_VariableRestrictionsSniff` - 1 child class

I'm wondering why these files are not at the `WordPress` root level - like the `WordPress_Sniff` - and if there is a reason why these haven't been defined as proper `abstract` classes with the same for the methods which a child theme has to implement ?

There was probably a good reason for this (at the time?), but I currently can't see one.

**Comment by JDGrimes** [comment]
Back-compat. IIRC, these sniffs may have been configured from XML files at one time, and changing them to be abstract now would break that. We *could* break things whenever we want, of course, but I decided not to at the time. 😄 

As for moving the files, I'm not sure that that would be possible with PHPCS's current autoload mechanism, although I really don't know for sure.

**Comment by jrfnl** [comment]
> Back-compat. IIRC, these sniffs may have been configured from XML files at one time, and changing them to be abstract now would break that.

That could be maintained by having a file which essentially extends the abstract class replace the current abstract classes and have the real abstracts moved.

As none of these three currently have any functionality without being extended, having them in an XML config is essentially useless anyway.

> As for moving the files, I'm not sure that that would be possible with PHPCS's current autoload mechanism, although I really don't know for sure.

I'd be happy to run some tests, but I don't think it'll be a problem as the main WP_Sniff class is also loaded from that location and PHPCS itself does it that way too.

Reason for my question was that with the Theme Review project, I already ran into one confusion with someone adjusting one of these classes instead of extending it.
I would hope that having them in the more logical location and being abstract would make it easier to understand for people new to WPCS to start contributing.

**Comment by JDGrimes** [comment]
I'd be fine making these abstract now, so long as we make sure that this gets marked as a breaking change in the changelog. But I think that you will find that they cannot be moved without changing their names. PHPCS appears to use PSR-0 autoloading.

**Comment by jrfnl** [comment]
I'll have a play it with once #590 has been merged.
