### ISSUE TITLE
Add sniff for long conditional end comments.

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#606]
From the handbook:

> Furthermore, if you have a really long block, consider whether it can be broken into two or more shorter blocks or functions. If you consider such a long block unavoidable, **please put a short comment at the end so people can tell at glance what that ending brace ends – typically this is appropriate for a logic block, longer than about 35 rows**, but any code that’s not intuitively obvious can be commented.

Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#brace-style

This rule is so far not covered, but there is a sniff available for this upstream.

The finer details of a PR for this depend on the upstream PR https://github.com/squizlabs/PHP_CodeSniffer/pull/1074 and therefore can only be added once the upstream PR has been merged and the minimum PHPCS version required for WPCS is upped to match.

If it is desired to have this functionality available before that point in time, a copy of the - adjusted - upstream sniff could be used for the time being and altered to extend the upstream class at a later point in time.

Commit in feature branch which implements the functionality based on upstream: ~~https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/6774ab0f4f756cbaedee078713098443c7a13885~~ https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/commit/c38a6c095d47229a64328b52efd1d216d39f1945

[Edit]: Travis will - of course - fail for this branch as long as the upstream PR has not been merged yet.

**Comment by GaryJones** [comment]
Personally, I can't stand these redundant comments, but the upstream patch makes sense to improve it.

**Comment by jrfnl** [comment]
> Personally, I can't stand these redundant comments

True that, but it **_is_** in the handbook, which is why I suggest for WPCS to cover it. People can always turn it off for individual projects. And at least WP only suggests it for > 35 lines.
( which would make the condition a prime candidate for refactoring anyway)

**Comment by lkraav** [comment]
I have found reasons not to be that harsh against clarity comments at the end of blocks, esp. on nested stuff where just seeing 3 closing blocks with a short comment allows quick understand of what you're seeing in complex situations. Just that manually maintaining the comment content accuracy is annoying.

**Comment by jrfnl** [comment]
> Just that manually maintaining the comment content accuracy is annoying.

@lkraav The sniff actually contains a fixer, so that can be handled for you ;-)

**Comment by jrfnl** [comment]
FYI: looks like there's some movement upstream - the PR for this has been merged. Still, there isn't a released PHPCS version which contains it atm which we could set as a minimum version, so we'd still need to bridge this with an extended class for now or wait until it is contained in a released version and the WPCS minimum required PHPCS version has caught up.

Opinions ?

**Comment by GaryJones** [comment]
For the record, how would one disable this in their phpcs.xml file?

**Comment by jrfnl** [comment]
> For the record, how would one disable this in their phpcs.xml file? 

```xml
<exclude name="Squiz.Commenting.LongConditionClosingComment" />
```

And if a different line limit or end comment is preferred, you can overrule the settings by adding the following in `phpcs.xml` (with different values for the properties):
```xml
		<rule ref="Squiz.Commenting.LongConditionClosingComment">
			<properties>
				<property name="lineLimit" value="35" />
				<property name="commentFormat" value="// End %s()." />
			</properties>
		</rule>
```
