### ISSUE TITLE
Are the unit tests also testing the fixer ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#627]
Just checking as I'm getting the impression they currently are not.

I know they are for the PHPCS repo, but get the impression the fixer functionality is not being tested in the WPCS repo.

Background:
The unit tests for the fixer file for alternative open tags in the PR for PHPCS was originally failing because of ini settings on travis (both `short_open_tag` as well as `asp_tags` being off) preventing the sniff going into fixer mode.
However the unit tests for the same for WPCS are passing fine.

Which makes me wonder of course if WPCS is only testing the sniffs and not the fixer.

**Comment by JDGrimes** [comment]
As far as I know they do. I just tested it and they did for me, but I really need to update both my PHPCS and WPCS versions, so I can't say what the current versions do.

**Comment by jrfnl** [comment]
Sorry I meant in travis.

Though actually good point about the local usage too. For me, I can see it's trying to test it as I get lots of `diff not found` errors, but the unit tests still pass locally, even though fixer can't be tested on my local machine.

**Comment by JDGrimes** [comment]
Here is your answer (yes): https://travis-ci.org/WordPress-Coding-Standards/WordPress-Coding-Standards/builds/146238537

(Note: it appears not to be on PHP 5.2 only because I happened to choose a test that is skipped on 5.2.)

**Comment by jrfnl** [comment]
Thanks for that - it's just weird in that case that the code for the Alternative Open Tags was failing in the PHPCS run (until I took some dragonic measures) and passing in the WPCS run. Will have another look at both.

**Comment by jrfnl** [comment]
Quick Q: can the test branch be removed ?

**Comment by JDGrimes** [comment]
> Quick Q: can the test branch be removed ?

Yes. And I've removed it.
