### ISSUE TITLE
Error: PHP Notice: Undefined offset: 74 in /usr/local/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php on line 107

### ISSUE THREAD

**Issue by PC888** [WordPress-Coding-Standards/WordPress-Coding-Standards#628]
Hey guys, I've just started receiving this error when editing php files. Not sure if I should be posting this here or at - https://github.com/AtomLinter/linter-phpcs

Error: PHP Notice: Undefined offset: 74 in /usr/local/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php on line 107
    at ChildProcess.<anonymous> (/Users/paulcarter/.atom/packages/linter-phpcs/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Socket.<anonymous> (internal/child_process.js:319:11)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at Pipe._onclose (net.js:469:12)

I'm running linter-phpcs/linter with phpcs and the wpcs coding standards. It's been running fine since the install 1 week ago.

When I disable linter-phpcs the errors stop.

**Comment by grappler** [comment]
I get the errors sometimes, they are normally caused by php code which has a syntax error in it. I normally just close the error and have no negative effects.

The issue may be better reported at AtomLinter/linter-phpcs as the issue only happens in Atom and not the command line.

**Comment by PC888** [comment]
Thanks grappler, I reported the issue to linter-phpcs as well, they responded and closed the ticket -

> Sounds like a PHPCS error to me. Some sniffs (especially custom/3rd-party sniffs) tend to error out when you have a syntax error in your code, or sometimes for other unknown reasons.
I'd recommend updating CodeSniffer and your ruleset and see if it solves anything, and otherwise report the error to wpcs together with the code to reproduce the error :)

**Comment by PC888** [comment]
I've updated phpcs and wpcs. 

Just opened a brand new file demo.php and typed - if

Immediately, I get this error - 

Error: PHP Notice:  Undefined offset: 58 in /usr/local/wpcs/WordPress/Sniffs/WhiteSpace/ControlStructureSpacingSniff.php on line 103
    at ChildProcess.<anonymous> (/Users/paulcarter/.atom/packages/linter-phpcs/node_modules/atom-linter/node_modules/sb-exec/lib/index.js:36:20)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:818:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)

I couldn't imagine this being a 'WP standards' issue, if it's faulting on an if statement. However, I just reset linter-phpcs code standard to the default PSR2 and I can't replicate the error, so it looks like it's with wpcs?

**Comment by jrfnl** [comment]
@PC888 Would you mind testing with the code in PR #636 ?

**Comment by PC888** [comment]
@jrfnl I replaced line 103 with the code provided in PR #636  and it seemed to solve the 'if' errors, but another purposeful syntax error with 'quote strings' brought up yet another error - 

![error2](https://cloud.githubusercontent.com/assets/20432991/17125084/e96c6102-5333-11e6-9ff4-9962c42dadf6.png)

**Comment by jrfnl** [comment]
@PC888 Ok, thanks for testing.

Regarding the new "issue":

1. This is not a WPCS issue, but would need to be solved upstream in PHPCS.
2. I believe it's caused by the mismatched quotes in your code, so if you change `echo 'It Worked";` to `echo 'It Worked';`, the issue should be gone.

**Comment by PC888** [comment]
Thanks @jrfnl I mismatched the quotes on purpose, looking for linter-phpcs to display an error message at the bottom of the screen. I just reproduced the code and got the same error.

![error3](https://cloud.githubusercontent.com/assets/20432991/17125556/ccaf8e6e-5337-11e6-9ccb-460c17739aec.png)

Is this normal functionality to get these large error boxes?

**Comment by jrfnl** [comment]
> Is this normal functionality to get these large error boxes?

That's an Atom question and has nothing to do with WPCS. I can't tell you as I don't use Atom.

**Comment by PC888** [comment]
OK, I'll keep looking, thanks for your help.

**Comment by PC888** [comment]
Hi @jrfnl, last night I completely uninstalled/reinstalled Homebrew, PHP CodeSniffer, wpcs and linter-phpcs.

> Regarding the new "issue":
 This is not a WPCS issue, but would need to be solved upstream in PHPCS.
 I believe it's caused by the mismatched quotes in your code, so if you change echo 'It Worked";
to echo 'It Worked';, the issue should be gone.

This morning, with linter-phpcs enabled and set to use 'WordPress' as it's coding standard I'm still getting the errors. I don't understand why the error is now showing in /usr/local/Cellar/php-code-sniffer/2.6.2/CodeSniffer/Standards/Squiz/Sniffs/Strings/DoubleQuoteUsageSniff.php as this would indicate that the issue is not with the wpcs codebase.

![error](https://cloud.githubusercontent.com/assets/20432991/17161294/98cc4ec6-53ef-11e6-9521-5bf579f9600b.jpg)

The problem is, that I'm only getting errrors when I set one of the 4 wpcs standards in the linter-phpcs settings. If I remove it and go back to the default PSR2; no more errors.

![error2](https://cloud.githubusercontent.com/assets/20432991/17161383/55635b6a-53f0-11e6-93c7-7d1b92c18c7b.jpg)

Short of giving up on using wpcs with Atom and PHP CodeSniffer, I don't know where else to go with this.

**Comment by jrfnl** [comment]
@PC888 Ah! But that's a different question entirely...

WPCS uses numerous upstream sniffs, including the `Squiz.Strings.DoubleQuoteUsage` sniff which is throwing the error.
Still, as that sniff - while used by WPCS - is not *maintained* as part of WPCS, it still remains an upstream issue to solve.
But I hope at least I've managed to solve the mystery of why you're seeing the message :sunglasses:
