### ISSUE TITLE
Question, branch to test projects against?

### ISSUE THREAD

**Issue by davidpagepsycle** [WordPress-Coding-Standards/WordPress-Coding-Standards#631]
The 0.10.0 milestone has no open issues so will a new version be released soon? 

Or should we test projects against the develop branch, even though it's not officially stable? 

I ask because I have projects that trigger errors when tested against the 0.9.0 release (which is far behind master anyway) yet doesn't against develop.

**Comment by westonruter** [comment]
Personally I always use the `develop` branch locally and in my Travis CI builds.

**Comment by davidpagepsycle** [comment]
Same here. At the moment though there is a lot of work being undertaken on `develop`. There are those who on the one hand want multiple developers on multiple projects to code to standards, but on the other see `develop` as a moving target, and would want something a little less fluid.

Since the `0.10.0` milestone is complete and 5 months past due, could `master` be updated and tagged?

**Comment by westonruter** [comment]
@JDGrimes should we do a release at the end of this month?

**Comment by GaryJones** [comment]
@westonruter @JDGrimes @jrfnl Release 0.10.0 on 1st August?

**Comment by JDGrimes** [comment]
> Release 0.10.0 on 1st August?


Yes. But I am already working on another project being released that day, so I can't volunteer to make it happen. (Lack of time is the only reason I haven't released 1.10.0 already.)

**Comment by jrfnl** [comment]
For the 0.10.0 release, I think it would be good to have #596 and #608 merged.

I'll also be sending in two more PRs which don't actually touch any functionality, so should be ok to merge for 0.10.0:
* The re-ordering of the `core` ruleset to follow the handbook per #602.
* A PR which will streamline and update the (file/class) documentation of WPCS and fix other persistent documentation issues, so the WPCS code base can pass the `docs` sniffs. This is a follow-up on #590 where `docs` was left out.

**Comment by jrfnl** [comment]
The two PRs I was working on for 0.10.0 mentioned above are ready for review & merge. #645 + #651
Additionally - as a side-tracked result from the work on #651 - PR #647 could be included (if not, one commit from #651 would need to be reverted.)
