### ISSUE TITLE
Javascript and CSS code standards

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#644]
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/javascript/
Ref: https://make.wordpress.org/core/handbook/best-practices/coding-standards/css/

These _can_ be sniffed by PHPCS as well, but we can also provide either instructions in the readme on how to add JSHint, JSLint and CSSLint or possibly look into adding these into WPCS.

Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-csslint
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-jshint
Ref: https://github.com/squizlabs/PHP_CodeSniffer/wiki/Configuration-Options#setting-the-path-to-jslint

And from https://github.com/squizlabs/PHP_CodeSniffer/wiki/Annotated-ruleset.xml :
`<config name="zend_ca_path" value="/path/to/ZendCodeAnalyzer"/>`

**Comment by westonruter** [comment]
See also: https://core.trac.wordpress.org/ticket/31823

**Comment by gonzela2006** [comment]
It will be great if Javascript and CSS code standards integrated into wpcs.

**Comment by westonruter** [comment]
@gonzela2006 they are\*… see:

* For CSS: https://github.com/WordPress-Coding-Standards/stylelint-config-wordpress
* For JS: https://github.com/WordPress-Coding-Standards/eslint-config-wordpress

\* They're using Stylelint and ESLint respectively, not PHPCS.

**Comment by GaryJones** [comment]
I think we're better off deferring to Stylelint and ESLint, instead of trying to replicate all the checks in PHPCS, so I'll mark this as closed.
