### ISSUE TITLE
WP_Query and get_posts argument

### ISSUE THREAD

**Issue by sboisvert** [WordPress-Coding-Standards/WordPress-Coding-Standards#662]
setting the post_type and post_status as well as setting no_found_rows should be recommended. (with the caveat that no_found_rows is only to be used if pagination is not required)

**Comment by westonruter** [comment]
Humm. It may be a challenge to indicate a “recommemdation” in PHPCS, since
it supports only warnings and errors. It would be nice if also supported
recommendations, though perhaps we could get away with a warning here.

**Comment by sboisvert** [comment]
Warning sounds good. I didn't know if it supported 'info' or some other format. We can make the longer message mention that it's not a hard and fast rule since it can't always be done.

**Comment by westonruter** [comment]
I think this can still be done.

We can make it a warning if `post_type` and `post_status` aren't explicitly supplied (if not wanted, then `any` should be provided).

As for missing `no_found_rows` I think we could make this a warning if `paged` is not present. Presumably you'd only want to get the total number of posts in a result set if there is pagination being used, and we could sniff for this by looking for `paged`. If the `paged` query var is absent, then we could make it a warning if `no_found_rows` is not present.

**Comment by sboisvert** [comment]
That would totally work! Both seem like very good additions

**Comment by GaryJones** [comment]
https://github.com/Automattic/VIP-Coding-Standards/issues/186 (if VIP-specific) would cover this.

**Comment by GaryJones** [comment]
Closing as now covered by https://github.com/Automattic/VIP-Coding-Standards/issues/186.
