### ISSUE TITLE
0.11.0

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#673]
@WordPress-Coding-Standards/collaborators 

All,

As 0.10.0 is out of the door, let's get started with 0.11.0.
There are a number of open PRs tagged with 0.11.0 which are ready for merge.
I think it would be good to merge these soon so they can be thoroughly tested by people using `develop` before they become part of a release.

So for whomever has some time: please review the open PRs tagged with 0.11.0 and give feedback, merge or give merge approval.

If you want to merge something but it needs rebasing - ping me and I'll do it asap.

See: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/637#issuecomment-242906170
>  Due to a change in the GH interface, a rebase (or update = back-merge resulting in the history being littered with unnecessary extra merges) is now needed for every PR after every merge - even if the PR would merge cleanly -.
> So ... please ping me when someone is ready to merge this and I'll rebase asap (instead of continuously doing so after every merge which gets old very fast).

> Hopefully GH will reverse/improve this change soon as this is not very workable. (I've already contacted them about it, please do so too if you think this should change)

**Comment by westonruter** [comment]
@jrfnl did you see this? https://github.com/blog/2243-rebase-and-merge-pull-requests

However, this isn't relevant anymore due to our conversation on September 13th now that we unchecked the “require branches to be update to date before merging” option under branch protection. So I think we can close this issue.

**Comment by jrfnl** [comment]
@westonruter I hadn't seen it until you mentioned it. Good development IMHO.

**Comment by grappler** [comment]
@jrfnl I think it would be good to change the issue title so it is clear what it is about. There will be most likely an issue "0.11.0" which will be related to the release.
