### ISSUE TITLE
Super global variable advice

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#680]
Sorry if I'm being annoying, but I'd like to be clear when doing these kinda things in the future (better safe than sorry).

I have a callback function for my AJAX call that looks like this:

```
add_action( 'wp_ajax_settings_save', 'settings_save_callback' );
/**
 * Settings save AJAX callback function
 *
 * @return void
 */
function settings_save_callback() {
	if ( isset( $_POST['data'] ) && '' !== $_POST['data'] ) {
		$settings = json_decode( stripcslashes( $_POST['data'] ) );
		update_option( 'settings', $settings );
	}
	wp_die();
}
```

Now, there are errors on the lines where there is a check 

`if ( isset( $_POST['data'] ) && '' !== $_POST['data'] ) {`

> Detected access of super global var $_POST, probably need manual inspection; Processing form data without nonce verification; Detected access of super global var $_POST, probably need manual inspection; Processing form data without nonce verification; 

and on the line 

`$settings = json_decode( stripcslashes( $_POST['data'] ) );`

> Detected access of super global var $_POST, probably need manual inspection; Processing form data without nonce verification; Missing wp_unslash() before sanitization; Detected usage of a non-sanitized input variable: $_POST

The function is an ajax callback one. So my `$_POST['data']` is JSON string I collect using JavaScript.

I get that I should include a nonce check, but there were [times in the past](http://stackoverflow.com/questions/36795082/nonce-fails-on-ajax-save) where, when using nonce, I couldn't get it to pass the check, no matter whether my code was correct.

Since theme settings are accessible only by administrators, I can ignore this error. But the error that confuses me is the missing `wp_unslash()` error and non-sanitized input variable. I'm already stripping the quote slashes using [stripcslashes](http://php.net/manual/en/function.stripcslashes.php), shouldn't this be enough? Or should I replace it with `wp_unslash()`?

Also where should I put `sanitize_text_field()`? before `json_decode()`, after or? 

Thanks for the clarification, and sorry for the long post.

**EDIT**

I added nonce and verification and sanitized everything like

```
function settings_save_callback() {
	if ( isset( $_POST['data'], $_POST['settings_nonce'] ) && '' !== $_POST['data'] && wp_verify_nonce( sanitize_key( $_POST['settings_nonce'] ), 'settings_nonce_action' ) ) {
		$settings = json_decode( sanitize_text_field( wp_unslash( $_POST['data'] ) ) );
		update_option( 'settings', $settings );
	}
	wp_die();
}
```

The settings are saved ok in the database, but I still get warnings and errors

>Detected access of super global var $_POST, probably need manual inspection. Detected access of super global var $_POST, probably need manual inspection. Detected access of super global var $_POST, probably need manual inspection. Processing form data without nonce verification. Detected access of super global var $_POST, probably need manual inspection. Detected access of super global var $_POST, probably need manual inspection.

**Comment by dingo-d** [comment]
Ok, I managed to fix all the warnings and errors with

```
function settings_save_callback() {
	if ( isset( $_POST['data'], $_POST['settings_nonce'] ) && wp_verify_nonce( sanitize_key( $_POST['settings_nonce'] ), 'settings_nonce_action' ) && '' !== $_POST['data'] ) { // Input var okay.
		$settings = json_decode( sanitize_text_field( wp_unslash( $_POST['data'] ) ) ); // Input var okay.
		update_option( 'settings', $settings );
	}
	wp_die();
}
```

Every check of the super global should come after the nonce check, and the validation check.

**Comment by GaryJones** [comment]
If `filter_input()` is supported, then you can sanitise as you grab from the superglobal, and WPCS doesn't complain at all.
