### ISSUE TITLE
tax_queries flagged as potentially slow

### ISSUE THREAD

**Issue by aaronjorbin** [WordPress-Coding-Standards/WordPress-Coding-Standards#690]
It seems as though the vip rules are flagging tax queries as potentially slow, but with the taxonomy changes over the last few core releases, I'm pretty sure this should no longer be the case for some (but not all) tax queries.  This depends on if the taxonomy changes have all made their way onto .com (which I'm unsure of)

**Comment by westonruter** [comment]
@aaronjorbin you're right, and there's an issue about this actually. See #661. Do you have anything to add to it?

**Comment by aaronjorbin** [comment]
Completely missed that in my search.  Apologies for the duplicate.
