### ISSUE TITLE
Missing file doc comment

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#693]
My `footer.php` looks like this

```
<?php
/**
 * Footer
 *
 * Main footer file for the theme.
 *
 * @package WordPress
 * @subpackage mytheme
 * @version 1.0.0
 * @author  ****
 * @license https://www.gnu.org/licenses/gpl-3.0.txt GNU/GPLv3
 * @link ****
 * @since  1.0.0
 */

require_once( TEMPDIR . '/inc/output-saved-footer.php' );

echo ( get_theme_mod( 'boxed_body', false ) ) ? '</div>' : '' ;
wp_footer(); ?>
</body>
</html>
```

And I still get

>Error: Missing file doc comment, Line 1, Column 6

I have similar doc blocks in other files and I don't get this error. What am I doing wrong?

**Comment by jrfnl** [comment]
This comes from an upstream sniff where part of the standard is that every `include`/`require` should also have it's own docblock. In this case, the sniff therefore sees the docblock as belonging with the `require_once` and not as a file comment.

**Comment by dingo-d** [comment]
Oh, so should I just add docblock for the `include` statement to fix it?

**Comment by jserrao** [comment]
To quiet all the PHPCS errors in VS Code I was getting on my WordPress install, I had to format my doc block JUST like this:

```
<?php
  /**
   * Footer
   *
   * Main footer file for the theme.
   *
   * @category   Components
   * @package    WordPress
   * @subpackage Theme_Name_Here
   * @author     Your Name <yourname@example.com>
   * @license    https://www.gnu.org/licenses/gpl-3.0.txt GNU/GPLv3
   * @link       https://yoursite.com
   * @since      1.0.0
   */
?>
```
