### ISSUE TITLE
Echoing theme mods

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#694]
When echoing theme mods (`get_theme_mod( $name, $default )`), I get 

> Expected next thing to be an escaping function (see Codex for 'Data Validation'), not 'get_theme_mod'

Now, this is kinda odd, since all themes must pass the Theme Check, and if you don't specify the sanitization callback (`sanitize_callback`) when setting up a theme mod, you won't pass the check (from the plugin).

So if we are already sanitizing the select/input, or whatever modification we stored to the database, isn't it assumed that the output of that same theme mod should be safe to echo even without escaping it?

**Comment by westonruter** [comment]
Sanitization and escaping serve different purposes. You sanitize input and escape output according to the context where it is echoed. A string may very well be sanitized but when used in the context of an HTML attribute it may also very well be unsafe if not escaped. Best to never assume a value will be safe and escape every time you echo any data.

**Comment by dingo-d** [comment]
Ok, thanks for the explanation :)
