### ISSUE TITLE
Overriding WordPress globals is prohibited question

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#695]
My comment function looks a lot like the one from the developers page about [wp_list_comments](https://developer.wordpress.org/reference/functions/wp_list_comments/).

```
function mytheme_comment($comment, $args, $depth) {
    $GLOBALS['comment'] = $comment;
    extract($args, EXTR_SKIP);

    if ( 'div' == $args['style'] ) {
        $tag = 'div';
        $add_below = 'comment';
    } else {
        $tag = 'li';
        $add_below = 'div-comment';
    }
?>
    ...
}
```

The error I get is that `Overriding WordPress globals is prohibited` on line where `$GLOBALS['comment'] = $comment;`

This function is used when creating comment list (looping through the comments and formatting it)

```
wp_list_comments( array( 'callback' => 'mytheme_comment' ) );
```

How to fix this issue?

**Comment by JDGrimes** [comment]
Ask yourself, "Why do I need to override the global?" I assume that you are using some function like `get_comment_author_link()` in your function, as in the example in the WP Code Reference. However, there is no need to set the `$comment` global to use that, as you can just pass in the comment/ID to it directly. So there is really no need to override the global.

**Comment by dingo-d** [comment]
That's what I was thinking, If the `wp_list_comments()` function will pull the comment, then there is really no point to overriding the global.

I'm reviewing a code, and I'm not sure why this was put there in the first place. Also the code from the above example is a bit... odd.

**Comment by JDGrimes** [comment]
Yeah, I've left a feedback note on that page alerting the curators to the issues.

**Comment by johnbillion** [comment]
I've removed that usage example altogether. The information in it isn't particularly useful.

**Comment by jrfnl** [comment]
Just checking: Can we close this issue ?
