### ISSUE TITLE
PHPCS expecting the wrong number of tabs

### ISSUE THREAD

**Issue by rodrigoprimo** [WordPress-Coding-Standards/WordPress-Coding-Standards#697]
Given the following code:

```
<td>
	<?php if ( $key->lifetime ) {
		echo 'Not applicable to lifetime subscriptions.';
	} ?>
</td>
```

If I run `phpcs --standard=WordPress-Core  example.php` I get the following error:

```
FOUND 1 ERROR AFFECTING 1 LINE
----------------------------------------------------------------------
 4 | ERROR | [x] Line indented incorrectly; expected 0 tabs, found 1
----------------------------------------------------------------------
```

Maybe I'm missing something but it seems to me that the indentation of the code above is correct and PHPCS is mistakenly reporting an error.

**Comment by grappler** [comment]
I think this would need to reported upstream https://github.com/squizlabs/PHP_CodeSniffer/

Indention is difficult to process when switching between PHP and HTML.

Related https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/679

**Comment by westonruter** [comment]
Try putting the `if` on the next line like:

```php
<td>
    <?php
    if ( $key->lifetime ) {
        echo 'Not applicable to lifetime subscriptions.';
    } 
    ?>
</td>
```

Or better yet, use the alternate syntax for control structures since they are more template-taggy:

```php
<td>
    <?php if ( $key->lifetime ) : ?>
        Not applicable to lifetime subscriptions.
    <?php endif; ?>
</td>
```

**Comment by rodrigoprimo** [comment]
Thanks for the information. Apparently this is happening by design:

https://github.com/squizlabs/PHP_CodeSniffer/issues/1143

So I'm closing this issue.
