### ISSUE TITLE
Sniff for strings containing a placeholder but no translator comment

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#714]
Strings that contain placeholders (such as `__( 'Howdy, %s' )`) should always have a corresponding `/* translators: ...*/` comment above it that provides information about the placeholder value.

AFAIK this is not [yet] a requirement or recommendation in WP's coding standards, but I think it should be.

Can such a sniff can be implemented?

**Comment by grappler** [comment]
Yes, a sniff should be possible. We would check for `%s` within a i18n function and then check if there is a translator comment before it.

**Comment by jrfnl** [comment]
Closing as duplicate of #423
