### ISSUE TITLE
Refer to coding standard in sniffs

### ISSUE THREAD

**Issue by sourcerer-mike** [WordPress-Coding-Standards/WordPress-Coding-Standards#717]
Cheerio.

Some of the sniffs are just awkward. Like the `WordPress_Sniffs_PHP_StrictComparisonsSniff` as it forces everyone to use "===" instead of "==".

I were not able to find this or other things in the codex or some other WordPress documentation lately.
So please add a link in all your sniffs refering to a website showing this coding standard or common use.

Like `@see https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#yoda-conditions`. I really bothers me by now that WPCS is nagging about things I can't find anywhere.

This StrictComparison e.g. is written down in the WordPress-VIP ruleset. So I look up https://vip.wordpress.com/documentation/vip/best-practices/wordpress-coding-standards/ and can't find it. A link to the correct place would be great in every Sniff-DocComment.

**Comment by jrfnl** [comment]
@sourcerer-mike FYI: The strict comparisons sniff is not part of the WP core ruleset, but part of the `extra` ruleset which adds sniffs for a number of common (PHP) best practices. You can chose to just use the `core` sniffs when running PHPCS from the command line or could disable the `extra` sniffs (or just this particular sniff) through a custom ruleset.

For the `VIP` ruleset, this particular check is documented here: https://vip.wordpress.com/documentation/vip/code-review-what-we-look-for/#using-instead-of

**Comment by sourcerer-mike** [comment]
Thanks for the helpful reply @jrfnl .
This is okay, but I am forced / payed to use the `extra` coding standards in one project.  Looking forward to have it a bit better documented :)

**Comment by jrfnl** [comment]
I've been thinking this over and I suggest closing this issue as `won't fix`.

Some rules are used by several rulesets (Core, Extra, VIP) and - at least for Core and VIP -, the links to documentation pages documenting/explaining the rules will be different.

I believe that the sniffs should be ruleset agnostic and should not necessarily contain links to documentation. However, the **ruleset** which includes the sniff should.

The `Core` ruleset is build up like this and contains links to (and quotes from) the handbook for _every_ sniff included in it.

The `VIP` ruleset contains links for a number of the included sniffs (not all) and could be improved, but I believe that should be the responsibility of the VIP team.

As for the `Extra` ruleset, most of the sniffs included there are common best practices and should be self-explanatory.
If at all, I think links to the PRs/issues which introduced those sniffs into the `Extra` ruleset should be sufficient as those will give the reasoning of why those sniffs were included.

**Comment by JDGrimes** [comment]
> If at all, I think links to the PRs/issues which introduced those sniffs into the Extra ruleset should be sufficient as those will give the reasoning of why those sniffs were included.

If someone wants to open a an issue/PR for that, feel free.

**Comment by sourcerer-mike** [comment]
Wow. Neither you document it for yourself, nor for others. This is really a "Close, because work" thing. I find your interest in restricting people over educating them disgusting.
Please have that as an inner issue for yourself or ignore this opinion - feel free.

**Comment by jrfnl** [comment]
@sourcerer-mike Some politeness and respect for all the work we put into this wouldn't be amiss.

You seem to be misinterpreting the reason for closing this issue. What I was saying is that the reason for including a rule is documented with links in the ruleset (not the sniff), which is the correct place for it.
I suggest you have a look at the rulesets for your education.

**Comment by grappler** [comment]
@sourcerer-mike There are a number articles that explain strict comparisons that be found easily. This is not specific to WordPress but to programing in general.

http://www.phptherightway.com/pages/The-Basics.html
https://www.copterlabs.com/strict-vs-loose-comparisons-in-php/

If you don't agree then you can ignore the sniff by excluding it in your own custom ruleset.
