### ISSUE TITLE
Whitelist wp_strip_all_tags()

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#721]
Should [`wp_strip_all_tags()`](https://developer.wordpress.org/reference/functions/wp_strip_all_tags/) be whitelisted in one of the arrays in the [base sniff](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/Sniff.php)?

**Comment by westonruter** [comment]
Whitelist as in `escapingFunctions`?

**Comment by jrfnl** [comment]
If at all, I believe it should be in `sanitizingFunctions` - AFAICS, WP core uses it mostly from within sanitization routines.
It can not be considered an escaping function as it doesn't clean up invalid unicode, nor escape meta characters, like quotes.

**Comment by GaryJones** [comment]
Yes, one of those functions arrays - whichever it may be :-)

**Comment by westonruter** [comment]
This also came up for `strip_tags()` which ultimately was decided against. See #706.

**Comment by GaryJones** [comment]
> This differs from `strip_tags()` because it removes the contents of the `<script>` and `<style>` tags. E.g. `strip_tags( '<script>something</script>' )` will return `something`. `wp_strip_all_tags( '<script>something</script>)` will return an empty string.

**Comment by westonruter** [comment]
So it could be included among `sanitizingFunctions` but not `escapingFunctions`.

**Comment by GaryJones** [comment]
The error it gives is about the next thing expecting to be an escaping function. Does that mean it should be included in both `$sanitizingFunctions` and `$escapingFunctions`?

**Comment by GaryJones** [comment]
In my case it was `echo wp_strip_all_tags( $foo );`, but I really should have `echo esc_html( wp_strip_all_tags( $foo );` to stop the complaint about the next thing expected to be an escaping function.

**Comment by grappler** [comment]
As the PR has been merged the issue could be closed.
