### ISSUE TITLE
Seems to be clipping off advice in my terminal

### ISSUE THREAD

**Issue by corysimmons** [WordPress-Coding-Standards/WordPress-Coding-Standards#724]
![image](https://cloud.githubusercontent.com/assets/224636/21083334/476c335a-bfbc-11e6-83e8-2aa839e76ca1.png)

Using Fish Shell, BobTheFish theme with PowerLine fonts.

**Comment by corysimmons** [comment]
I'm an idiot...

**Comment by corysimmons** [comment]
I hate you guys...

**Comment by GaryJones** [comment]
Would you be kind enough to share what that root issue / solution was, so others who experience the same problem know where to start checking?

**Comment by westonruter** [comment]
This would surely be a PHP_CodeSniffer issue nonetheless.

**Comment by jrfnl** [comment]
Pst... I think the _perceived_ issue was with _"Use Yoda condition check, you must"_ ...

If at all, we could probably add a `.` at the end to prevent future misperceptions...

**Comment by corysimmons** [comment]
I'm just stupid for not realizing it was a joke immediately. =)

If you miss the joke, it reads like `you must ____________________` [to fix the problem].

@jrfnl 's suggestion is correct.

**Comment by corysimmons** [comment]
The "I hate you guys" wasn't meant like "I actually hate you guys" (on the contrary, I <3 you). It was meant to read like "Alright alright, ya got me." -- more of one those things where if someone makes a bad pun, everyone just stares at them disappointedly.

**Comment by GaryJones** [comment]
Thanks for the clarifications.

@corysimmons As you've contributed before, feel free to do a PR that adds in the missing full stop :-)

**Comment by corysimmons** [comment]
Happy to, but pretty busy atm. Will try to remember to do this.

**Comment by GaryJones** [comment]
No problem - I went ahead and did it as I had the code open.

**Comment by corysimmons** [comment]
I saw that one and was going to change it, but then I figured it should _probably_ be done for every warning and thought it might be a time sink.

I think we made a mountain out of molehill and your PR solves it though so lgtm 👍
