### ISSUE TITLE
Check for nonces inside of forms (and in Ajax handlers)

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#73]
Whenever a `<form>` appears in the source, there should be a `nonce` function that appears between it and the closing `</form>`.

Checking for proper validation if nonces, however, would be quite difficult to check programatically, except in Ajax handlers.

- [ ] Look for `wp_nonce_field()` inside of `<form>` elements.
- [ ] In Ajax actions, verify that `check_ajax_referer()` or `wp_verify_nonce()` are used.

See http://codex.wordpress.org/WordPress_Nonces

Per the [VIP cod review guidelines](http://vip.wordpress.com/documentation/code-review-what-we-look-for/#filesystem-writes):

> <p>Nonces should be used to validate all form submissions.</p>

**Comment by GaryJones** [comment]
Closing in favour of #325.
