### ISSUE TITLE
New Abstract for restricting arguments in functions

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#745]
I started working on something for theme sniffs but realized this would fit better ustream. https://github.com/WPTRT/WordPress-Coding-Standards/pull/80

As we have an abstract to restrict function it would make sense to have one to restrict arguments.

A few examples for this would be 
- `get_bloginfo( 'home' )` where `home` is deprecated
- making sure the correct argument is used e.g. `date_i18n( get_option( 'date_format' ) )` #739
- requiring that a function has a certain argument `get_bloginfo( 'name', 'display' )`
- if a certain hook should not be used e.g `add_filter( 'mime_types', '' );` as it is plugin territory
- unneeded checking for backwards compatibility with `function_exist( 'add_action' )`

Related issues https://github.com/WPTRT/WordPress-Coding-Standards/issues/93 https://github.com/WPTRT/WordPress-Coding-Standards/issues/42 https://github.com/WPTRT/WordPress-Coding-Standards/issues/27 https://github.com/WPTRT/WordPress-Coding-Standards/issues/1 https://github.com/WPTRT/WordPress-Coding-Standards/issues/96
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/611

The current array is as below.
```php
array( 
'get_bloginfo' => array(
	1 => array(
		'home' => array(
			'alt'     => 'home_url()',
			'version' => '2.2'
		),
		'siteurl' => array(
			'alt'     => 'home_url()',
			'version' => '2.2'
		),
	),
),
);
```

First we have the function name, the position of the argument, the argument it should match. Alt is the alternative function for the deprecated parameter and version is when it was deprecated.

**What I unsure about is how I can differentiate when a argument should not be used and when a argument is required.**

**Comment by jrfnl** [comment]
May I suggest having an abstract class and then three concrete class - one for deprecated arguments, one for required arguments, one for checking correct usage of an argument ? Keeps the different logic isolated in different sniffs.
Does that help or did you mean something else ?

**Comment by grappler** [comment]
Thank you @jrfnl Would such a structure make sense:

- `abstract class WordPress_AbstractArgsRestrictionsSniff implements PHP_CodeSniffer_Sniff`
  - `class WordPress_RestrictedArgsSniff extends WordPress_AbstractArgsRestrictionsSnifff`
    - `class WordPress_Sniffs_Theme_DeprecatedArgsSniff extends WordPress_RestrictedArgsSniff`
  - `class WordPress_RequiredArgsSniff extends WordPress_AbstractArgsRestrictionsSnifff`
    - `class WordPress_Sniffs_XSS_BloginfoArgsSniff extends WordPress_RequiredArgsSniff`
  - `class WordPress_ControlArgsSniff extends WordPress_AbstractArgsRestrictionsSnifff`
    - `class WordPress_Sniffs_WP_DateArgsSniff extends WordPress_ControlArgsSniff`

The array for `WordPress_RestrictedArgsSnif` would be 
```php
'get_bloginfo' => array(
	2 => array(
		'home' => array(
			'alt'     => 'home_url()',
		),
		'siteurl' => array(
			'alt'     => 'home_url()',
			'version' => '2.2'
		),
	),
),
```

The array for `WordPress_RequiredArgsSniff` would be
```php
'get_bloginfo' => array(
	2 => array(
		'display',
	),
),
```

The array for `WordPress_ControlArgsSniff` would be
```php
'apply_filters' => array(
	1 => 'widget_title',
	2 => true,
	3 => true,
	4 => true,
),
```
