### ISSUE TITLE
Suggestions for addition to 'safe' function list / XSS sniff

### ISSUE THREAD

**Issue by grappler** [WordPress-Coding-Standards/WordPress-Coding-Standards#746]
I would suggest adding the following function to the safe list:
`get_the_id()` as `the_ID()` is already on the list and `get_the_id()` only echos `the_ID()` without any escaping
`get_post_class()` as `post_class()` is already on the list and `get_post_class()` echos the result from `post_class()` without escaping it.

**Comment by GaryJones** [comment]
https://core.trac.wordpress.org/ticket/20009 has been accepted for WP 5.5, so we may be able to add post_class() back into the auto escaped list.
