### ISSUE TITLE
Missing method: DiscouragedFunctionsSniff::register()

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#760]
Running PHPCS `master`, and WPCS `develop`, PhpStorm gives me:

![screenshot 2016-12-31 12 27 21](https://cloud.githubusercontent.com/assets/88371/21577497/ca864a76-cf54-11e6-9bdb-f6829a2fa87e.png)

cc @grappler

**Comment by jrfnl** [comment]
Ah! That's my fault, I suggested it could be empty and didn't think about PHPCS still autoloading it even when it's not registered in the ruleset. Sorry.
#761 should fix this.
