### ISSUE TITLE
The future of the `WordPress_Sniff` class

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#765]
As since #696, #703 and #633 have all been addressed & merged, nearly all sniffs which extended an upstream sniff have been reverted to stand-alone sniffs, I'm wondering if it's time to review the `WordPress_Sniff` class.

That class currently contains mostly static properties so other sniffs - which couldn't extend it - could use these.
It also contains a number of non-static methods (and a few such properties).

I intend to start adding a number of additional utility methods to this class in the near future to be used by a plentitude of sniffs.
These utility methods have been extensively tested over the last few months within the PHPCompatibility standard (I wrote them, so there is no licencing issue with bringing them over).
They will address things like a standardized way to determine if a `T_STRING` is a function call, getting the parameters from the function call, safely stripping the quotes off a `T_CONSTANT_ENCAPSED_STRING`, checking if something is within a namespace, getting the fully qualified function/method name etc

I imagine there might be advantages in:
* turning a number of sniffs (quite a few actually) into extended classes based on the `WordPress_Sniff` class
* turning the static properties into normal class properties
* changing the `init()` method to `process()` and once it has stored the basic information, letting it hand off to a `processToken()` method which would be implemented in the child classes instead of the current `process()` method. This would save having to pass around the `$phpcsFile` and retrieving the `$tokens` in nearly every function as they would be available as class properties instead.

Opinions ?

**Comment by grappler** [comment]
Looking forward to this.

> changing the `init()` method to `process()` ...

Would this not break backward compatibility? Which version are we aiming for here?

**Comment by jrfnl** [comment]
> Would this not break backward compatibility?

No, it would not.
PHPCS looks for the `process()` method (and has been doing this since PHPCS 1.x). At this moment it finds the `process()` method in each individual sniff. With what I'm suggesting, PHPCS would find still find that method, but now in the parent class (for those sniffs where we would implement this).
The child class can still provide it's own `process()` overloading the parent method if needed.
One advantage would be that we wouldn't have to call `$this->init()` (method in the `WordPress_Sniff` class) from within the individual sniffs, but that that would be done by default, making the `$phpcsFile`  and `$tokens` properties available througout instead of having to pass them along/calling the `$phpcsFile->getTokens()` method from each individual function.

**Comment by jrfnl** [comment]
@JDGrimes @westonruter @GaryJones Opinions on this ?
If everyone is ok with the general direction of this, I will look into changing the base class ASAP. I'm running into more and more things related to the static properties - see #786, but the same issue as I patched there, basically exists in four more sniffs. I'd prefer to work towards a more structural solution rather than adding more plasters :confused:

**Comment by JDGrimes** [comment]
I think I favor the general direction here. Though I would note that changing the properties to be non-static may break backward compatibility for some people.

The original idea behind the `WordPress_Sniff` class was that most/all of our sniffs would eventually extend it, and take advantage of the helper functions and bootstrap that it provides. So wherever this is helpful, it should be done, and whatever changes are needed in the `WordPress_Sniff` class to make it more useful for the extending sniffs should be pursued. So 👍.

**Comment by jrfnl** [comment]
> Though I would note that changing the properties to be non-static may break backward compatibility for some people.

That would only be for people who have their own sniff standard which presumes the WPCS standard is installed and build upon that, or am I forgetting something ?

A quick search here on [GH for `extends WordPress_Sniff`](https://github.com/search?p=1&q=%22extends+WordPress_Sniff%22&type=Code&utf8=%E2%9C%93) yields 138 results, nearly all submodule/vendor dirs (when will people learn not to commit those ?!), save two:
* https://github.com/Automattic/VIP-Coding-Standards/blob/master/WordPressVIPMinimum/Sniffs/VIP/ValidatedSanitizedInputSniff.php
* https://github.com/Postmedia-Digital/CI_Config/blob/master/postmedia-coding-standards/Postmedia/Sniffs/XSS/EscapeOutputSniff.php

A search for [`WordPress_Sniff::$`](https://github.com/search?utf8=%E2%9C%93&q=%22WordPress_Sniff%3A%3A%24%22&type=Code&ref=searchresults) yields 177 results, with the same two custom sniffs as the net result.

Obviously this only shows projects on GH and only if they are public, but if this is any indication, I'm not worried about breaking anything for other people ;-)

**Comment by JDGrimes** [comment]
Yes, that would be the only concern for back-compat, any code built on WPCS that is expecting those properties to be static. It looks like there isn't much to worry about, at least that is published (though I personally have some unpublished stuff likely affected by this, but it is no big deal). It's fine to break back-compat, since we're still `0.*` after all, but I thought it was worth pointing out. Thanks for doing the research to see if there is much that would break.

**Comment by jrfnl** [comment]
FYI: I have two consecutive branches ready to address this issue:
* the first will address the third bullet of the original issue
* the second (follow-on branch) will address the second bullet + will fix all the currently existing issues with custom array property merging

Bullet one is being addressed in individual PRs if and when a sniff starts using utility functions contained in the `WordPress_Sniff` class.

To pull the branches which I have currently waiting and to avoid a nightmarish scenario of merge conflicts, some of the currently open PRs will need to be merged first.
* For the first branch, PR #814 + follow-up branch (waiting in the wings) which addresses duplicate code when toggling error/warning messages + #817 + #818 need to be merged (or at least decided upon).
* For the second branch, the first branch needs to be merged + #822

**Comment by jrfnl** [comment]
FYI: I've opened issues in both affected repos to inform them.
