### ISSUE TITLE
PHPUnit is not included in the Composer dependencies

### ISSUE THREAD

**Issue by stevegrunwell** [WordPress-Coding-Standards/WordPress-Coding-Standards#766]
According to [the Contributing doc](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/CONTRIBUTING.md#unit-testing), PHPUnit should be available via `/vendor/bin/phpunit`, but the binary is not available.

Looking through the complete history of composer.json, it appears that the file has _never_ included PHPUnit, but is instead relying on it being included through PHP_CodeSniffer. Unfortunately, (to my knowledge) Composer doesn't recursively load development dependencies; a contributor would have to explicitly `cd` into `vendor/squizlabs/php_codesniffer/` and run `composer install`. Even after doing so, the `tests/AllTests.php` file referenced in the documentation doesn't appear to exist in the project.

It may be worthwhile for one of the maintainers — someone able to execute the test suite — tries a clean installation and updates the contributing guidelines.

**Comment by stevegrunwell** [comment]
Ugh, that would explain a lot. My apologies for apparently not drinking enough coffee before reading the documentation.

Since PHP_CodeSniffer doesn't package the `tests/` directory in the distribution, however (see [#548](https://github.com/squizlabs/PHP_CodeSniffer/issues/548)), contributors to WPCS need to use Composer's `--prefer-source` flag when installing locally for development.

I've opened #767 with some minor tweaks to the contributing doc.

**Comment by jrfnl** [comment]
Closing as #767 was closed as sufficiently addressed.
