### ISSUE TITLE
Error while fixing code using phpcbf 

### ISSUE THREAD

**Issue by lakinmohapatra** [WordPress-Coding-Standards/WordPress-Coding-Standards#774]
phpcbf path/file.php --standard=wordpress  
DONE in 51ms (39 fixable violations)
        => Fixing file: 1/39 violations remaining [made 50 passes]... ERROR in 2.79 secs
No fixable errors were found
Time: 2.91 secs; Memory: 10.75Mb

Please help .

**Comment by GaryJones** [comment]
This may be an upstream error - can you share your file (before and after)? We're going to need a lot more info to be able to determine where the issue is.

**Comment by jrfnl** [comment]
Closing for lack of response.
If this is still an issue, please provide the additional information requested and we can reopen the issue.
