### ISSUE TITLE
Question: Is it possible to add in this repository new ruleset?

### ISSUE THREAD

**Issue by korobochkin** [WordPress-Coding-Standards/WordPress-Coding-Standards#778]
Hi there. I have a question about this repository. I'm working on some plugins for WordPress and really love WordPress and their standards but sometimes I feel lost while writing code.

I think this idea is not common issue for WordPress and very new for community and I really want that you won't hate it.

After a lot of thinking I realized that only one thing stopping me from being happy: **snack_case** instead of **CamelCase**.

Why I think that CamelCase is more pretty:

1. More clear folders and files structure. For example:
    ```
    Admin
    Options
    - TokenOption.php
    - LastUpdateDateOption.php
    API
    - API.php
    - Actions
    -- SomeAction.php
    -- AnotherAction.php
    ```

     For bad file-folder organization checkout WooComerce or Seo by Yoast — they have hundreds of PHP files and for the first glance it's hard to know where something happens or located (thank you IDE for click by function name to open the function).

2. Composer autoloader (PSR-4). And no more tons of `require` in millions of files which makes code more complicated and hard to understand.

3. We can name files more friendly. For example, `comments.php` — what is it? Class or just plain functions inside? Maybe this class extended from some other class or implements interface?  

    But if we add one more word then it makes more sense. `CommentsModule.php` — it's a module in Jetpack!

4. This CS is used in Symfony. We can learn and get a lot of fresh ideas from Symfony.

5. WordPress itself typed in CamelCase :)

I understand that I can create my own rules in separated repository but I want to discuss this with WordPress community :) What you think?

**Comment by jrfnl** [comment]
While I appreciate that you want to start this discussion, this is not the right place IMHO.

The people here don't make up the rules. This repository and the sniffs contained therein follow the coding standards as set out by WP Core, WP VIP and common WP and PHP best practices.

Regarding the naming conventions, the WP core handbook is quite clear about these:
https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#naming-conventions

I'd suggest you ask in the WP Slack what would be a better place for this discussion.
