### ISSUE TITLE
Recognize sanitize_hex_color as a sanitization function

### ISSUE THREAD

**Issue by paulschreiber** [WordPress-Coding-Standards/WordPress-Coding-Standards#780]
WPCS should recognize `sanitize_hex_color()` as a sanitization function.

**Comment by jrfnl** [comment]
This was fixed in #781

**Comment by jrfnl** [comment]
@DannyCooper That's not necessarily up to me, but I can see your point, though I do find the inconsistency of the return values of the function a bit troubling, but that's another matter.
