### ISSUE TITLE
Use of <title> tag in rss template

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#787]
I made a custom rss template for my site and in it I have

```php
<title><?php wp_title_rss(); ?></title>
```

The code sniffer throws

```
The title tag must not be used. Use add_theme_support( 'title-tag' ) instead.
```

But this should only apply to the title tag inside the `header.php` file if I'm not mistaken. Or maybe I am. I'd like to clear my code of any errors, so I'd like to solve this one as well.

**Comment by grappler** [comment]
This is in reference to the new theme check: `WordPress.Theme.NoTitleTag`. The original issue is https://github.com/WPTRT/WordPress-Coding-Standards/issues/25

> But this should only apply to the title tag inside the `header.php` file if I'm not mistaken. 

I ran the sniff on all of the themes that have been updated in the last two years and the title tag was found in a number of places not just the `header.php`.

@dingo-d Could you share what you are doing exactly?`From my quick search it seems like this is only needed if an existing feed is being overwritten or a new feed is defined.

The only theme that is adding a custom feed is p2 but that theme is an exception in a few different ways.

My initial reaction would be that this is plugin territory as it is functionality and not design. 

This is best discussed on the WPTRT fork as this is not yet merged into WPCS.

**Comment by dingo-d** [comment]
This is from my personal site. I started reviewing what I wrote over a year ago, and I rewrote the rss feed using

~~~php
add_feed( 'rss2', 'create_my_custom_feed' );

/**
 * Custom rss feed
 *
 * @since 1.0.0
 */
function create_my_custom_feed() {
	load_template( get_template_directory() . '/feed-rss2.php' );
}
~~~

The `feed-rss2.php` has 2 instances of `<title><?php the_title_rss() ?></title>` used - inside the `<channel>` tag and inside the `<item>` tag, for each post.

So it is a unique case I guess.

But is there a general rule what to do in a case we do find multiple `<title>` tags in a theme? Especially in a theme review?

**Comment by grappler** [comment]
> I rewrote the rss feed 

Why did you need to rewrite the rss feed?

> But is there a general rule what to do in a case we do find multiple <title> tags in a theme? Especially in a theme review?

Yes, the sniff would not be an error if it was not required. Themes can only support up to 3 versions behind the current WordPress version. `add_theme_support( 'title-tag' )` was introduced in 4.1.

We have built in an exception for svg. We could potentially build in a similar exception for the title tag used in the rss feeds e.g `<channel>`.

**Comment by dingo-d** [comment]
> Why did you need to rewrite the rss feed?

I think I was getting XML validation errors on the regular feed, it was a year ago I really don't remember exactly why I did that. I think that the feed in WordPress is missing 

`xmlns:media="http://search.yahoo.com/mrss/`

so I added my own custom feed. 

I searched a bit and it looks like that fails under a plugin teritory [trac#8994](https://core.trac.wordpress.org/ticket/8994), so I guess that we don't need the exception...

**Comment by jrfnl** [comment]
I'm closing this as it relates to a sniff in the WPTRT-CS repo, not to a sniff in WPCS.
