### ISSUE TITLE
Flag front-end database writes

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#80]
I'm not sure of a programatic check for front-end database writes. Only way I can think of is to check if the current file is a WordPress template, and then check for the presence of any function that touches the database.

Is a front-end database write allowed if it is wrapped in with cache/transient? Most likely not given:

> <h4 id="post_meta-as-a-hit-counters">post_meta as a hit counters <a href="http://vip.wordpress.com/documentation/code-review-what-we-look-for/#post_meta-as-a-hit-counters" class="anchor">#</a></h4>
> 
> <p>Please don’t use post_meta to track counts of things (e.g. votes, pageviews, etc.). First of all, it won’t work properly because of caching and due to race conditions on high volume sites. It’s also just a recipe for disaster and easy way to break your site.</p>

As such, as such only time the database should be written to is if `is_user_logged_in` or if `DOING_CRON`.

This test may be better suited for PHPUnit rather than PHP_CodeSniffer.

> <h4 id="front-end-db-writes" tabindex="-1">Front-end db writes <a href="http://vip.wordpress.com/documentation/code-review-what-we-look-for/#front-end-db-writes" class="anchor">#</a></h4>
> 
> <p>Functions used on the front-end that write to the database are not allowed. This is due to scaling concerns and can easily bring down a site.</p>

**Comment by GaryJones** [comment]
Closing here as it is only applicable to VIPCS.
