### ISSUE TITLE
FileNameSniff triggers on taxonomy-{taxonomy_slug}.php files with underscores

### ISSUE THREAD

**Issue by davidpagepsycle** [WordPress-Coding-Standards/WordPress-Coding-Standards#805]
The advice when registering a [custom taxonomy](https://codex.wordpress.org/Function_Reference/register_taxonomy) is "Name should only contain lowercase letters and the underscore character", yet if you do this and have a custom taxonomy with underscores such as `resource_category` then have a theme template called `taxonomy-resource_category` the FileNameSniff triggers.

According to the [template hierarchy](https://developer.wordpress.org/themes/basics/template-hierarchy/#custom-taxonomies) documentation this sniff would also trigger if a theme were to customise based on post formats, such as `taxonomy-post_format.php`.

Seems to be that the sniff needs to take into account these taxonomy template files and allow these instances.

**Comment by jrfnl** [comment]
@grappler I'm looking to fix this. Any input on other typical file names used in themes which are considered valid exceptions ?

**Comment by GaryJones** [comment]
@jrfnl See #470 and #642.

**Comment by jrfnl** [comment]
@GaryJones Thanks! I'd forgotten about those. I guess we should close this issue as a duplicate in that case.
@davidpagepsycle Thanks for bringing it up again.

**Comment by davidpagepsycle** [comment]
Ah, sorry for the duplicate submission, didn't see it already here.
