### ISSUE TITLE
Unnecessary wp_unslash() call inside esc_url()?

### ISSUE THREAD

**Issue by fbm-static** [WordPress-Coding-Standards/WordPress-Coding-Standards#810]
When you have the following:

```
$new_url = isset( $_GET['url'] ) ? esc_url(  $_GET['url'] ) : '';
```

phpcs will output:

```
Missing wp_unslash() before sanitization
```

I tried comparing the results of `esc_url( $val )` and `esc_url( wp_unslash( $val ) )` (where val has a quotation mark) and they seem to be the same.

**Comment by JDGrimes** [comment]
What about when the URL contains backslashes though?

**Comment by westonruter** [comment]
Right, `wp_slash()` is always needed when reading from an input global.
