### ISSUE TITLE
Plugin territory whitelist

### ISSUE THREAD

**Issue by dingo-d** [WordPress-Coding-Standards/WordPress-Coding-Standards#856]
Since we don't have `WordPress-Plugin` standard (yet?), when working on plugins it's a bit annoying to see errors pointing to usage of functions that shouldn't be used in themes like `register_post_type()` and `register_taxonomy()`.

So, until we have a dedicated plugin standard, it would be useful to have a whitelist comment for plugins

~~~
// WPCS: plugin ok.
~~~

I know I can create a custom ruleset, and basically exclude every plugin sniff, I think that just whitelisting it is quicker.

Just an idea...

**Comment by JDGrimes** [comment]
What sniffs, specifically, are those errors coming from? I'm not sure that we have anything like that in WPCS. Do you have a theme-related standard installed from somewhere else, maybe?

**Comment by dingo-d** [comment]
No, I use `WordPress` coding standard, and just ignore VIP notices.

**Comment by dingo-d** [comment]
Oh, my bad! I just realized that I have `\Theme` folder in the `Sniffs` folder, which is probably from the WPTRT fork, and it's including it automatically.

**Comment by grappler** [comment]
@dingo-d It is easier not to use the `WordPres ` coding standads and choose which one you would like to use. That way when new rulesets are added they do not apply to your code.

**Comment by dingo-d** [comment]
Well I use `WordPress` because it's really strict :D I'd like to foolproof my code as much as possible :)

**Comment by grappler** [comment]
`WordPress` is the total of all of the sniffs. Once `WordPress-Theme` has been merged into this project it will run too when using `WordPress`. You can include the single rulesets and have the same strictness.

* `WordPress` — complete set with all of the sniffs in the project
  - `WordPress-Core` — main ruleset for [WordPress core coding standards](http://make.wordpress.org/core/handbook/coding-standards/)
  - `WordPress-Docs` — additional ruleset for [WordPress inline documentation standards](https://make.wordpress.org/core/handbook/best-practices/inline-documentation-standards/)
  - `WordPress-Extra` — extended ruleset for recommended best practices, not sufficiently covered in the WordPress core coding standards
    - includes `WordPress-Core`
  - `WordPress-VIP` — extended ruleset for [WordPress VIP coding requirements](http://vip.wordpress.com/documentation/code-review-what-we-look-for/)
    - includes `WordPress-Core`
