### ISSUE TITLE
Report missing escaping for PHP <?= tag

### ISSUE THREAD

**Issue by david-binda** [WordPress-Coding-Standards/WordPress-Coding-Standards#857]
While the WordPress ruleset.xml is including the `Generic.PHP.DisallowShortOpenTag` sniff, we still should report on missing escaping in case, the `<?=` is used without escaping function

**Comment by westonruter** [comment]
Taking a quick stab at this…

**Comment by david-binda** [comment]
@westonruter I have a PR almost ready.

**Comment by westonruter** [comment]
Nevermind then 😄

**Comment by david-binda** [comment]
Thanks for the quick response tho! It's really impressive.
