### ISSUE TITLE
Fatal error: Class 'WordPress_Sniff' not found

### ISSUE THREAD

**Issue by sandrodz** [WordPress-Coding-Standards/WordPress-Coding-Standards#872]
I'm getting: 

<img width="854" alt="screen shot 2017-03-12 at 9 54 25 pm" src="https://cloud.githubusercontent.com/assets/8479569/23834340/783f1958-076e-11e7-902c-fc1aa0ad30e3.png">

**Comment by jrfnl** [comment]
Which version of PHPCS are you using ?

**Comment by sandrodz** [comment]
@jrfnl I use PHP_CodeSniffer version 3.0.0RC4

**Comment by grappler** [comment]
@sandrodz WPCS does not yet support PHPCS 3. There is an issue open to add support for it. https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/718

**Comment by sandrodz** [comment]
@grappler I see, I use phpcs 3 branch because of `--basepath=`, going to close this.
