### ISSUE TITLE
Core: Capital P dangit sniff

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#876]
Just a thought: should we add a sniff which checks whether `WordPress` is spelled correctly wherever used (comments, text strings, class/function names etc) ? :sunglasses:

**Comment by grappler** [comment]
This is something that we need for the `WordPress-Theme` ruleset too.

I am not sure we should check class and function names. On the other hand we could whitelist `wordpress` when it is all small case.

**Comment by dingo-d** [comment]
We just need to be careful not to apply this rule when people put the site url `https://wordpress.org` in their code.

In themes it's usually in the footer, for example

~~~php
<div class="copyright"><?php printf( wp_kses_post( __( 'Powered by <a href="%s">WordPress</a>', 'theme-slug' ) ), 'https://wordpress.org/' ); ?></div>
~~~

In this case, the `WordPress` inside the anchor tag must have capital W and P, but the one in the url doesn't.

**Comment by jrfnl** [comment]
A PR for this is now open for review #909
