### ISSUE TITLE
Possible slow query warnings for meta queries have no whitelist flags

### ISSUE THREAD

**Issue by barryceelen** [WordPress-Coding-Standards/WordPress-Coding-Standards#894]
Possible slow query warnings for meta queries have no whitelist flags, 
Should these be added?

**Comment by grappler** [comment]
@barryceelen Do you have a code example?

**Comment by jrfnl** [comment]
@barryceelen Historically the sniff only checked for tax queries, so it has the whitelist comment `tax-query ok`, but that should work for meta queries too.
https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/wiki/Whitelisting-code-which-flags-errors#slow-taxonomy-queries

I'd like to suggest we deprecate (but still respect) the old whitelist comment and add a new one which better covers the sniff in the next version of WPCS.

**Comment by barryceelen** [comment]
@jrfnl I tried the `tax-query ok` flag, turns out I put it in the wrong place 😐…

Misread the sniff and figured the flag only worked for tax queries.
I’d be happy to create a pull request for a differently named flag. Any naming ideas?
`slow query ok` seems to imply the query is alway slow so seems a bit on the negative side to me.

**Comment by JDGrimes** [comment]
> `slow query ok` seems to imply the query is alway slow so seems a bit on the negative side to me.

Actually, if nobody has a better idea, that is actually reasonably consistent with our other sniffs. I mean, we have `XSS ok` after all. 😃

**Comment by Skatox** [comment]
Yes, this should be added. It's annoing to have that error message.
