### ISSUE TITLE
Class definitions should not be part of DiscouragedPHPFunctions warnings

### ISSUE THREAD

**Issue by fjarrett** [WordPress-Coding-Standards/WordPress-Coding-Standards#898]
This seems like a bug to me. You should be able to name your classes anything you want, especially within a namespace.

If you were going to run sniffs on class names (which I can't think of any use cases for) they'd be better off in their own `DiscouragedPHPClasses` sniff.

Consider the following `test.php`:

```php
<?php

namespace Foo;

class System {
	// Things
}

class Serialize {
	// Things
}
```

And `WordPress_Sniffs_PHP_DiscouragedPHPFunctionsSniff` will throw:

```
FILE: test.php
----------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 2 LINES
----------------------------------------------------------------------
  5 | WARNING | system() found. PHP system calls are often disabled
    |         | by server admins.
  9 | WARNING | serialize() found. Serialized data has known
    |         | vulnerability problems with Object Injection. JSON is
    |         | generally a better approach for serializing data. See
    |         | https://www.owasp.org/index.php/PHP_Object_Injection
----------------------------------------------------------------------
```

**Comment by JDGrimes** [comment]
Yes, this is definitely a bug, the sniff needs to only flag function calls and not just any `T_STRING`. Adding `T_CLASS` to [this list](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/develop/WordPress/AbstractFunctionRestrictionsSniff.php#L190) should fix the issue, I think.

**Comment by ocean90** [comment]
Related: #719
