### ISSUE TITLE
Flag bypassing of Settings API

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#91]
The only way I can think of to automate checking of this is to look for instances of `add_menu_page` or `add_submenu_page`, and for the callback argument, and then to attempt to find that callback function and check to see if it outputs any fields, and if it does, warn that they should use settings API. 

However, this seems to be better checked with PHPUnit. A unit test could be run which executes the admin page callback for each admin page and checks to see if the settings API is ever invoked during the execution of the function.

> <h4 id="not-using-the-settings-api" tabindex="-1">Not Using the Settings API <a href="http://vip.wordpress.com/documentation/code-review-what-we-look-for/#not-using-the-settings-api" class="anchor">#</a></h4>
> 
> <p>Instead of handling the output of settings pages and storage yourself, use the WordPress Settings API as it handles a lot of the heavy lifting for you including added security.</p>
> 
> <p>Make sure to also validate and sanitize submitted values from users using the sanitize callback in the <code>register_setting</code> call.</p>

**Comment by GaryJones** [comment]
Is this meant to be for VIP only, or is it something everyone could benefit from?

**Comment by jrfnl** [comment]
I think checking that `register_setting()` is always called with `sanitize_callback` set in the `$args` would be a good addition for everyone, this is covered by #126.

Checking the callback functions passed to `add_(sub)menu_page()` is something which IMHO cannot easily be done in a reliable manner with PHPCS.

**Comment by GaryJones** [comment]
Closing as VIP issues are no longer relevant here.
