### ISSUE TITLE
Todo: PHPCS 2.9.0: adjust some sniffs

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#910]
I've pulled a [PR upstream](https://github.com/squizlabs/PHP_CodeSniffer/pull/1409) in PHPCS which has just been merged, which will add a new `PHP_CodeSniffer_Tokens::$textStringTokens` array.

In contrast to the `PHP_CodeSniffer_Tokens::$stringTokens` array - which contains the token for typical PHP string variables, this new array will contain also include `T_INLINE_HTML`, `T_HEREDOC` and `T_NOWDOC`.

Up to now, we often would use `PHP_CodeSniffer_Tokens::$stringTokens` and add the other three for sniffs examining text, now this can be replaced by using `PHP_CodeSniffer_Tokens::$textStringTokens` instead.

These adjustments should only be pulled/merged when:
* PHPCS has released version ~~2.8.2 (or whatever else the next version will be called)~~ 2.9.0
* WPCS is willing to up the minimum requirement to PHPCS ~~2.8.2~~ 2.9.0

**Comment by jrfnl** [comment]
The code changes for this have been prepared: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/tree/WAIT-upstream-release/feature/issue-910-use-new-token-array

Waiting for the release of PHPCS 2.8.2 before pulling this.
The branch might need to be updated by that time for any changes in WPCS which are affected by this between then and now.

**Comment by JDGrimes** [comment]
Fixed by #937.
