### ISSUE TITLE
Access to undeclared static property

### ISSUE THREAD

**Issue by widoz** [WordPress-Coding-Standards/WordPress-Coding-Standards#940]
Got this message today after pull request.

phpcs: Fatal error: Uncaught Error: Access to undeclared static property: PHP_CodeSniffer_Tokens::$textStringTokens in /Users/wido/Sites/sniffs/wpcs/WordPress/Sniffs/WP/EnqueuedResourcesSniff.php on line 27

**Comment by JDGrimes** [comment]
WPCS `develop` now requires PHPCS 2.9+. See #937.

**Comment by widoz** [comment]
Ah, sorry me.

Thank you.
