### ISSUE TITLE
WPCS Setup issue

### ISSUE THREAD

**Issue by rinkuyadav999** [WordPress-Coding-Standards/WordPress-Coding-Standards#944]
I am setting up WPCS on Windows 10 but it is displaying PHP Fatal error.

Command and Output:

C:\xampp\php>phpcs -i
The installed coding standards are MySource, PEAR, PSR1, PSR2, Squiz, Zend, WordPress, WordPress-Core, WordPress-Docs, WordPress-Extra, WordPress-Theme and WordPress-VIP

C:\xampp\php>phpcs --standard=WordPress C:\xampp\htdocs\start\wpfree\wp-load.php
PHP Fatal error:  Class 'WordPress_AbstractArrayAssignmentRestrictionsSniff' not found in C:\xampp\php\pear\PHP\CodeSniffer\src\Standards\WordPress-Coding-Standards\WordPress\Sniffs\Arrays\ArrayAssignmentRestrictionsSniff.php on line 24

Fatal error: Class 'WordPress_AbstractArrayAssignmentRestrictionsSniff' not found in C:\xampp\php\pear\PHP\CodeSniffer\src\Standards\WordPress-Coding-Standards\WordPress\Sniffs\Arrays\ArrayAssignmentRestrictionsSniff.php on line 24

When i run phpcs -i, it displays correct installed standards but when i run a core WordPress file, it does not give output instead display 'Fatal error:'

When i change standard '--standard=Zend' it display correct output.

I can not figure out issue because when i change standard to Zend it run without error but it display error with WordPress. Means PHPCS is installed correctly but issue with WPCS.

Your help will be greatly appreciated.

**Comment by jrfnl** [comment]
PHPCS has released a new version (3.0) this week with which WPCS is not (yet) compatible. S#718
If you use PHPCS 2.9.0, things will work as expected.

**Comment by rinkuyadav999** [comment]
@jrfnl 

Yes, i installed 2.9.0 and no issue.

Thank you very much
