### ISSUE TITLE
Remove wp_get_post_terms() from VIP Restricted Functions Sniff

### ISSUE THREAD

**Issue by fklein-lu** [WordPress-Coding-Standards/WordPress-Coding-Standards#945]
The `WordPress_Sniffs_VIP_RestrictedFunctionsSniff` class checks for occurrences of `wp_get_post_terms()` usage.

This is the error message produced:
```
wp_get_post_terms() is highly discouraged due to not being cached; please use get_the_terms() along with wp_list_pluck() to extract the IDs.
```

However this is no longer true since WordPress 4.7:
* `wp_get_post_terms()` uses `wp_get_object_terms()`.
* `wp_get_object_terms()` uses `get_terms()`.
* `get_terms()` uses `WP_Term_Query()`, which is cached.

So since the function is now cached, it makes sense to remove this sniff.

**Comment by fklein-lu** [comment]
I don't think that you can set the supported version in the ruleset, unless the sniff supports it, like `WordPress_Sniffs_WP_DeprecatedFunctionsSniff`.

In this case, I don't think it's needed, since VIP environments are always up to date anyway.

**Comment by grappler** [comment]
I don't think it would be too hard to add a version check as `WordPress_Sniffs_WP_DeprecatedFunctionsSniff` extends `WordPress_AbstractFunctionRestrictionsSniff`.

> In this case, I don't think it's needed, since VIP environments are always up to date anyway.

This may be true for VIP environments but may not be for other environments where someone may be using the sniff.

**Comment by johnbillion** [comment]
I think the VIP sniffs should really represent the current best practices for the VIP environment. This means running WordPress 4.7.

The sniffs for usage of `wp_json_encode()` and `wp_parse_url()` don't sniff for the WordPress version.

**Comment by JDGrimes** [comment]
Note that these functions are still listed on the [Uncached Functions page in the VIP docs](https://vip.wordpress.com/documentation/caching/uncached-functions/). But that is probably just out of date.
