### ISSUE TITLE
Showing error when run for inspection.

### ISSUE THREAD

**Issue by emgk** [WordPress-Coding-Standards/WordPress-Coding-Standards#946]
I have installed code sniffer and copied this repo to 'standards' folder, all WordPress standards are showing.

But when I tried to run code inspection through my command prompt.
`phpcs --standard=WordPress myfile.php `

<img src="http://i.imgur.com/SA8mcR4.png"/>

**Comment by jrfnl** [comment]
Closing as duplicate of #944, #938, #872, #718 etc
