### ISSUE TITLE
WordPress.com VIP Go ruleset

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#951]
The existing `WordPress-VIP` ruleset is not technically specific to the WordPress.com VIP environment, although its sniffs _are_ based on its requirements. Lots of people use the ruleset for projects not hosted on WordPress.com VIP in order to adhere to the most stringent practices.

The new WordPress.com VIP Go environment (which is containerised) has much fewer restrictions, and therefore many of the WordPress.com VIP-specific sniffs are not relevant. As one example, you are allowed to use `switch_to_blog()` on a WordPress.com VIP Go environment.

Should a WordPress.com VIP Go specific ruleset be introduced? Is this something that belongs as part of WPCS or is this really a responsibility of Automattic? Discuss!

CCing people who've expressed interest in this: @jazzsequence @simonwheatley

**Comment by johnbillion** [comment]
Oh I just found. https://github.com/Automattic/VIP-Coding-Standards

**Comment by GaryJones** [comment]
> Is this something that belongs as part of WPCS or is this really a responsibility of Automattic?

We've had discussions elsewhere (reference needed) about whether `WordPress-VIP` should still be part of this repo or not. So in terms of a variant for WordPress VIP Go, I'd strongly suggest it should be handled by Automattic.

**Comment by grappler** [comment]
This was discussed previously here: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/pull/676

As Automattic has created their own repo we could work on a migration plan where VIP specific check are moved to their repo.

This would make it easier for them to maintain their own sniffs like: https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/945

CC/ @imsimond

**Comment by jrfnl** [comment]
Closing as superseded by #1309
