### ISSUE TITLE
JS Templating and Generic.PHP.DisallowAlternativePHPTags.MaybeASPOpenTagFound

### ISSUE THREAD

**Issue by rheinardkorf** [WordPress-Coding-Standards/WordPress-Coding-Standards#952]
On some projects we use <%- %> to incorporate JS templating into our PHP files. Obviously this triggers the "Possible use of ASP" sniff violations. 

Can we please implement one of the following into WPCS:

1. Remove this sniff.

2. Add a new whitelist option for "// WPCS: Alternate Tags Ok."

**Comment by jrfnl** [comment]
If your project uses ASP tags for JS templating, you can just disable that particular sniff/message either from the command-line or using a custom ruleset. The fact that certain JS frameworks have deemed it a "sensible choice" to use ASP tags as their delimiters is no reason to disable checking against ASP tags.

**Comment by aristath** [comment]
Why not simply use `{{ - }}` instead of `<% - %>` which is the default way WP does it for underscore templates?

**Comment by jhabdas** [comment]
Sorry to interject, but I wanted to point out Mustache-style templates will play nice with Hugo templates as well, in the future, and are easier on the fingers and increase development speed as a result.

**Comment by jrfnl** [comment]
Closing as `wontfix`
