### ISSUE TITLE
Definition of aliased classes and namespaces should be ignored

### ISSUE THREAD

**Issue by johnbillion** [WordPress-Coding-Standards/WordPress-Coding-Standards#956]
The following code gets flagged by the WordPress-VIP ruleset because it thinks that `Link` is `link()`, which is disallowed.

    use Fieldmanager_Link as Link;

Resulting sniff error:

    Filesystem writes are forbidden, you should not be using link()
    (WordPress.VIP.FileSystemWritesDisallow.file_ops_link)

The sniffs should ignore the definition of aliased classes and namespaces.

Related: #764

**Comment by jrfnl** [comment]
Related #719.

Same utility function as mentioned in https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/issues/719#issuecomment-264554267 should solve this too eventually.
