### ISSUE TITLE
WordPress Files_FileNameSniff should ignore slugs in content-{slug}.php template files

### ISSUE THREAD

**Issue by guillaumemolter** [WordPress-Coding-Standards/WordPress-Coding-Standards#957]
We should have an exception for `content-{slug}.php` since the slug can contain '_' and format not allowed by the sniff.

The same way we have an exception for:
- `archive-{slug}.php` 
- ` single-{slug}.php`
- etc. 

See: https://developer.wordpress.org/themes/template-files-section/partial-and-miscellaneous-template-files/#content-slug-php

**Comment by jrfnl** [comment]
Thanks for bringing this new template file type to our attention.

PR #958 should fix it ;-)

**Comment by guillaumemolter** [comment]
@jrfnl Damn! You were faster than I was!!

**Comment by jrfnl** [comment]
@guillaumemolter Was an easy fix to make (when you know how the unit testing for this sniff works) ;-)
