### ISSUE TITLE
Core: A comment at the end of long blocks is no longer required

### ISSUE THREAD

**Issue by pento** [WordPress-Coding-Standards/WordPress-Coding-Standards#964]
This rule can be removed.

https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards/blob/3682c0df4c4343c4759256acc3c742f4d4c05b76/WordPress-Core/ruleset.xml#L72-L80

**Comment by jrfnl** [comment]
@pento Regarding the handbook update: looks like something has gone wrong with the encoding of entities in the code samples. You may want to fix that. I've pasted an example below.
```php
<?php
// Before:
eat ( 'noodles', array( 'speed' =&gt; 'moderate' ) );

// After the update:
eat ( 'noodles', array( 'speed' =&amp;amp;gt; 'moderate' ) );
```

**Comment by pento** [comment]
Thanks for the heads up, @jrfnl, fixed. 🙃

**Comment by jrfnl** [comment]
PR #965 should fix this.
