### ISSUE TITLE
Flag use of TEMPLATEPATH and STYLESHEETPATH

### ISSUE THREAD

**Issue by westonruter** [WordPress-Coding-Standards/WordPress-Coding-Standards#97]
It is highly desirable to use `get_template_directory()` and `get_stylesheet_directory()` because these can be filtered by plugins, whereas constants cannot.

**Comment by grappler** [comment]
We have created a Sniff as part of the `WordPress-Theme` ruleset. https://github.com/WPTRT/WordPress-Coding-Standards/pull/30

**Comment by GaryJones** [comment]
@westonruter Happy for this one to be closed?

**Comment by westonruter** [comment]
Yes, because `WPTRT/WordPress-Coding-Standards` is going to be merged into WPCS?

**Comment by GaryJones** [comment]
That's my understanding.

@grappler Is that correct?

**Comment by jrfnl** [comment]
As that particular sniff is not theme specific, but should probably be placed in the `WP` category, I could update it and pull it here already. It may still be quite a while before the TRT sniffs will get pulled here, so why wait ?

**Comment by GaryJones** [comment]
That sounds good to me.
