### ISSUE TITLE
Empty statement sniff ?

### ISSUE THREAD

**Issue by jrfnl** [WordPress-Coding-Standards/WordPress-Coding-Standards#975]
Example code:
```php
function_call( $something );;
```
Fixed as:
```php
function_call( $something );
;
```

Expected fix:
```php
function_call( $something );
```

Should we add a sniff for this typo which won't cause a parse error ?

Came across this at least once so far when visually reviewing the core auto-fixes though can't find the relevant file ATM.

**Comment by JDGrimes** [comment]
#465 is kind of related.

I found a request for something similar to this upstream: https://github.com/squizlabs/PHP_CodeSniffer/issues/1119

The `Squiz.WhiteSpace.SemicolonSpacing` sniff will complain about the semicolon, I think, but it won't auto-fix.

**Comment by jrfnl** [comment]
@JDGrimes Thanks for finding that upstream issue! I did recall seeing something about this before but couldn't recall where.

Considering there is an upstream feature request for this, I suggest creating a new sniff which in due time can be pulled upstream (would not be accepted in PHPCS 2.x anymore anyhow).

Regarding #465, while loosely related, it is a distinctly separate issue as the logic needed to detect this would be completely different.

**Comment by jrfnl** [comment]
N.B.: when upstreaming the feature, it would make sense to merge it into the `Generic.CodeAnalysis.EmptyStatement` sniff which currently checks for empty control structures.
