### ISSUE TITLE
0.11.0: "Missing function doc comment" should not apply to `function __construct()`

### ISSUE THREAD

**Issue by lkraav** [WordPress-Coding-Standards/WordPress-Coding-Standards#978]
Since `__construct()` is to an extent self-documenting, why is a docblock forced here?

**Comment by JDGrimes** [comment]
I think if nothing else, the docblock is useful for the `@since` version, and to document the arguments (if there are any). I do usually omit the short and long descriptions though, unless the constructor has side-effects (which it probably shouldn't, really).

**Comment by GaryJones** [comment]
"to an extent" is not sufficient reason to make an exception here.
