### ISSUE TITLE
Set encoding to utf-8

### ISSUE THREAD

**Issue by GaryJones** [WordPress-Coding-Standards/WordPress-Coding-Standards#990]
From https://core.trac.wordpress.org/ticket/41057#comment:33

> The default encoding PHPCS 2.x uses for interpreting files is
 `ISO-8859-1`. This can be changed by setting `--encoding=utf-8` on the
 command line or using `<config name="encoding" value="utf-8"/>` in a
 custom ruleset.
>
> AFAIK, this can not be changed for an individual file, so will affect how
 all files are read.
>
>  If so desired, we can add this directive to the `WordPress-Core` ruleset
 in WPCS.

I'd definitely be +1 to this. My understanding is, files previously treated as (and only have characters from) `ISO-8859-1` should continue to be the same when treated as `utf-8`.

**Comment by jrfnl** [comment]
It should and the default encoding for PHPCS 3.x has been changed to `utf-8` anyhow.
So far, I've had one file when I was running tests with the PHPCS 3.x which gave problems with utf8.

I'd say, let's change it and see if there is any fall-out.
