### ISSUE TITLE
PHP Fatal error when using PHPCS v3.0+

### ISSUE THREAD

**Issue by bfintal** [WordPress-Coding-Standards/WordPress-Coding-Standards#996]
I get this:

    PHP Fatal error:  Interface 'PHP_CodeSniffer_Sniff' not found 

I installed PHPCS via:

    sudo pear install PHP_CodeSniffer

The error goes away when installing an older version such as:

    sudo pear install PHP_CodeSniffer-2.9.1

**Comment by JDGrimes** [comment]
Yes, PHPCS 3 is not supported yet, see #718

**Comment by bfintal** [comment]
Thanks! I'm watching that issue 👍

**Comment by elzette** [comment]
Hello! Would you mind if I ask how I would go about installing the 2.9.1 version using homebrew or composer? I have the latest version of phpcs installed, to end up with the same error. Eventually found this thread. I did have a go (or few), but think I am getting something wrong with the command line.

**Comment by miklb** [comment]
@elzette homebrew doesn't support older versions unless you have the old one still cached, in which case you can `brew switch php-code-sniffer 2.8.1` However if you've done a fresh install of homebrew or have run `brew cleanup` you can not switch. 

Unless I've missed something new.

**Comment by elzette** [comment]
Hello @miklb - thank you for your quick response. 
Indeed a fresh install... :(
Thanks for the info though, very helpful.

**Comment by JDGrimes** [comment]
You can install any version you want with composer. This will install the latest version of 2.x:

`composer global require "squizlabs/php_codesniffer=^2.9.0"`

**Comment by elzette** [comment]
Aaah brilliant! Thank you @JDGrimes - that did the trick! Much appreciated!

**Comment by GaryJones** [comment]
As an alternative, you can also do a git clone of phpcs, and then checkout the 2.9.1 tag.

**Comment by elzette** [comment]
Thanks @GaryJones, will keep that in mind.

**Comment by setokaibakg** [comment]
homebrew and older php-code-sniffer rulesets aren't friends. I was trying to use drupal-code-sniffer.

I had to do the following to get it to work on a Mac.

brew install drupal-code-sniffer (which installs php-code-sniffer 3.0.2 as req)
brew install php-code-sniffer@2.9   
which phpcs  (get location installed or look at install info)
copy /usr/local/Cellar/php-code-sniffer@2.9/2.9.1 folder to /usr/local/Cellar/php-code-sniffer/
brew switch php-code-sniffer 2.9.1

the Drupal ruleset I needed is working. (I know other people were suggesting composer but I didn't want to deal with path issues right now)

**Comment by jrfnl** [comment]
@setokaibakg Did you post this in the wrong repo ? I have no idea what PHPCS version the Drupal CS supports, so can't help you.

**Comment by setokaibakg** [comment]
It uses phpcs 2.7+ < 3.0 , what I posted above worked for me just using brew
